%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'directed_search_est_only_C';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(4,1);
M_.exo_names_tex = cell(4,1);
M_.exo_names_long = cell(4,1);
M_.exo_names(1) = {'e_ZI'};
M_.exo_names_tex(1) = {'e\_ZI'};
M_.exo_names_long(1) = {'e_ZI'};
M_.exo_names(2) = {'e_Z'};
M_.exo_names_tex(2) = {'e\_Z'};
M_.exo_names_long(2) = {'e_Z'};
M_.exo_names(3) = {'e_chi'};
M_.exo_names_tex(3) = {'e\_chi'};
M_.exo_names_long(3) = {'e_chi'};
M_.exo_names(4) = {'e_kappa'};
M_.exo_names_tex(4) = {'e\_kappa'};
M_.exo_names_long(4) = {'e_kappa'};
M_.endo_names = cell(39,1);
M_.endo_names_tex = cell(39,1);
M_.endo_names_long = cell(39,1);
M_.endo_names(1) = {'p_C'};
M_.endo_names_tex(1) = {'p\_C'};
M_.endo_names_long(1) = {'p_C'};
M_.endo_names(2) = {'p_I'};
M_.endo_names_tex(2) = {'p\_I'};
M_.endo_names_long(2) = {'p_I'};
M_.endo_names(3) = {'P_C'};
M_.endo_names_tex(3) = {'P\_C'};
M_.endo_names_long(3) = {'P_C'};
M_.endo_names(4) = {'q_C'};
M_.endo_names_tex(4) = {'q\_C'};
M_.endo_names_long(4) = {'q_C'};
M_.endo_names(5) = {'Q'};
M_.endo_names_tex(5) = {'Q'};
M_.endo_names_long(5) = {'Q'};
M_.endo_names(6) = {'C'};
M_.endo_names_tex(6) = {'C'};
M_.endo_names_long(6) = {'C'};
M_.endo_names(7) = {'I'};
M_.endo_names_tex(7) = {'I'};
M_.endo_names_long(7) = {'I'};
M_.endo_names(8) = {'Y'};
M_.endo_names_tex(8) = {'Y'};
M_.endo_names_long(8) = {'Y'};
M_.endo_names(9) = {'Gamma_C'};
M_.endo_names_tex(9) = {'Gamma\_C'};
M_.endo_names_long(9) = {'Gamma_C'};
M_.endo_names(10) = {'c_A'};
M_.endo_names_tex(10) = {'c\_A'};
M_.endo_names_long(10) = {'c_A'};
M_.endo_names(11) = {'r_I'};
M_.endo_names_tex(11) = {'r\_I'};
M_.endo_names_long(11) = {'r_I'};
M_.endo_names(12) = {'r_C'};
M_.endo_names_tex(12) = {'r\_C'};
M_.endo_names_long(12) = {'r_C'};
M_.endo_names(13) = {'w'};
M_.endo_names_tex(13) = {'w'};
M_.endo_names_long(13) = {'w'};
M_.endo_names(14) = {'L_C'};
M_.endo_names_tex(14) = {'L\_C'};
M_.endo_names_long(14) = {'L_C'};
M_.endo_names(15) = {'L_I'};
M_.endo_names_tex(15) = {'L\_I'};
M_.endo_names_long(15) = {'L_I'};
M_.endo_names(16) = {'L'};
M_.endo_names_tex(16) = {'L'};
M_.endo_names_long(16) = {'L'};
M_.endo_names(17) = {'K_C'};
M_.endo_names_tex(17) = {'K\_C'};
M_.endo_names_long(17) = {'K_C'};
M_.endo_names(18) = {'K_I'};
M_.endo_names_tex(18) = {'K\_I'};
M_.endo_names_long(18) = {'K_I'};
M_.endo_names(19) = {'K'};
M_.endo_names_tex(19) = {'K'};
M_.endo_names_long(19) = {'K'};
M_.endo_names(20) = {'lam'};
M_.endo_names_tex(20) = {'lam'};
M_.endo_names_long(20) = {'lam'};
M_.endo_names(21) = {'u_C'};
M_.endo_names_tex(21) = {'u\_C'};
M_.endo_names_long(21) = {'u_C'};
M_.endo_names(22) = {'u_I'};
M_.endo_names_tex(22) = {'u\_I'};
M_.endo_names_long(22) = {'u_I'};
M_.endo_names(23) = {'cu'};
M_.endo_names_tex(23) = {'cu'};
M_.endo_names_long(23) = {'cu'};
M_.endo_names(24) = {'Z'};
M_.endo_names_tex(24) = {'Z'};
M_.endo_names_long(24) = {'Z'};
M_.endo_names(25) = {'Z_I'};
M_.endo_names_tex(25) = {'Z\_I'};
M_.endo_names_long(25) = {'Z_I'};
M_.endo_names(26) = {'u_ZI'};
M_.endo_names_tex(26) = {'u\_ZI'};
M_.endo_names_long(26) = {'u_ZI'};
M_.endo_names(27) = {'chi'};
M_.endo_names_tex(27) = {'chi'};
M_.endo_names_long(27) = {'chi'};
M_.endo_names(28) = {'kappa'};
M_.endo_names_tex(28) = {'kappa'};
M_.endo_names_long(28) = {'kappa'};
M_.endo_names(29) = {'C_obs'};
M_.endo_names_tex(29) = {'C\_obs'};
M_.endo_names_long(29) = {'C_obs'};
M_.endo_names(30) = {'TI_obs'};
M_.endo_names_tex(30) = {'TI\_obs'};
M_.endo_names_long(30) = {'TI_obs'};
M_.endo_names(31) = {'LC_obs'};
M_.endo_names_tex(31) = {'LC\_obs'};
M_.endo_names_long(31) = {'LC_obs'};
M_.endo_names(32) = {'LI_obs'};
M_.endo_names_tex(32) = {'LI\_obs'};
M_.endo_names_long(32) = {'LI_obs'};
M_.endo_names(33) = {'Y_obs'};
M_.endo_names_tex(33) = {'Y\_obs'};
M_.endo_names_long(33) = {'Y_obs'};
M_.endo_names(34) = {'p_I_obs'};
M_.endo_names_tex(34) = {'p\_I\_obs'};
M_.endo_names_long(34) = {'p_I_obs'};
M_.endo_names(35) = {'lab_prod_obs'};
M_.endo_names_tex(35) = {'lab\_prod\_obs'};
M_.endo_names_long(35) = {'lab_prod_obs'};
M_.endo_names(36) = {'labor_share'};
M_.endo_names_tex(36) = {'labor\_share'};
M_.endo_names_long(36) = {'labor_share'};
M_.endo_names(37) = {'SR_obs'};
M_.endo_names_tex(37) = {'SR\_obs'};
M_.endo_names_long(37) = {'SR_obs'};
M_.endo_names(38) = {'w_obs'};
M_.endo_names_tex(38) = {'w\_obs'};
M_.endo_names_long(38) = {'w_obs'};
M_.endo_names(39) = {'AUX_ENDO_LAG_26_1'};
M_.endo_names_tex(39) = {'AUX\_ENDO\_LAG\_26\_1'};
M_.endo_names_long(39) = {'AUX_ENDO_LAG_26_1'};
M_.endo_partitions = struct();
M_.param_names = cell(19,1);
M_.param_names_tex = cell(19,1);
M_.param_names_long = cell(19,1);
M_.param_names(1) = {'A'};
M_.param_names_tex(1) = {'A'};
M_.param_names_long(1) = {'A'};
M_.param_names(2) = {'beta'};
M_.param_names_tex(2) = {'beta'};
M_.param_names_long(2) = {'beta'};
M_.param_names(3) = {'delta_K'};
M_.param_names_tex(3) = {'delta\_K'};
M_.param_names_long(3) = {'delta_K'};
M_.param_names(4) = {'sigma_a'};
M_.param_names_tex(4) = {'sigma\_a'};
M_.param_names_long(4) = {'sigma_a'};
M_.param_names(5) = {'psi_inv'};
M_.param_names_tex(5) = {'psi\_inv'};
M_.param_names_long(5) = {'psi_inv'};
M_.param_names(6) = {'sigma'};
M_.param_names_tex(6) = {'sigma'};
M_.param_names_long(6) = {'sigma'};
M_.param_names(7) = {'var_share'};
M_.param_names_tex(7) = {'var\_share'};
M_.param_names_long(7) = {'var_share'};
M_.param_names(8) = {'Gamma_bar'};
M_.param_names_tex(8) = {'Gamma\_bar'};
M_.param_names_long(8) = {'Gamma_bar'};
M_.param_names(9) = {'wL_Y'};
M_.param_names_tex(9) = {'wL\_Y'};
M_.param_names_long(9) = {'wL_Y'};
M_.param_names(10) = {'phi_I'};
M_.param_names_tex(10) = {'phi\_I'};
M_.param_names_long(10) = {'phi_I'};
M_.param_names(11) = {'Psi'};
M_.param_names_tex(11) = {'Psi'};
M_.param_names_long(11) = {'Psi'};
M_.param_names(12) = {'Psi_K'};
M_.param_names_tex(12) = {'Psi\_K'};
M_.param_names_long(12) = {'Psi_K'};
M_.param_names(13) = {'gam'};
M_.param_names_tex(13) = {'gam'};
M_.param_names_long(13) = {'gam'};
M_.param_names(14) = {'iota'};
M_.param_names_tex(14) = {'iota'};
M_.param_names_long(14) = {'iota'};
M_.param_names(15) = {'rho_Z'};
M_.param_names_tex(15) = {'rho\_Z'};
M_.param_names_long(15) = {'rho_Z'};
M_.param_names(16) = {'rho_ZI'};
M_.param_names_tex(16) = {'rho\_ZI'};
M_.param_names_long(16) = {'rho_ZI'};
M_.param_names(17) = {'rho_kappa'};
M_.param_names_tex(17) = {'rho\_kappa'};
M_.param_names_long(17) = {'rho_kappa'};
M_.param_names(18) = {'lambda_1'};
M_.param_names_tex(18) = {'lambda\_1'};
M_.param_names_long(18) = {'lambda_1'};
M_.param_names(19) = {'lambda_2'};
M_.param_names_tex(19) = {'lambda\_2'};
M_.param_names_long(19) = {'lambda_2'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 39;
M_.param_nbr = 19;
M_.orig_endo_nbr = 38;
M_.aux_vars(1).endo_index = 39;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 27;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(1).orig_expr = 'chi(-1)';
options_.varobs = cell(4, 1);
options_.varobs(1)  = {'LC_obs'};
options_.varobs(2)  = {'LI_obs'};
options_.varobs(3)  = {'C_obs'};
options_.varobs(4)  = {'TI_obs'};
options_.varobs_id = [ 31 32 29 30  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 38;
M_.eq_nbr = 39;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 2;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 2;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 2;
M_.lead_lag_incidence = [
 0 10 0;
 0 11 0;
 0 12 0;
 0 13 0;
 0 14 49;
 0 15 0;
 0 16 0;
 0 17 0;
 0 18 0;
 1 19 0;
 0 20 50;
 0 21 51;
 0 22 0;
 0 23 0;
 0 24 0;
 0 25 0;
 2 26 0;
 3 27 0;
 4 28 0;
 0 29 52;
 0 30 0;
 0 31 0;
 0 32 0;
 5 33 0;
 0 34 0;
 6 35 0;
 7 36 0;
 8 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 9 48 0;]';
M_.nstatic = 26;
M_.nfwrd   = 4;
M_.npred   = 9;
M_.nboth   = 0;
M_.nsfwrd   = 4;
M_.nspred   = 9;
M_.ndynamic   = 13;
M_.dynamic_tmp_nbr = [12; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Variety effect: household' ;
  2 , 'name' , 'Variety effect (investment)' ;
  3 , 'name' , 'Consumption aggregation' ;
  4 , 'name' , 'Markup (consumption)' ;
  5 , 'name' , 'Labor C' ;
  6 , 'name' , 'Labor in I' ;
  7 , 'name' , 'Capital in C' ;
  8 , 'name' , 'Capital in I' ;
  9 , 'name' , 'Labor intratemporal' ;
  10 , 'name' , 'Capital accumulation (consumption)' ;
  11 , 'name' , 'C shopping' ;
  12 , 'name' , 'Consumption multiplier' ;
  13 , 'name' , 'Euler equation of capital (C))' ;
  14 , 'name' , 'Euler equation of capital (I)' ;
  15 , 'name' , 'Capital utilization (C)' ;
  16 , 'name' , 'Capital utilization (I)' ;
  17 , 'name' , 'Relative price of investment' ;
  18 , 'name' , 'Relative price of investment' ;
  19 , 'name' , 'C production' ;
  20 , 'name' , 'I production' ;
  21 , 'name' , 'Labor composition' ;
  22 , 'name' , 'Capital composition' ;
  23 , 'name' , 'cu' ;
  24 , 'name' , 'Aggregate accounting (income = expenditures)' ;
  25 , 'name' , 'Z' ;
  26 , 'name' , 'u_ZI' ;
  27 , 'name' , 'Z_I' ;
  28 , 'name' , 'kappa' ;
  29 , 'name' , 'chi' ;
  30 , 'name' , 'C_obs' ;
  31 , 'name' , 'TI_obs' ;
  32 , 'name' , 'Y_obs' ;
  33 , 'name' , 'w_obs' ;
  34 , 'name' , 'SR_obs' ;
  35 , 'name' , 'lab_prod_obs' ;
  36 , 'name' , 'labor_share' ;
  37 , 'name' , 'LC_obs' ;
  38 , 'name' , 'LI_obs' ;
};
M_.mapping.p_C.eqidx = [1 5 18 19 30 32 ];
M_.mapping.p_I.eqidx = [2 ];
M_.mapping.P_C.eqidx = [1 3 12 ];
M_.mapping.q_C.eqidx = [1 4 5 11 19 23 ];
M_.mapping.Q.eqidx = [13 14 15 16 17 ];
M_.mapping.C.eqidx = [3 5 19 24 30 32 ];
M_.mapping.I.eqidx = [6 10 17 20 24 31 32 ];
M_.mapping.Y.eqidx = [24 ];
M_.mapping.Gamma_C.eqidx = [4 5 ];
M_.mapping.c_A.eqidx = [3 11 12 ];
M_.mapping.r_I.eqidx = [8 14 16 ];
M_.mapping.r_C.eqidx = [7 13 15 ];
M_.mapping.w.eqidx = [5 6 7 8 9 33 ];
M_.mapping.L_C.eqidx = [5 7 19 21 37 ];
M_.mapping.L_I.eqidx = [6 8 20 21 38 ];
M_.mapping.L.eqidx = [9 21 34 35 36 ];
M_.mapping.K_C.eqidx = [7 19 22 ];
M_.mapping.K_I.eqidx = [8 20 22 ];
M_.mapping.K.eqidx = [10 17 22 34 ];
M_.mapping.lam.eqidx = [9 12 13 14 ];
M_.mapping.u_C.eqidx = [7 10 15 19 23 ];
M_.mapping.u_I.eqidx = [8 10 16 20 23 ];
M_.mapping.cu.eqidx = [23 ];
M_.mapping.Z.eqidx = [19 25 27 ];
M_.mapping.Z_I.eqidx = [20 27 ];
M_.mapping.u_ZI.eqidx = [26 27 ];
M_.mapping.chi.eqidx = [9 29 ];
M_.mapping.kappa.eqidx = [11 28 ];
M_.mapping.C_obs.eqidx = [30 ];
M_.mapping.TI_obs.eqidx = [31 ];
M_.mapping.LC_obs.eqidx = [37 ];
M_.mapping.LI_obs.eqidx = [38 ];
M_.mapping.Y_obs.eqidx = [32 34 35 36 ];
M_.mapping.p_I_obs.eqidx = [18 ];
M_.mapping.lab_prod_obs.eqidx = [35 ];
M_.mapping.labor_share.eqidx = [36 ];
M_.mapping.SR_obs.eqidx = [34 ];
M_.mapping.w_obs.eqidx = [33 36 ];
M_.mapping.e_ZI.eqidx = [26 ];
M_.mapping.e_Z.eqidx = [25 ];
M_.mapping.e_chi.eqidx = [29 ];
M_.mapping.e_kappa.eqidx = [28 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [10 17 18 19 24 26 27 28 39 ];
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(39, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(19, 1);
M_.endo_trends = struct('deflator', cell(39, 1), 'log_deflator', cell(39, 1), 'growth_factor', cell(39, 1), 'log_growth_factor', cell(39, 1));
M_.NNZDerivatives = [134; 0; -1; ];
M_.static_tmp_nbr = [12; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(2) = 0.993;
beta = M_.params(2);
M_.params(5) = 0.72;
psi_inv = M_.params(5);
M_.params(6) = 1;
sigma = M_.params(6);
M_.params(12) = 2.0;
Psi_K = M_.params(12);
M_.params(16) = 0.979;
rho_ZI = M_.params(16);
M_.params(15) = 0.979;
rho_Z = M_.params(15);
M_.params(17) = 0.979;
rho_kappa = M_.params(17);
M_.params(18) = 0.979;
lambda_1 = M_.params(18);
M_.params(19) = 0.0;
lambda_2 = M_.params(19);
M_.params(9) = 0.667;
wL_Y = M_.params(9);
M_.params(10) = 0.22;
phi_I = M_.params(10);
M_.params(1) = 0.78;
A = M_.params(1);
M_.params(3) = 0.0435;
delta_K = M_.params(3);
M_.params(7) = 0.0;
var_share = M_.params(7);
M_.params(14) = 0.0;
iota = M_.params(14);
M_.params(11) = 0.25;
Psi = M_.params(11);
M_.params(13) = 0.42;
gam = M_.params(13);
M_.params(8) = 1.3;
Gamma_bar = M_.params(8);
M_.params(4) = 0.32;
sigma_a = M_.params(4);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0.0072;
M_.Sigma_e(2, 2) = 0.0072;
M_.Sigma_e(4, 4) = 0.0072;
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 6, 1.5, 0.5, 4, 2, 1.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 0.5, 0.0, 0.99, 1, 0.5, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, 0.25, 0.0, 0.5, 1, 0.2, 0.1, 0, 0.5, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, 1.1, 1.0001, 2.0, 1, 1.3, 0.20, 1.01, 2.0, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 0.3, 0.0001, 2.0, 1, 0.42, 0.3, 0.0, 2.0, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 5.0, 0.00, 30, 2, 1.57, 1.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, 0.32, 0.0, 30.0, 2, 0.32, 0.3, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.95, 0.0212, 0.99999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.95, 0.0212, 0.99999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.9, 0.0212, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.9, 0.0212, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.01, 0.0001, 0.2, 4, 0.01, 0.004, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.01, 0.00001, 0.2, 4, 0.01, 0.004, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.01, 0.0001, 0.6, 4, 0.01, 0.004, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.02, 0.0001, 0.4, 4, 0.01, 0.004, NaN, NaN, NaN ];
options_ident = struct();
options_ident.ar = 10;
dynare_identification(options_ident);
resid(1);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.TeX = true;
options_.bayesian_irf = true;
options_.lik_init = 1;
options_.mh_drop = 0.3;
options_.mh_jscale = 0.3;
options_.mh_nblck = 2;
options_.mh_replic = 250000;
options_.mode_check.status = true;
options_.mode_compute = 1;
options_.prefilter = 1;
options_.presample = 0;
options_.prior_trunc = 0;
options_.datafile = 'observables';
options_.mode_file = 'directed_search_est_mode';
options_.optim_opt = '''MaxIter'',200';
options_.order = 1;
var_list_ = {'C_obs';'TI_obs';'Y_obs';'lab_prod_obs';'labor_share';'L_C';'L_I';'L';'p_I_obs'};
oo_recursive_=dynare_estimation(var_list_);
trace_plot(options_, M_, estim_params_, 'DeepParameter', 1, 'Psi')
trace_plot(options_, M_, estim_params_, 'DeepParameter', 1, 'gam')
trace_plot(options_, M_, estim_params_, 'DeepParameter', 1, 'Gamma_bar')
options_.irf = 60;
options_.nofunctions = true;
options_.order = 1;
options_.periods = 0;
options_.conditional_variance_decomposition = [1;4;8;40;];
var_list_ = {'C_obs';'TI_obs';'Y_obs';'lab_prod_obs';'labor_share';'L_C';'L_I';'L';'p_I_obs'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'directed_search_est_only_C_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_est_only_C_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_est_only_C_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_est_only_C_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_est_only_C_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_est_only_C_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_est_only_C_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
