%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'directed_search_testing';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(5,1);
M_.exo_names_tex = cell(5,1);
M_.exo_names_long = cell(5,1);
M_.exo_names(1) = {'e_ZI'};
M_.exo_names_tex(1) = {'e\_ZI'};
M_.exo_names_long(1) = {'e_ZI'};
M_.exo_names(2) = {'e_Z'};
M_.exo_names_tex(2) = {'e\_Z'};
M_.exo_names_long(2) = {'e_Z'};
M_.exo_names(3) = {'e_shop'};
M_.exo_names_tex(3) = {'e\_shop'};
M_.exo_names_long(3) = {'e_shop'};
M_.exo_names(4) = {'e_zeta'};
M_.exo_names_tex(4) = {'e\_zeta'};
M_.exo_names_long(4) = {'e_zeta'};
M_.exo_names(5) = {'e_chi'};
M_.exo_names_tex(5) = {'e\_chi'};
M_.exo_names_long(5) = {'e_chi'};
M_.endo_names = cell(45,1);
M_.endo_names_tex = cell(45,1);
M_.endo_names_long = cell(45,1);
M_.endo_names(1) = {'p_C'};
M_.endo_names_tex(1) = {'p\_C'};
M_.endo_names_long(1) = {'p_C'};
M_.endo_names(2) = {'p_I'};
M_.endo_names_tex(2) = {'p\_I'};
M_.endo_names_long(2) = {'p_I'};
M_.endo_names(3) = {'P_C'};
M_.endo_names_tex(3) = {'P\_C'};
M_.endo_names_long(3) = {'P_C'};
M_.endo_names(4) = {'q_C'};
M_.endo_names_tex(4) = {'q\_C'};
M_.endo_names_long(4) = {'q_C'};
M_.endo_names(5) = {'q_I'};
M_.endo_names_tex(5) = {'q\_I'};
M_.endo_names_long(5) = {'q_I'};
M_.endo_names(6) = {'Q_C'};
M_.endo_names_tex(6) = {'Q\_C'};
M_.endo_names_long(6) = {'Q_C'};
M_.endo_names(7) = {'Q_I'};
M_.endo_names_tex(7) = {'Q\_I'};
M_.endo_names_long(7) = {'Q_I'};
M_.endo_names(8) = {'C'};
M_.endo_names_tex(8) = {'C'};
M_.endo_names_long(8) = {'C'};
M_.endo_names(9) = {'Gamma_C'};
M_.endo_names_tex(9) = {'Gamma\_C'};
M_.endo_names_long(9) = {'Gamma_C'};
M_.endo_names(10) = {'Gamma_I'};
M_.endo_names_tex(10) = {'Gamma\_I'};
M_.endo_names_long(10) = {'Gamma_I'};
M_.endo_names(11) = {'c_A'};
M_.endo_names_tex(11) = {'c\_A'};
M_.endo_names_long(11) = {'c_A'};
M_.endo_names(12) = {'C_util'};
M_.endo_names_tex(12) = {'C\_util'};
M_.endo_names_long(12) = {'C_util'};
M_.endo_names(13) = {'I_util'};
M_.endo_names_tex(13) = {'I\_util'};
M_.endo_names_long(13) = {'I_util'};
M_.endo_names(14) = {'I'};
M_.endo_names_tex(14) = {'I'};
M_.endo_names_long(14) = {'I'};
M_.endo_names(15) = {'I_C'};
M_.endo_names_tex(15) = {'I\_C'};
M_.endo_names_long(15) = {'I_C'};
M_.endo_names(16) = {'I_I'};
M_.endo_names_tex(16) = {'I\_I'};
M_.endo_names_long(16) = {'I_I'};
M_.endo_names(17) = {'w'};
M_.endo_names_tex(17) = {'w'};
M_.endo_names_long(17) = {'w'};
M_.endo_names(18) = {'L_C'};
M_.endo_names_tex(18) = {'L\_C'};
M_.endo_names_long(18) = {'L_C'};
M_.endo_names(19) = {'L_I'};
M_.endo_names_tex(19) = {'L\_I'};
M_.endo_names_long(19) = {'L_I'};
M_.endo_names(20) = {'L_K'};
M_.endo_names_tex(20) = {'L\_K'};
M_.endo_names_long(20) = {'L_K'};
M_.endo_names(21) = {'L'};
M_.endo_names_tex(21) = {'L'};
M_.endo_names_long(21) = {'L'};
M_.endo_names(22) = {'K_C'};
M_.endo_names_tex(22) = {'K\_C'};
M_.endo_names_long(22) = {'K_C'};
M_.endo_names(23) = {'K_I'};
M_.endo_names_tex(23) = {'K\_I'};
M_.endo_names_long(23) = {'K_I'};
M_.endo_names(24) = {'K'};
M_.endo_names_tex(24) = {'K'};
M_.endo_names_long(24) = {'K'};
M_.endo_names(25) = {'lam'};
M_.endo_names_tex(25) = {'lam'};
M_.endo_names_long(25) = {'lam'};
M_.endo_names(26) = {'D'};
M_.endo_names_tex(26) = {'D'};
M_.endo_names_long(26) = {'D'};
M_.endo_names(27) = {'u_C'};
M_.endo_names_tex(27) = {'u\_C'};
M_.endo_names_long(27) = {'u_C'};
M_.endo_names(28) = {'u_I'};
M_.endo_names_tex(28) = {'u\_I'};
M_.endo_names_long(28) = {'u_I'};
M_.endo_names(29) = {'cu'};
M_.endo_names_tex(29) = {'cu'};
M_.endo_names_long(29) = {'cu'};
M_.endo_names(30) = {'Z'};
M_.endo_names_tex(30) = {'Z'};
M_.endo_names_long(30) = {'Z'};
M_.endo_names(31) = {'Z_I'};
M_.endo_names_tex(31) = {'Z\_I'};
M_.endo_names_long(31) = {'Z_I'};
M_.endo_names(32) = {'u_ZI'};
M_.endo_names_tex(32) = {'u\_ZI'};
M_.endo_names_long(32) = {'u_ZI'};
M_.endo_names(33) = {'zeta'};
M_.endo_names_tex(33) = {'zeta'};
M_.endo_names_long(33) = {'zeta'};
M_.endo_names(34) = {'kappa'};
M_.endo_names_tex(34) = {'kappa'};
M_.endo_names_long(34) = {'kappa'};
M_.endo_names(35) = {'u_shop'};
M_.endo_names_tex(35) = {'u\_shop'};
M_.endo_names_long(35) = {'u_shop'};
M_.endo_names(36) = {'chi'};
M_.endo_names_tex(36) = {'chi'};
M_.endo_names_long(36) = {'chi'};
M_.endo_names(37) = {'Y_obs'};
M_.endo_names_tex(37) = {'Y\_obs'};
M_.endo_names_long(37) = {'Y_obs'};
M_.endo_names(38) = {'C_obs'};
M_.endo_names_tex(38) = {'C\_obs'};
M_.endo_names_long(38) = {'C_obs'};
M_.endo_names(39) = {'TI_obs'};
M_.endo_names_tex(39) = {'TI\_obs'};
M_.endo_names_long(39) = {'TI_obs'};
M_.endo_names(40) = {'p_I_obs'};
M_.endo_names_tex(40) = {'p\_I\_obs'};
M_.endo_names_long(40) = {'p_I_obs'};
M_.endo_names(41) = {'lab_prod_obs'};
M_.endo_names_tex(41) = {'lab\_prod\_obs'};
M_.endo_names_long(41) = {'lab_prod_obs'};
M_.endo_names(42) = {'SR_obs'};
M_.endo_names_tex(42) = {'SR\_obs'};
M_.endo_names_long(42) = {'SR_obs'};
M_.endo_names(43) = {'SR_util_obs'};
M_.endo_names_tex(43) = {'SR\_util\_obs'};
M_.endo_names_long(43) = {'SR_util_obs'};
M_.endo_names(44) = {'Y_util_obs'};
M_.endo_names_tex(44) = {'Y\_util\_obs'};
M_.endo_names_long(44) = {'Y_util_obs'};
M_.endo_names(45) = {'AUX_ENDO_LAG_35_1'};
M_.endo_names_tex(45) = {'AUX\_ENDO\_LAG\_35\_1'};
M_.endo_names_long(45) = {'AUX_ENDO_LAG_35_1'};
M_.endo_partitions = struct();
M_.param_names = cell(19,1);
M_.param_names_tex = cell(19,1);
M_.param_names_long = cell(19,1);
M_.param_names(1) = {'A'};
M_.param_names_tex(1) = {'A'};
M_.param_names_long(1) = {'A'};
M_.param_names(2) = {'beta'};
M_.param_names_tex(2) = {'beta'};
M_.param_names_long(2) = {'beta'};
M_.param_names(3) = {'delta_K'};
M_.param_names_tex(3) = {'delta\_K'};
M_.param_names_long(3) = {'delta_K'};
M_.param_names(4) = {'sigma_a'};
M_.param_names_tex(4) = {'sigma\_a'};
M_.param_names_long(4) = {'sigma_a'};
M_.param_names(5) = {'psi_inv'};
M_.param_names_tex(5) = {'psi\_inv'};
M_.param_names_long(5) = {'psi_inv'};
M_.param_names(6) = {'sigma'};
M_.param_names_tex(6) = {'sigma'};
M_.param_names_long(6) = {'sigma'};
M_.param_names(7) = {'var_share'};
M_.param_names_tex(7) = {'var\_share'};
M_.param_names_long(7) = {'var_share'};
M_.param_names(8) = {'Gamma_bar'};
M_.param_names_tex(8) = {'Gamma\_bar'};
M_.param_names_long(8) = {'Gamma_bar'};
M_.param_names(9) = {'wL_Y'};
M_.param_names_tex(9) = {'wL\_Y'};
M_.param_names_long(9) = {'wL_Y'};
M_.param_names(10) = {'phi_I'};
M_.param_names_tex(10) = {'phi\_I'};
M_.param_names_long(10) = {'phi_I'};
M_.param_names(11) = {'Psi'};
M_.param_names_tex(11) = {'Psi'};
M_.param_names_long(11) = {'Psi'};
M_.param_names(12) = {'Psi_K'};
M_.param_names_tex(12) = {'Psi\_K'};
M_.param_names_long(12) = {'Psi_K'};
M_.param_names(13) = {'gam'};
M_.param_names_tex(13) = {'gam'};
M_.param_names_long(13) = {'gam'};
M_.param_names(14) = {'rho_Z'};
M_.param_names_tex(14) = {'rho\_Z'};
M_.param_names_long(14) = {'rho_Z'};
M_.param_names(15) = {'rho_ZI'};
M_.param_names_tex(15) = {'rho\_ZI'};
M_.param_names_long(15) = {'rho_ZI'};
M_.param_names(16) = {'rho_shop'};
M_.param_names_tex(16) = {'rho\_shop'};
M_.param_names_long(16) = {'rho_shop'};
M_.param_names(17) = {'rho_zeta'};
M_.param_names_tex(17) = {'rho\_zeta'};
M_.param_names_long(17) = {'rho_zeta'};
M_.param_names(18) = {'lambda_1'};
M_.param_names_tex(18) = {'lambda\_1'};
M_.param_names_long(18) = {'lambda_1'};
M_.param_names(19) = {'lambda_2'};
M_.param_names_tex(19) = {'lambda\_2'};
M_.param_names_long(19) = {'lambda_2'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 45;
M_.param_nbr = 19;
M_.orig_endo_nbr = 44;
M_.aux_vars(1).endo_index = 45;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 36;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(1).orig_expr = 'chi(-1)';
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 44;
M_.eq_nbr = 45;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 2;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 2;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 2;
M_.lead_lag_incidence = [
 0 13 0;
 0 14 0;
 0 15 0;
 0 16 0;
 0 17 0;
 0 18 58;
 0 19 59;
 0 20 60;
 0 21 61;
 0 22 62;
 0 23 0;
 0 24 0;
 0 25 0;
 0 26 63;
 1 27 0;
 2 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 3 34 64;
 4 35 65;
 0 36 0;
 0 37 66;
 0 38 0;
 5 39 67;
 6 40 68;
 0 41 0;
 7 42 0;
 8 43 0;
 0 44 0;
 9 45 0;
 0 46 0;
 10 47 0;
 11 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 12 57 0;]';
M_.nstatic = 26;
M_.nfwrd   = 7;
M_.npred   = 8;
M_.nboth   = 4;
M_.nsfwrd   = 11;
M_.nspred   = 12;
M_.ndynamic   = 19;
M_.dynamic_tmp_nbr = [9; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Variety effect: household' ;
  2 , 'name' , 'Variety effect (investment)' ;
  3 , 'name' , 'Consumption aggregation' ;
  4 , 'name' , 'Markup (consumption)' ;
  5 , 'name' , 'Markup (investment)' ;
  6 , 'name' , 'Labor in retail' ;
  7 , 'name' , 'Labor in investment' ;
  8 , 'name' , 'Employment in investment shopping' ;
  9 , 'name' , 'Labor intratemporal' ;
  10 , 'name' , 'Capital accumulation (consumption)' ;
  11 , 'name' , 'Capital accumulation (investment)' ;
  12 , 'name' , 'HH shopping' ;
  13 , 'name' , 'q_I' ;
  14 , 'name' , 'Consumption multiplier' ;
  15 , 'name' , 'Euler equation of capital (C))' ;
  16 , 'name' , 'Euler equation of capital (I)' ;
  17 , 'name' , 'Capital utilization (C)' ;
  18 , 'name' , 'Capital utilization (I)' ;
  19 , 'name' , 'Relative price of capital good: consumption' ;
  20 , 'name' , 'Relative price of capital good: investment' ;
  21 , 'name' , 'Relative price of investment' ;
  22 , 'name' , 'Retail production' ;
  23 , 'name' , 'Investment production' ;
  24 , 'name' , 'C_util' ;
  25 , 'name' , 'Investment (utilization-adjusted)' ;
  26 , 'name' , 'Labor composition' ;
  27 , 'name' , 'Capital composition' ;
  28 , 'name' , 'Investment composition' ;
  29 , 'name' , 'Capacity utilization' ;
  30 , 'name' , 'Aggregate accounting (income = expenditures)' ;
  31 , 'name' , 'Z' ;
  32 , 'name' , 'u_ZI' ;
  33 , 'name' , 'Z_I' ;
  34 , 'name' , 'u_shop' ;
  35 , 'name' , 'kappa' ;
  36 , 'name' , 'zeta' ;
  37 , 'name' , 'chi' ;
  38 , 'name' , 'C_obs' ;
  39 , 'name' , 'TI_obs' ;
  40 , 'name' , 'Y_obs' ;
  41 , 'name' , 'Y_util_obs' ;
  42 , 'name' , 'SR_obs' ;
  43 , 'name' , 'SR_util_obs' ;
  44 , 'name' , 'lab_prod_obs' ;
};
M_.mapping.p_C.eqidx = [1 21 22 24 38 40 41 ];
M_.mapping.p_I.eqidx = [2 21 23 25 39 40 41 ];
M_.mapping.P_C.eqidx = [1 3 9 14 ];
M_.mapping.q_C.eqidx = [1 4 12 22 29 ];
M_.mapping.q_I.eqidx = [2 5 13 23 29 ];
M_.mapping.Q_C.eqidx = [15 17 19 ];
M_.mapping.Q_I.eqidx = [16 18 20 ];
M_.mapping.C.eqidx = [3 6 15 17 22 30 38 40 ];
M_.mapping.Gamma_C.eqidx = [4 6 15 17 ];
M_.mapping.Gamma_I.eqidx = [5 7 16 18 ];
M_.mapping.c_A.eqidx = [3 9 12 14 ];
M_.mapping.C_util.eqidx = [24 41 ];
M_.mapping.I_util.eqidx = [25 41 ];
M_.mapping.I.eqidx = [7 8 16 18 23 28 39 40 ];
M_.mapping.I_C.eqidx = [10 19 28 ];
M_.mapping.I_I.eqidx = [11 20 28 ];
M_.mapping.w.eqidx = [6 7 8 9 ];
M_.mapping.L_C.eqidx = [6 22 24 26 ];
M_.mapping.L_I.eqidx = [7 23 25 26 ];
M_.mapping.L_K.eqidx = [8 13 26 ];
M_.mapping.L.eqidx = [9 26 42 43 44 ];
M_.mapping.K_C.eqidx = [10 15 17 19 22 24 27 ];
M_.mapping.K_I.eqidx = [11 16 18 20 23 25 27 ];
M_.mapping.K.eqidx = [27 42 43 ];
M_.mapping.lam.eqidx = [14 15 16 ];
M_.mapping.D.eqidx = [30 ];
M_.mapping.u_C.eqidx = [10 15 17 22 29 ];
M_.mapping.u_I.eqidx = [11 16 18 23 29 ];
M_.mapping.cu.eqidx = [29 ];
M_.mapping.Z.eqidx = [22 24 31 33 ];
M_.mapping.Z_I.eqidx = [23 25 32 33 ];
M_.mapping.u_ZI.eqidx = [32 33 ];
M_.mapping.zeta.eqidx = [13 36 ];
M_.mapping.kappa.eqidx = [12 35 ];
M_.mapping.u_shop.eqidx = [34 35 ];
M_.mapping.chi.eqidx = [9 37 ];
M_.mapping.Y_obs.eqidx = [40 42 44 ];
M_.mapping.C_obs.eqidx = [38 ];
M_.mapping.TI_obs.eqidx = [39 ];
M_.mapping.p_I_obs.eqidx = [21 ];
M_.mapping.lab_prod_obs.eqidx = [44 ];
M_.mapping.SR_obs.eqidx = [42 ];
M_.mapping.SR_util_obs.eqidx = [43 ];
M_.mapping.Y_util_obs.eqidx = [41 43 ];
M_.mapping.e_ZI.eqidx = [32 ];
M_.mapping.e_Z.eqidx = [31 ];
M_.mapping.e_shop.eqidx = [34 ];
M_.mapping.e_zeta.eqidx = [36 ];
M_.mapping.e_chi.eqidx = [37 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [15 16 22 23 27 28 30 31 33 35 36 45 ];
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(45, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(19, 1);
M_.endo_trends = struct('deflator', cell(45, 1), 'log_deflator', cell(45, 1), 'growth_factor', cell(45, 1), 'log_growth_factor', cell(45, 1));
M_.NNZDerivatives = [171; 0; -1; ];
M_.static_tmp_nbr = [9; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(2) = 0.993;
beta = M_.params(2);
M_.params(5) = 0.72;
psi_inv = M_.params(5);
phi = 0.5;
M_.params(6) = 1.0;
sigma = M_.params(6);
M_.params(12) = 4.0;
Psi_K = M_.params(12);
M_.params(15) = 0.979;
rho_ZI = M_.params(15);
M_.params(14) = 0.979;
rho_Z = M_.params(14);
M_.params(16) = 0.979;
rho_shop = M_.params(16);
M_.params(17) = 0.979;
rho_zeta = M_.params(17);
M_.params(18) = 0.979;
lambda_1 = M_.params(18);
M_.params(19) = 0.0;
lambda_2 = M_.params(19);
M_.params(9) = 0.667;
wL_Y = M_.params(9);
M_.params(10) = 0.22;
phi_I = M_.params(10);
M_.params(7) = 0.5;
var_share = M_.params(7);
M_.params(1) = 0.78;
A = M_.params(1);
M_.params(3) = 0.0435;
delta_K = M_.params(3);
M_.params(11) = 0.25;
Psi = M_.params(11);
M_.params(13) = 0.42;
gam = M_.params(13);
M_.params(8) = 1.35;
Gamma_bar = M_.params(8);
M_.params(4) = 0.32;
sigma_a = M_.params(4);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0.0072;
M_.Sigma_e(2, 2) = 0.0072;
M_.Sigma_e(3, 3) = 0.0072;
M_.Sigma_e(4, 4) = 0.0072;
options_.irf = 100;
options_.nofunctions = true;
options_.order = 1;
options_.periods = 0;
options_.conditional_variance_decomposition = [1;4;8;40;];
var_list_ = {'C_obs';'Y_obs';'D';'lab_prod_obs';'SR_obs';'cu';'TI_obs';'L_C';'L_I';'L';'p_I_obs';'Gamma_C';'Gamma_I'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'directed_search_testing_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_testing_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_testing_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_testing_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_testing_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_testing_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_testing_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
