%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'BRS_sectoral';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(9,1);
M_.exo_names_tex = cell(9,1);
M_.exo_names_long = cell(9,1);
M_.exo_names(1) = {'e_g'};
M_.exo_names_tex(1) = {'{e_g}'};
M_.exo_names_long(1) = {'Labor-augmenting-technology growth shock'};
M_.exo_names(2) = {'e_Z'};
M_.exo_names_tex(2) = {'{e_Z}'};
M_.exo_names_long(2) = {'TFP shock'};
M_.exo_names(3) = {'e_ZI'};
M_.exo_names_tex(3) = {'{e_{ZI}}'};
M_.exo_names_long(3) = {'Investment-specific tech shock'};
M_.exo_names(4) = {'e_N'};
M_.exo_names_tex(4) = {'{e_N}'};
M_.exo_names_long(4) = {'Labor supply shock'};
M_.exo_names(5) = {'e_D'};
M_.exo_names_tex(5) = {'{e_D}'};
M_.exo_names_long(5) = {'Shopping disutility shock'};
M_.exo_names(6) = {'e_DI'};
M_.exo_names_tex(6) = {'{e_DI}'};
M_.exo_names_long(6) = {'Relative investment shopping disutility shock'};
M_.exo_names(7) = {'e_b'};
M_.exo_names_tex(7) = {'{e_b}'};
M_.exo_names_long(7) = {'Discount factor shock'};
M_.exo_names(8) = {'e_muC'};
M_.exo_names_tex(8) = {'{e_{muC}}'};
M_.exo_names_long(8) = {'Wage markup shock: C'};
M_.exo_names(9) = {'e_muI'};
M_.exo_names_tex(9) = {'{e_{muI}}'};
M_.exo_names_long(9) = {'Wage markup shock: I'};
M_.endo_names = cell(71,1);
M_.endo_names_tex = cell(71,1);
M_.endo_names_long = cell(71,1);
M_.endo_names(1) = {'Y'};
M_.endo_names_tex(1) = {'{Y}'};
M_.endo_names_long(1) = {'output'};
M_.endo_names(2) = {'C'};
M_.endo_names_tex(2) = {'{C}'};
M_.endo_names_long(2) = {'consumption'};
M_.endo_names(3) = {'I'};
M_.endo_names_tex(3) = {'{I}'};
M_.endo_names_long(3) = {'investment'};
M_.endo_names(4) = {'I_C'};
M_.endo_names_tex(4) = {'{I_C}'};
M_.endo_names_long(4) = {'investment:C'};
M_.endo_names(5) = {'I_I'};
M_.endo_names_tex(5) = {'{I_I}'};
M_.endo_names_long(5) = {'investment:I'};
M_.endo_names(6) = {'K'};
M_.endo_names_tex(6) = {'{K}'};
M_.endo_names_long(6) = {'Capital'};
M_.endo_names(7) = {'K_C'};
M_.endo_names_tex(7) = {'{K_C}'};
M_.endo_names_long(7) = {'Capital:C'};
M_.endo_names(8) = {'K_I'};
M_.endo_names_tex(8) = {'{K_I}'};
M_.endo_names_long(8) = {'Capital:I'};
M_.endo_names(9) = {'N'};
M_.endo_names_tex(9) = {'{N}'};
M_.endo_names_long(9) = {'Hours'};
M_.endo_names(10) = {'N_C'};
M_.endo_names_tex(10) = {'{N_C}'};
M_.endo_names_long(10) = {'Hours:C'};
M_.endo_names(11) = {'N_I'};
M_.endo_names_tex(11) = {'{N_I}'};
M_.endo_names_long(11) = {'Hours:I'};
M_.endo_names(12) = {'N_comp'};
M_.endo_names_tex(12) = {'{N}'};
M_.endo_names_long(12) = {'Labor CES aggregate'};
M_.endo_names(13) = {'Z_C'};
M_.endo_names_tex(13) = {'{Z_C}'};
M_.endo_names_long(13) = {'Tech:C'};
M_.endo_names(14) = {'u_ZI'};
M_.endo_names_tex(14) = {'u\_ZI'};
M_.endo_names_long(14) = {'u_ZI'};
M_.endo_names(15) = {'Z_I'};
M_.endo_names_tex(15) = {'{Z_I}'};
M_.endo_names_long(15) = {'Tech:I'};
M_.endo_names(16) = {'theta_N'};
M_.endo_names_tex(16) = {'{\theta_N}'};
M_.endo_names_long(16) = {'Labor disutility'};
M_.endo_names(17) = {'theta_D'};
M_.endo_names_tex(17) = {'{\theta_D}'};
M_.endo_names_long(17) = {'Shopping disutility'};
M_.endo_names(18) = {'theta_I'};
M_.endo_names_tex(18) = {'{\theta_I}'};
M_.endo_names_long(18) = {'Relative shopping disutility'};
M_.endo_names(19) = {'theta_b'};
M_.endo_names_tex(19) = {'{\theta_b}'};
M_.endo_names_long(19) = {'Discount factor shock'};
M_.endo_names(20) = {'mu_C'};
M_.endo_names_tex(20) = {'{\mu_C}'};
M_.endo_names_long(20) = {'mu_C'};
M_.endo_names(21) = {'mu_I'};
M_.endo_names_tex(21) = {'\mu_I}'};
M_.endo_names_long(21) = {'mu_I'};
M_.endo_names(22) = {'R_C'};
M_.endo_names_tex(22) = {'{R_C}'};
M_.endo_names_long(22) = {'Capital rental rate:C'};
M_.endo_names(23) = {'R_I'};
M_.endo_names_tex(23) = {'{R_I}'};
M_.endo_names_long(23) = {'Capital rental rate:I'};
M_.endo_names(24) = {'W_C'};
M_.endo_names_tex(24) = {'{W_C}'};
M_.endo_names_long(24) = {'Real wage:C'};
M_.endo_names(25) = {'W_I'};
M_.endo_names_tex(25) = {'{W_I}'};
M_.endo_names_long(25) = {'Real wage:C'};
M_.endo_names(26) = {'h_C'};
M_.endo_names_tex(26) = {'{h_C}'};
M_.endo_names_long(26) = {'Capital utilization rate:C'};
M_.endo_names(27) = {'h_I'};
M_.endo_names_tex(27) = {'{h_I}'};
M_.endo_names_long(27) = {'Capital utilization rate:I'};
M_.endo_names(28) = {'delta_C'};
M_.endo_names_tex(28) = {'{\delta_C}'};
M_.endo_names_long(28) = {'Capital depreciation rate:C'};
M_.endo_names(29) = {'delta_I'};
M_.endo_names_tex(29) = {'{\delta_I}'};
M_.endo_names_long(29) = {'Capital depreciation rate:I'};
M_.endo_names(30) = {'delta_C_pr'};
M_.endo_names_tex(30) = {'{\delta_C}'};
M_.endo_names_long(30) = {'Capital depreciation rate derivative:C'};
M_.endo_names(31) = {'delta_I_pr'};
M_.endo_names_tex(31) = {'{\delta_I}'};
M_.endo_names_long(31) = {'Capital depreciation rate derivative:I'};
M_.endo_names(32) = {'Sc'};
M_.endo_names_tex(32) = {'S'};
M_.endo_names_long(32) = {'Investment adjustment cost:C'};
M_.endo_names(33) = {'Si'};
M_.endo_names_tex(33) = {'S'};
M_.endo_names_long(33) = {'Investment adjustment cost:I'};
M_.endo_names(34) = {'Sc_pr'};
M_.endo_names_tex(34) = {'S_pr'};
M_.endo_names_long(34) = {'Derivative investment adjustment cost:C'};
M_.endo_names(35) = {'Si_pr'};
M_.endo_names_tex(35) = {'S_pr'};
M_.endo_names_long(35) = {'Derivative investment adjustment cost:I'};
M_.endo_names(36) = {'D'};
M_.endo_names_tex(36) = {'{D}'};
M_.endo_names_long(36) = {'Shopping effort'};
M_.endo_names(37) = {'D_C'};
M_.endo_names_tex(37) = {'{D}'};
M_.endo_names_long(37) = {'Shopping effort:C'};
M_.endo_names(38) = {'D_I'};
M_.endo_names_tex(38) = {'{D}'};
M_.endo_names_long(38) = {'Shopping effort:I'};
M_.endo_names(39) = {'Gam'};
M_.endo_names_tex(39) = {'{\Gamma}'};
M_.endo_names_long(39) = {'Composite utility term'};
M_.endo_names(40) = {'zeta'};
M_.endo_names_tex(40) = {'{\zeta}'};
M_.endo_names_long(40) = {'Wealth effects parameter'};
M_.endo_names(41) = {'p_I'};
M_.endo_names_tex(41) = {'{p_I}'};
M_.endo_names_long(41) = {'Relative investment price'};
M_.endo_names(42) = {'Q_C'};
M_.endo_names_tex(42) = {'{Q}'};
M_.endo_names_long(42) = {'Relative price of capital:C'};
M_.endo_names(43) = {'Q_I'};
M_.endo_names_tex(43) = {'{Q}'};
M_.endo_names_long(43) = {'Relative price of capital:I'};
M_.endo_names(44) = {'x_C'};
M_.endo_names_tex(44) = {'{x}'};
M_.endo_names_long(44) = {'Growth rate of investment:C'};
M_.endo_names(45) = {'x_I'};
M_.endo_names_tex(45) = {'{x}'};
M_.endo_names_long(45) = {'Growth rate of investment:I'};
M_.endo_names(46) = {'log_SR'};
M_.endo_names_tex(46) = {'log\_SR'};
M_.endo_names_long(46) = {'Solow residual'};
M_.endo_names(47) = {'util'};
M_.endo_names_tex(47) = {'{util}'};
M_.endo_names_long(47) = {'Capacity utilization:'};
M_.endo_names(48) = {'g'};
M_.endo_names_tex(48) = {'{g}'};
M_.endo_names_long(48) = {'Growth rate of stochastic trend'};
M_.endo_names(49) = {'log_Y'};
M_.endo_names_tex(49) = {'log\_Y'};
M_.endo_names_long(49) = {'log_Y'};
M_.endo_names(50) = {'log_C'};
M_.endo_names_tex(50) = {'log\_C'};
M_.endo_names_long(50) = {'log_C'};
M_.endo_names(51) = {'log_I'};
M_.endo_names_tex(51) = {'log\_I'};
M_.endo_names_long(51) = {'log_I'};
M_.endo_names(52) = {'log_N'};
M_.endo_names_tex(52) = {'log\_N'};
M_.endo_names_long(52) = {'log_N'};
M_.endo_names(53) = {'log_NC'};
M_.endo_names_tex(53) = {'log\_NC'};
M_.endo_names_long(53) = {'log_NC'};
M_.endo_names(54) = {'log_NI'};
M_.endo_names_tex(54) = {'log\_NI'};
M_.endo_names_long(54) = {'log_NI'};
M_.endo_names(55) = {'log_K'};
M_.endo_names_tex(55) = {'log\_K'};
M_.endo_names_long(55) = {'log_K'};
M_.endo_names(56) = {'log_Y_N'};
M_.endo_names_tex(56) = {'log\_Y\_N'};
M_.endo_names_long(56) = {'log_Y_N'};
M_.endo_names(57) = {'log_D'};
M_.endo_names_tex(57) = {'log\_D'};
M_.endo_names_long(57) = {'log_D'};
M_.endo_names(58) = {'log_p_I'};
M_.endo_names_tex(58) = {'log\_p\_I'};
M_.endo_names_long(58) = {'log_p_I'};
M_.endo_names(59) = {'log_util'};
M_.endo_names_tex(59) = {'log\_util'};
M_.endo_names_long(59) = {'log_util'};
M_.endo_names(60) = {'C_obs'};
M_.endo_names_tex(60) = {'C\_obs'};
M_.endo_names_long(60) = {'C_obs'};
M_.endo_names(61) = {'I_obs'};
M_.endo_names_tex(61) = {'I\_obs'};
M_.endo_names_long(61) = {'I_obs'};
M_.endo_names(62) = {'Y_obs'};
M_.endo_names_tex(62) = {'Y\_obs'};
M_.endo_names_long(62) = {'Y_obs'};
M_.endo_names(63) = {'Y_N_obs'};
M_.endo_names_tex(63) = {'Y\_N\_obs'};
M_.endo_names_long(63) = {'Y_N_obs'};
M_.endo_names(64) = {'p_I_obs'};
M_.endo_names_tex(64) = {'p\_I\_obs'};
M_.endo_names_long(64) = {'p_I_obs'};
M_.endo_names(65) = {'N_obs'};
M_.endo_names_tex(65) = {'N\_obs'};
M_.endo_names_long(65) = {'N_obs'};
M_.endo_names(66) = {'NC_obs'};
M_.endo_names_tex(66) = {'NC\_obs'};
M_.endo_names_long(66) = {'NC_obs'};
M_.endo_names(67) = {'NI_obs'};
M_.endo_names_tex(67) = {'NI\_obs'};
M_.endo_names_long(67) = {'NI_obs'};
M_.endo_names(68) = {'util_obs'};
M_.endo_names_tex(68) = {'util\_obs'};
M_.endo_names_long(68) = {'util_obs'};
M_.endo_names(69) = {'D_obs'};
M_.endo_names_tex(69) = {'D\_obs'};
M_.endo_names_long(69) = {'D_obs'};
M_.endo_names(70) = {'K_obs'};
M_.endo_names_tex(70) = {'K\_obs'};
M_.endo_names_long(70) = {'K_obs'};
M_.endo_names(71) = {'SR_obs'};
M_.endo_names_tex(71) = {'SR\_obs'};
M_.endo_names_long(71) = {'SR_obs'};
M_.endo_partitions = struct();
M_.param_names = cell(31,1);
M_.param_names_tex = cell(31,1);
M_.param_names_long = cell(31,1);
M_.param_names(1) = {'gam'};
M_.param_names_tex(1) = {'{\gamma}'};
M_.param_names_long(1) = {'Risk aversion'};
M_.param_names(2) = {'gam_max'};
M_.param_names_tex(2) = {'{\gamma_{max}}'};
M_.param_names_long(2) = {'Upper bound on risk aversion'};
M_.param_names(3) = {'beta'};
M_.param_names_tex(3) = {'{\beta}'};
M_.param_names_long(3) = {'Discount factor'};
M_.param_names(4) = {'g_bar'};
M_.param_names_tex(4) = {'{\overline{g}}'};
M_.param_names_long(4) = {'Quarterly trend growth rate'};
M_.param_names(5) = {'nu'};
M_.param_names_tex(5) = {'\nu'};
M_.param_names_long(5) = {'Frisch elasticity'};
M_.param_names(6) = {'sigma_s'};
M_.param_names_tex(6) = {'\sigma_s'};
M_.param_names_long(6) = {'wealth effect on labor supply'};
M_.param_names(7) = {'mu_ss'};
M_.param_names_tex(7) = {'\mu_{ss}'};
M_.param_names_long(7) = {'steady-state wage markup'};
M_.param_names(8) = {'sigma_ac'};
M_.param_names_tex(8) = {'{\sigma_{ac}}'};
M_.param_names_long(8) = {'Inverse elasticity of marginal utilization cost wrt rental rate:C'};
M_.param_names(9) = {'sigma_ai'};
M_.param_names_tex(9) = {'{\sigma_{ai}}'};
M_.param_names_long(9) = {'Inverse elasticity of marginal utilization cost wrt rental rate:I'};
M_.param_names(10) = {'Psi_C'};
M_.param_names_tex(10) = {'{\Psi_C}'};
M_.param_names_long(10) = {'Investment adjustment cost parameter:C'};
M_.param_names(11) = {'Psi_I'};
M_.param_names_tex(11) = {'{\Psi_I}'};
M_.param_names_long(11) = {'Investment adjustment cost parameter:I'};
M_.param_names(12) = {'I_Y'};
M_.param_names_tex(12) = {'{I_Y}'};
M_.param_names_long(12) = {'Investment-output ratio'};
M_.param_names(13) = {'K_Y'};
M_.param_names_tex(13) = {'{K_Y}'};
M_.param_names_long(13) = {'Capital-output ratio (quarterly)'};
M_.param_names(14) = {'labor_share'};
M_.param_names_tex(14) = {'(labor share)'};
M_.param_names_long(14) = {'Labor share'};
M_.param_names(15) = {'nu_R'};
M_.param_names_tex(15) = {'{\nu_R}'};
M_.param_names_long(15) = {'Fixed cost share'};
M_.param_names(16) = {'ha'};
M_.param_names_tex(16) = {'{ha}'};
M_.param_names_long(16) = {'Habit persistence'};
M_.param_names(17) = {'m'};
M_.param_names_tex(17) = {'{m}'};
M_.param_names_long(17) = {'Ratio of price dispersion to consumption dispersion'};
M_.param_names(18) = {'eta'};
M_.param_names_tex(18) = {'{\eta}'};
M_.param_names_long(18) = {'Shopping disutility'};
M_.param_names(19) = {'Psi'};
M_.param_names_tex(19) = {'{\Psi}'};
M_.param_names_long(19) = {'Matching utilization'};
M_.param_names(20) = {'theta'};
M_.param_names_tex(20) = {'{\theta}'};
M_.param_names_long(20) = {'Inverse intersectoral elasticity of labor supply'};
M_.param_names(21) = {'rho_g'};
M_.param_names_tex(21) = {'{\rho_g}'};
M_.param_names_long(21) = {'persistence TFP growth shock'};
M_.param_names(22) = {'rho_Z'};
M_.param_names_tex(22) = {'{\rho_Z}'};
M_.param_names_long(22) = {'persistence TFP shock'};
M_.param_names(23) = {'rho_ZI'};
M_.param_names_tex(23) = {'{\rho_{ZI}}'};
M_.param_names_long(23) = {'persistence I-specific shock'};
M_.param_names(24) = {'rho_N'};
M_.param_names_tex(24) = {'{\rho_N}'};
M_.param_names_long(24) = {'persistence labor supply shock'};
M_.param_names(25) = {'rho_D'};
M_.param_names_tex(25) = {'{\rho_D}'};
M_.param_names_long(25) = {'persistence shopping effort shock'};
M_.param_names(26) = {'rho_DI'};
M_.param_names_tex(26) = {'{\rho_{DI}}'};
M_.param_names_long(26) = {'persistence relative shopping effort shock'};
M_.param_names(27) = {'rho_b'};
M_.param_names_tex(27) = {'{\rho_b}'};
M_.param_names_long(27) = {'persistence discount factor shock'};
M_.param_names(28) = {'rho_muC'};
M_.param_names_tex(28) = {'{\rho_{muC}}'};
M_.param_names_long(28) = {'persistence wage markup shock:C'};
M_.param_names(29) = {'rho_muI'};
M_.param_names_tex(29) = {'{\rho_{muI}}'};
M_.param_names_long(29) = {'persistence wage markup shock:I'};
M_.param_names(30) = {'p_I_ss'};
M_.param_names_tex(30) = {'p\_I\_ss'};
M_.param_names_long(30) = {'p_I_ss'};
M_.param_names(31) = {'N_ss'};
M_.param_names_tex(31) = {'N\_ss'};
M_.param_names_long(31) = {'N_ss'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 9;
M_.endo_nbr = 71;
M_.param_nbr = 31;
M_.orig_endo_nbr = 71;
M_.aux_vars = [];
options_.varobs = cell(5, 1);
options_.varobs(1)  = {'NC_obs'};
options_.varobs(2)  = {'NI_obs'};
options_.varobs(3)  = {'C_obs'};
options_.varobs(4)  = {'I_obs'};
options_.varobs(5)  = {'p_I_obs'};
options_.varobs_id = [ 66 67 60 61 64  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(9, 9);
M_.Correlation_matrix = eye(9, 9);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 71;
M_.eq_nbr = 71;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 28 0;
 1 29 0;
 0 30 0;
 2 31 0;
 3 32 0;
 0 33 0;
 4 34 0;
 5 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 6 40 0;
 0 41 0;
 7 42 0;
 8 43 0;
 9 44 0;
 10 45 0;
 11 46 0;
 12 47 0;
 13 48 0;
 0 49 99;
 0 50 100;
 0 51 0;
 0 52 0;
 0 53 101;
 0 54 102;
 0 55 103;
 0 56 104;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 105;
 0 62 106;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 107;
 14 67 0;
 0 68 0;
 0 69 108;
 0 70 109;
 0 71 110;
 0 72 111;
 0 73 0;
 0 74 0;
 15 75 112;
 16 76 0;
 17 77 0;
 18 78 0;
 19 79 0;
 20 80 0;
 21 81 0;
 22 82 0;
 23 83 0;
 24 84 0;
 25 85 0;
 26 86 0;
 0 87 0;
 0 88 0;
 0 89 0;
 0 90 0;
 0 91 0;
 0 92 0;
 0 93 0;
 0 94 0;
 0 95 0;
 0 96 0;
 27 97 0;
 0 98 0;]';
M_.nstatic = 31;
M_.nfwrd   = 13;
M_.npred   = 26;
M_.nboth   = 1;
M_.nsfwrd   = 14;
M_.nspred   = 27;
M_.ndynamic   = 40;
M_.dynamic_tmp_nbr = [56; 20; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Labor composite' ;
  2 , 'name' , 'Labor leisure:C' ;
  3 , 'name' , 'Labor leisure:I' ;
  4 , 'name' , 'Shopping:C' ;
  5 , 'name' , 'Shopping:I' ;
  6 , 'name' , 'Composite utility term' ;
  7 , 'name' , 'Law of motion of wealth effects variable' ;
  8 , 'name' , 'Investment adjustment cost function:C' ;
  9 , 'name' , 'Investment adjustment cost function:I' ;
  10 , 'name' , 'Investment adjustment cost function: derivative C' ;
  11 , 'name' , 'Investment adjustment cost function: derivative I' ;
  12 , 'name' , 'Investment growth:C' ;
  13 , 'name' , 'Investment growth:I' ;
  14 , 'name' , 'Tobins Q: C' ;
  15 , 'name' , 'Tobins Q: I' ;
  16 , 'name' , 'Euler equation: C' ;
  17 , 'name' , 'Euler equation: I' ;
  18 , 'name' , 'Utilization: C' ;
  19 , 'name' , 'Utilization: I' ;
  20 , 'name' , 'Depreciation rate: C' ;
  21 , 'name' , 'Depreciation rate: I' ;
  22 , 'name' , 'Depreciation rate derivative: C' ;
  23 , 'name' , 'Depreciation rate derivative: I' ;
  24 , 'name' , 'Consumption production' ;
  25 , 'name' , 'Investment production' ;
  26 , 'name' , 'Capital law of motion:C' ;
  27 , 'name' , 'Capital law of motion:I' ;
  28 , 'name' , 'Labor demand:C' ;
  29 , 'name' , 'Labor demand:I' ;
  30 , 'name' , 'Capital demand:C' ;
  31 , 'name' , 'Capital demand:I' ;
  32 , 'name' , 'Labor composition' ;
  33 , 'name' , 'Capital composition' ;
  34 , 'name' , 'Investment composition' ;
  35 , 'name' , 'Shopping composition' ;
  36 , 'name' , 'Output (base-year prices)' ;
  37 , 'name' , 'Capacity utilization' ;
  38 , 'name' , 'stochastic trend process' ;
  39 , 'name' , 'Stationary TFP process' ;
  40 , 'name' , 'Independent component of I-specific tech' ;
  41 , 'name' , 'Investment-specific TFP process' ;
  42 , 'name' , 'Labor supply process' ;
  43 , 'name' , 'Shopping effort process' ;
  44 , 'name' , 'Relative shopping effort process' ;
  45 , 'name' , 'Consumption preference process' ;
  46 , 'name' , 'Wage-markup process: C' ;
  47 , 'name' , 'Wage-markup process: I' ;
  48 , 'name' , 'Definition log output' ;
  49 , 'name' , 'Definition log consumption' ;
  50 , 'name' , 'Definition log investment' ;
  51 , 'name' , 'Definition log hours' ;
  52 , 'name' , 'log_NC' ;
  53 , 'name' , 'log_NI' ;
  54 , 'name' , 'log capital' ;
  55 , 'name' , 'Definition log labor productivity' ;
  56 , 'name' , 'Definition log shopping effort' ;
  57 , 'name' , 'Definition of log relative investment  price' ;
  58 , 'name' , 'Definition of log capacity utilization' ;
  59 , 'name' , 'Definition of log Solow residual' ;
  60 , 'name' , 'C_obs' ;
  61 , 'name' , 'I_obs' ;
  62 , 'name' , 'Y_obs' ;
  63 , 'name' , 'Y_N_obs' ;
  64 , 'name' , 'K_obs' ;
  65 , 'name' , 'SR_obs' ;
  66 , 'name' , 'p_I_obs' ;
  67 , 'name' , 'N_obs' ;
  68 , 'name' , 'NC_obs' ;
  69 , 'name' , 'NI_obs' ;
  70 , 'name' , 'util_obs' ;
  71 , 'name' , 'D_obs' ;
};
M_.mapping.Y.eqidx = [36 37 48 ];
M_.mapping.C.eqidx = [4 6 7 24 28 30 36 37 49 ];
M_.mapping.I.eqidx = [5 25 29 31 34 36 37 50 ];
M_.mapping.I_C.eqidx = [12 26 34 ];
M_.mapping.I_I.eqidx = [13 27 34 ];
M_.mapping.K.eqidx = [33 54 ];
M_.mapping.K_C.eqidx = [24 26 30 33 37 ];
M_.mapping.K_I.eqidx = [25 27 31 33 37 ];
M_.mapping.N.eqidx = [32 51 ];
M_.mapping.N_C.eqidx = [1 2 24 28 32 37 52 ];
M_.mapping.N_I.eqidx = [1 3 25 29 32 37 53 ];
M_.mapping.N_comp.eqidx = [1 2 3 6 ];
M_.mapping.Z_C.eqidx = [24 39 41 ];
M_.mapping.u_ZI.eqidx = [40 41 ];
M_.mapping.Z_I.eqidx = [25 40 41 ];
M_.mapping.theta_N.eqidx = [2 3 6 42 ];
M_.mapping.theta_D.eqidx = [4 5 6 7 43 ];
M_.mapping.theta_I.eqidx = [5 35 44 ];
M_.mapping.theta_b.eqidx = [14 15 16 17 45 ];
M_.mapping.mu_C.eqidx = [2 46 ];
M_.mapping.mu_I.eqidx = [3 47 ];
M_.mapping.R_C.eqidx = [16 18 30 ];
M_.mapping.R_I.eqidx = [17 19 31 ];
M_.mapping.W_C.eqidx = [2 28 ];
M_.mapping.W_I.eqidx = [3 29 ];
M_.mapping.h_C.eqidx = [16 20 22 24 30 37 ];
M_.mapping.h_I.eqidx = [17 21 23 25 31 37 ];
M_.mapping.delta_C.eqidx = [16 20 26 ];
M_.mapping.delta_I.eqidx = [17 21 27 ];
M_.mapping.delta_C_pr.eqidx = [18 22 ];
M_.mapping.delta_I_pr.eqidx = [19 23 ];
M_.mapping.Sc.eqidx = [8 14 26 ];
M_.mapping.Si.eqidx = [9 15 27 ];
M_.mapping.Sc_pr.eqidx = [10 14 ];
M_.mapping.Si_pr.eqidx = [11 15 ];
M_.mapping.D.eqidx = [4 5 6 7 35 56 ];
M_.mapping.D_C.eqidx = [4 24 28 30 35 37 ];
M_.mapping.D_I.eqidx = [5 25 29 31 35 37 ];
M_.mapping.Gam.eqidx = [6 14 15 16 17 ];
M_.mapping.zeta.eqidx = [2 3 6 7 ];
M_.mapping.p_I.eqidx = [5 14 15 29 31 57 ];
M_.mapping.Q_C.eqidx = [14 16 18 ];
M_.mapping.Q_I.eqidx = [15 17 19 ];
M_.mapping.x_C.eqidx = [8 10 12 14 ];
M_.mapping.x_I.eqidx = [9 11 13 15 ];
M_.mapping.log_SR.eqidx = [59 ];
M_.mapping.util.eqidx = [37 58 ];
M_.mapping.g.eqidx = [12 13 14 15 16 17 24 25 26 27 30 31 38 60 61 62 63 64 ];
M_.mapping.log_Y.eqidx = [48 55 59 62 ];
M_.mapping.log_C.eqidx = [49 60 ];
M_.mapping.log_I.eqidx = [50 61 ];
M_.mapping.log_N.eqidx = [51 55 59 67 ];
M_.mapping.log_NC.eqidx = [52 68 ];
M_.mapping.log_NI.eqidx = [53 69 ];
M_.mapping.log_K.eqidx = [54 59 64 ];
M_.mapping.log_Y_N.eqidx = [55 63 ];
M_.mapping.log_D.eqidx = [56 71 ];
M_.mapping.log_p_I.eqidx = [57 66 ];
M_.mapping.log_util.eqidx = [58 70 ];
M_.mapping.C_obs.eqidx = [60 ];
M_.mapping.I_obs.eqidx = [61 ];
M_.mapping.Y_obs.eqidx = [62 65 ];
M_.mapping.Y_N_obs.eqidx = [63 ];
M_.mapping.p_I_obs.eqidx = [66 ];
M_.mapping.N_obs.eqidx = [65 67 ];
M_.mapping.NC_obs.eqidx = [68 ];
M_.mapping.NI_obs.eqidx = [69 ];
M_.mapping.util_obs.eqidx = [70 ];
M_.mapping.D_obs.eqidx = [71 ];
M_.mapping.K_obs.eqidx = [64 65 ];
M_.mapping.SR_obs.eqidx = [65 ];
M_.mapping.e_g.eqidx = [38 ];
M_.mapping.e_Z.eqidx = [39 ];
M_.mapping.e_ZI.eqidx = [40 ];
M_.mapping.e_N.eqidx = [42 ];
M_.mapping.e_D.eqidx = [43 ];
M_.mapping.e_DI.eqidx = [44 ];
M_.mapping.e_b.eqidx = [45 ];
M_.mapping.e_muC.eqidx = [46 ];
M_.mapping.e_muI.eqidx = [47 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [2 4 5 7 8 13 15 16 17 18 19 20 21 40 48 49 50 51 52 53 54 55 56 57 58 59 70 ];
M_.exo_names_orig_ord = [1:9];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(71, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(9, 1);
M_.params = NaN(31, 1);
M_.endo_trends = struct('deflator', cell(71, 1), 'log_deflator', cell(71, 1), 'growth_factor', cell(71, 1), 'log_growth_factor', cell(71, 1));
M_.NNZDerivatives = [286; -1; -1; ];
M_.static_tmp_nbr = [54; 17; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 2.0;
gam = M_.params(1);
M_.params(3) = 0.99;
beta = M_.params(3);
M_.params(4) = 0.0045;
g_bar = M_.params(4);
M_.params(5) = 0.72;
nu = M_.params(5);
M_.params(6) = 0.5;
sigma_s = M_.params(6);
M_.params(16) = 0.1;
ha = M_.params(16);
M_.params(7) = 1.15;
mu_ss = M_.params(7);
M_.params(8) = 0.32;
sigma_ac = M_.params(8);
M_.params(9) = 0.32;
sigma_ai = M_.params(9);
M_.params(10) = 1.5;
Psi_C = M_.params(10);
M_.params(11) = 1.5;
Psi_I = M_.params(11);
M_.params(12) = 0.20;
I_Y = M_.params(12);
M_.params(13) = 11;
K_Y = M_.params(13);
M_.params(14) = 0.67;
labor_share = M_.params(14);
M_.params(15) = 0.2;
nu_R = M_.params(15);
M_.params(17) = 0.286;
m = M_.params(17);
M_.params(18) = 0.20;
eta = M_.params(18);
M_.params(19) = 0.81;
Psi = M_.params(19);
M_.params(20) = 0.5;
theta = M_.params(20);
M_.params(30) = 1.0;
p_I_ss = M_.params(30);
M_.params(31) = 0.30;
N_ss = M_.params(31);
M_.params(21) = 0.1;
rho_g = M_.params(21);
M_.params(22) = 0.9;
rho_Z = M_.params(22);
M_.params(23) = 0.9;
rho_ZI = M_.params(23);
M_.params(24) = 0.9;
rho_N = M_.params(24);
M_.params(25) = 0.9;
rho_D = M_.params(25);
M_.params(26) = 0.9;
rho_DI = M_.params(26);
M_.params(27) = 0.9;
rho_b = M_.params(27);
M_.params(28) = 0.9;
rho_muC = M_.params(28);
M_.params(29) = 0.9;
rho_muI = M_.params(29);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 5.184e-05;
M_.Sigma_e(2, 2) = 5.184e-05;
M_.Sigma_e(3, 3) = 5.184e-05;
M_.Sigma_e(4, 4) = 5.184e-05;
M_.Sigma_e(5, 5) = 5.184e-05;
M_.Sigma_e(6, 6) = 5.184e-05;
M_.Sigma_e(7, 7) = 5.184e-05;
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 1, 1.5, 1.0, 4.0, 1, 1.5, 0.25, 1.0, 4.0, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.5, 0.0, 0.95, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, 0.72, 0.05, 2.0, 2, 0.72, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, 0.5, 0.0, 1.0, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.286, 0.0, 0.95, 2, 0.286, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.20, 0.01, 0.5, 1, 0.2, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, 0.32, 0.0, 10, 4, 1, 1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, 0.32, 0.0, 10, 4, 1, 1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, 1.5, 0.0, 50, 2, 4, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, 1.5, 0.0, 50, 2, 4, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.20, 0.00, 10.0, 2, 0.2, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.5, .00, 10, 2, 1, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.1, 0.0001, 0.9, 1, 0.1, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 0.95, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.95, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, 0.6, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, 0.9, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, 0.9, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, 0.95, 0.01, 0.99999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, 0.95, 0.01, 0.99999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 29, 0.95, 0.01, 0.99999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.01, 0.00001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.01, 0.00001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.01, 0.0001, 0.4, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.01, 0.0001, 0.4, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
options_.TeX=1;
options_.TeX = true;
options_.lik_init = 2;
options_.mh_drop = 0.3;
options_.mh_init_scale = 0.0001;
options_.mh_jscale = 0.002;
options_.mh_nblck = 2;
options_.mh_replic = 150000;
options_.mode_check.status = true;
options_.mode_compute = 4;
options_.presample = 0;
options_.prior_trunc = 0;
options_.MCMC_jumping_covariance = 'prior_variance';
options_.datafile = 'observables_sectoral';
options_.optim_opt = '''MaxIter'',200';
options_.order = 1;
var_list_ = {'Y_obs';'Y_N_obs';'I_obs';'p_I_obs';'C_obs';'NC_obs';'NI_obs';'util_obs'};
oo_recursive_=dynare_estimation(var_list_);
write_latex_parameter_table;
write_latex_definitions;
write_latex_prior_table;
collect_latex_files;
options_.irf = 100;
options_.nofunctions = true;
options_.order = 1;
options_.periods = 0;
options_.conditional_variance_decomposition = [1;4;8;40;];
var_list_ = {'Y_obs';'Y_N_obs';'SR_obs';'I_obs';'p_I_obs';'C_obs';'NC_obs';'NI_obs';'util_obs';'D_obs';'log_Y';'log_Y_N';'log_SR';'log_I';'log_p_I';'log_C';'log_N';'log_NC';'log_NI';'log_util';'log_D'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'BRS_sectoral_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
