%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'BRS';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(4,1);
M_.exo_names_tex = cell(4,1);
M_.exo_names_long = cell(4,1);
M_.exo_names(1) = {'e_Z'};
M_.exo_names_tex(1) = {'{e_Z}'};
M_.exo_names_long(1) = {'TFP shock'};
M_.exo_names(2) = {'e_ZI'};
M_.exo_names_tex(2) = {'{e_ZI}'};
M_.exo_names_long(2) = {'Investment-specific tech shock'};
M_.exo_names(3) = {'e_N'};
M_.exo_names_tex(3) = {'{e_N}'};
M_.exo_names_long(3) = {'Labor supply shock'};
M_.exo_names(4) = {'e_D'};
M_.exo_names_tex(4) = {'{e_D}'};
M_.exo_names_long(4) = {'Shopping disutility shock'};
M_.endo_names = cell(33,1);
M_.endo_names_tex = cell(33,1);
M_.endo_names_long = cell(33,1);
M_.endo_names(1) = {'Y'};
M_.endo_names_tex(1) = {'{Y}'};
M_.endo_names_long(1) = {'output'};
M_.endo_names(2) = {'C'};
M_.endo_names_tex(2) = {'{C}'};
M_.endo_names_long(2) = {'consumption'};
M_.endo_names(3) = {'I'};
M_.endo_names_tex(3) = {'{I}'};
M_.endo_names_long(3) = {'investment'};
M_.endo_names(4) = {'K'};
M_.endo_names_tex(4) = {'{K}'};
M_.endo_names_long(4) = {'Capital'};
M_.endo_names(5) = {'K_C'};
M_.endo_names_tex(5) = {'{K_C}'};
M_.endo_names_long(5) = {'Capital:C'};
M_.endo_names(6) = {'K_I'};
M_.endo_names_tex(6) = {'{K_I}'};
M_.endo_names_long(6) = {'Capital:I'};
M_.endo_names(7) = {'N'};
M_.endo_names_tex(7) = {'{N}'};
M_.endo_names_long(7) = {'Hours'};
M_.endo_names(8) = {'N_C'};
M_.endo_names_tex(8) = {'{N_C}'};
M_.endo_names_long(8) = {'Hours:C'};
M_.endo_names(9) = {'N_I'};
M_.endo_names_tex(9) = {'{N_I}'};
M_.endo_names_long(9) = {'Hours:I'};
M_.endo_names(10) = {'Z_C'};
M_.endo_names_tex(10) = {'{Z_C}'};
M_.endo_names_long(10) = {'Tech:C'};
M_.endo_names(11) = {'u_ZI'};
M_.endo_names_tex(11) = {'u\_ZI'};
M_.endo_names_long(11) = {'u_ZI'};
M_.endo_names(12) = {'Z_I'};
M_.endo_names_tex(12) = {'{Z_I}'};
M_.endo_names_long(12) = {'Tech:I'};
M_.endo_names(13) = {'theta_N'};
M_.endo_names_tex(13) = {'{\theta_N}'};
M_.endo_names_long(13) = {'Labor disutility'};
M_.endo_names(14) = {'theta_D'};
M_.endo_names_tex(14) = {'{\theta_D}'};
M_.endo_names_long(14) = {'Shopping disutility'};
M_.endo_names(15) = {'R_C'};
M_.endo_names_tex(15) = {'{R_C}'};
M_.endo_names_long(15) = {'Capital rental rate:C'};
M_.endo_names(16) = {'R_I'};
M_.endo_names_tex(16) = {'{R_I}'};
M_.endo_names_long(16) = {'Capital rental rate:I'};
M_.endo_names(17) = {'W'};
M_.endo_names_tex(17) = {'{W}'};
M_.endo_names_long(17) = {'Real wage'};
M_.endo_names(18) = {'D'};
M_.endo_names_tex(18) = {'{D}'};
M_.endo_names_long(18) = {'Shopping effort'};
M_.endo_names(19) = {'D_C'};
M_.endo_names_tex(19) = {'{D}'};
M_.endo_names_long(19) = {'Shopping effort:C'};
M_.endo_names(20) = {'D_I'};
M_.endo_names_tex(20) = {'{D}'};
M_.endo_names_long(20) = {'Shopping effort:I'};
M_.endo_names(21) = {'Gam'};
M_.endo_names_tex(21) = {'{\Gamma}'};
M_.endo_names_long(21) = {'Composite utility term'};
M_.endo_names(22) = {'p_I'};
M_.endo_names_tex(22) = {'{p_I}'};
M_.endo_names_long(22) = {'Relative investment price'};
M_.endo_names(23) = {'log_Y'};
M_.endo_names_tex(23) = {'log\_Y'};
M_.endo_names_long(23) = {'log_Y'};
M_.endo_names(24) = {'log_C'};
M_.endo_names_tex(24) = {'log\_C'};
M_.endo_names_long(24) = {'log_C'};
M_.endo_names(25) = {'log_I'};
M_.endo_names_tex(25) = {'log\_I'};
M_.endo_names_long(25) = {'log_I'};
M_.endo_names(26) = {'log_N'};
M_.endo_names_tex(26) = {'log\_N'};
M_.endo_names_long(26) = {'log_N'};
M_.endo_names(27) = {'log_Y_N'};
M_.endo_names_tex(27) = {'log\_Y\_N'};
M_.endo_names_long(27) = {'log_Y_N'};
M_.endo_names(28) = {'log_D'};
M_.endo_names_tex(28) = {'log\_D'};
M_.endo_names_long(28) = {'log_D'};
M_.endo_names(29) = {'C_obs'};
M_.endo_names_tex(29) = {'C\_obs'};
M_.endo_names_long(29) = {'C_obs'};
M_.endo_names(30) = {'I_obs'};
M_.endo_names_tex(30) = {'I\_obs'};
M_.endo_names_long(30) = {'I_obs'};
M_.endo_names(31) = {'Y_obs'};
M_.endo_names_tex(31) = {'Y\_obs'};
M_.endo_names_long(31) = {'Y_obs'};
M_.endo_names(32) = {'lab_prod_obs'};
M_.endo_names_tex(32) = {'lab\_prod\_obs'};
M_.endo_names_long(32) = {'lab_prod_obs'};
M_.endo_names(33) = {'p_I_obs'};
M_.endo_names_tex(33) = {'p\_I\_obs'};
M_.endo_names_long(33) = {'p_I_obs'};
M_.endo_partitions = struct();
M_.param_names = cell(16,1);
M_.param_names_tex = cell(16,1);
M_.param_names_long = cell(16,1);
M_.param_names(1) = {'gam'};
M_.param_names_tex(1) = {'{\gamma}'};
M_.param_names_long(1) = {'Risk aversion'};
M_.param_names(2) = {'r_ann'};
M_.param_names_tex(2) = {'{r_ann}'};
M_.param_names_long(2) = {'Annual interest rate'};
M_.param_names(3) = {'g_bar'};
M_.param_names_tex(3) = {'{\overline{g}}'};
M_.param_names_long(3) = {'Quarterly growth rate'};
M_.param_names(4) = {'nu'};
M_.param_names_tex(4) = {'(\nu)'};
M_.param_names_long(4) = {'Frisch elasticity'};
M_.param_names(5) = {'I_Y'};
M_.param_names_tex(5) = {'(I_Y)'};
M_.param_names_long(5) = {'Investment-output ratio'};
M_.param_names(6) = {'K_Y'};
M_.param_names_tex(6) = {'(K_Y)'};
M_.param_names_long(6) = {'Capital-output ratio (quarterly)'};
M_.param_names(7) = {'labor_share'};
M_.param_names_tex(7) = {'(labor share)'};
M_.param_names_long(7) = {'Labor share'};
M_.param_names(8) = {'phi'};
M_.param_names_tex(8) = {'(\phi)'};
M_.param_names_long(8) = {'Shopping matching function elasticity'};
M_.param_names(9) = {'eta'};
M_.param_names_tex(9) = {'(\eta)'};
M_.param_names_long(9) = {'Shopping disutility'};
M_.param_names(10) = {'Psi'};
M_.param_names_tex(10) = {'(\Psi)'};
M_.param_names_long(10) = {'Matching utilization'};
M_.param_names(11) = {'rho_Z'};
M_.param_names_tex(11) = {'{\rho_Z}'};
M_.param_names_long(11) = {'persistence TFP shock'};
M_.param_names(12) = {'rho_ZI'};
M_.param_names_tex(12) = {'{\rho_ZI}'};
M_.param_names_long(12) = {'persistence I-specific shock'};
M_.param_names(13) = {'rho_N'};
M_.param_names_tex(13) = {'{\rho_N}'};
M_.param_names_long(13) = {'persistence labor supply shock'};
M_.param_names(14) = {'rho_D'};
M_.param_names_tex(14) = {'{\rho_D}'};
M_.param_names_long(14) = {'persistence shopping effort shock'};
M_.param_names(15) = {'p_I_ss'};
M_.param_names_tex(15) = {'p\_I\_ss'};
M_.param_names_long(15) = {'p_I_ss'};
M_.param_names(16) = {'N_ss'};
M_.param_names_tex(16) = {'N\_ss'};
M_.param_names_long(16) = {'N_ss'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 33;
M_.param_nbr = 16;
M_.orig_endo_nbr = 33;
M_.aux_vars = [];
options_.varobs = cell(4, 1);
options_.varobs(1)  = {'I_obs'};
options_.varobs(2)  = {'Y_obs'};
options_.varobs(3)  = {'lab_prod_obs'};
options_.varobs(4)  = {'p_I_obs'};
options_.varobs_id = [ 30 31 32 33  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [1 2 3 4 5 7 8 10 11 12 13 23 24 25 26 28 33];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 33;
M_.eq_nbr = 33;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 7 0;
 0 8 0;
 0 9 0;
 0 10 0;
 1 11 0;
 2 12 0;
 0 13 0;
 0 14 0;
 0 15 0;
 3 16 0;
 0 17 0;
 4 18 0;
 5 19 0;
 6 20 0;
 0 21 40;
 0 22 41;
 0 23 0;
 0 24 0;
 0 25 0;
 0 26 0;
 0 27 42;
 0 28 43;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;]';
M_.nstatic = 23;
M_.nfwrd   = 4;
M_.npred   = 6;
M_.nboth   = 0;
M_.nsfwrd   = 4;
M_.nspred   = 6;
M_.ndynamic   = 10;
M_.dynamic_tmp_nbr = [28; 14; 1; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Labor leisure' ;
  2 , 'name' , 'Shopping:C' ;
  3 , 'name' , 'Shopping:I' ;
  4 , 'name' , 'Composite utility term' ;
  5 , 'name' , 'Euler equation: C' ;
  6 , 'name' , 'Euler equation: I' ;
  7 , 'name' , 'Consumption production' ;
  8 , 'name' , 'Investment production' ;
  9 , 'name' , 'Capital law of motion' ;
  10 , 'name' , 'Labor demand:C' ;
  11 , 'name' , 'Capital demand:C' ;
  12 , 'name' , 'Labor demand:I' ;
  13 , 'name' , 'Capital demand:I' ;
  14 , 'name' , 'Labor composition' ;
  15 , 'name' , 'Capital composition' ;
  16 , 'name' , 'Shopping composition' ;
  17 , 'name' , 'Output (base-year prices)' ;
  18 , 'name' , 'exogenous TFP process' ;
  19 , 'name' , 'u_ZI' ;
  20 , 'name' , 'investment-specific TFP process' ;
  21 , 'name' , 'Labor supply process' ;
  22 , 'name' , 'Shopping effort process' ;
  23 , 'name' , 'Definition log output' ;
  24 , 'name' , 'Definition log consumption' ;
  25 , 'name' , 'Definition log investment' ;
  26 , 'name' , 'Definition log hours' ;
  27 , 'name' , 'Definition log labor productivity' ;
  28 , 'name' , 'Definition log shopping effort' ;
  29 , 'name' , 'C_obs' ;
  30 , 'name' , 'I_obs' ;
  31 , 'name' , 'Y_obs' ;
  32 , 'name' , 'lab_prod_obs' ;
  33 , 'name' , 'p_I_obs' ;
};
M_.mapping.Y.eqidx = [17 23 ];
M_.mapping.C.eqidx = [2 4 7 10 17 24 ];
M_.mapping.I.eqidx = [3 8 9 12 17 25 ];
M_.mapping.K.eqidx = [15 ];
M_.mapping.K_C.eqidx = [7 9 11 15 ];
M_.mapping.K_I.eqidx = [8 9 13 15 ];
M_.mapping.N.eqidx = [1 4 14 26 ];
M_.mapping.N_C.eqidx = [7 10 11 14 ];
M_.mapping.N_I.eqidx = [8 12 13 14 ];
M_.mapping.Z_C.eqidx = [7 18 20 ];
M_.mapping.u_ZI.eqidx = [19 20 ];
M_.mapping.Z_I.eqidx = [8 19 20 ];
M_.mapping.theta_N.eqidx = [1 4 21 ];
M_.mapping.theta_D.eqidx = [2 3 4 22 ];
M_.mapping.R_C.eqidx = [5 6 11 ];
M_.mapping.R_I.eqidx = [6 13 ];
M_.mapping.W.eqidx = [1 10 11 12 13 ];
M_.mapping.D.eqidx = [2 3 4 16 28 ];
M_.mapping.D_C.eqidx = [2 7 16 ];
M_.mapping.D_I.eqidx = [3 8 16 ];
M_.mapping.Gam.eqidx = [4 5 ];
M_.mapping.p_I.eqidx = [3 5 12 33 ];
M_.mapping.log_Y.eqidx = [23 27 31 ];
M_.mapping.log_C.eqidx = [24 29 ];
M_.mapping.log_I.eqidx = [25 30 ];
M_.mapping.log_N.eqidx = [26 27 ];
M_.mapping.log_Y_N.eqidx = [27 32 ];
M_.mapping.log_D.eqidx = [28 ];
M_.mapping.C_obs.eqidx = [29 ];
M_.mapping.I_obs.eqidx = [30 ];
M_.mapping.Y_obs.eqidx = [31 ];
M_.mapping.lab_prod_obs.eqidx = [32 ];
M_.mapping.p_I_obs.eqidx = [33 ];
M_.mapping.e_Z.eqidx = [18 ];
M_.mapping.e_ZI.eqidx = [19 ];
M_.mapping.e_N.eqidx = [21 ];
M_.mapping.e_D.eqidx = [22 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [5 6 10 12 13 14 ];
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(33, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(16, 1);
M_.endo_trends = struct('deflator', cell(33, 1), 'log_deflator', cell(33, 1), 'growth_factor', cell(33, 1), 'log_growth_factor', cell(33, 1));
M_.NNZDerivatives = [105; 97; -1; ];
M_.static_tmp_nbr = [27; 13; 2; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 1.0;
gam = M_.params(1);
M_.params(2) = 0.04;
r_ann = M_.params(2);
M_.params(3) = 0.0;
g_bar = M_.params(3);
M_.params(4) = 0.72;
nu = M_.params(4);
M_.params(5) = 0.20;
I_Y = M_.params(5);
M_.params(6) = 11;
K_Y = M_.params(6);
M_.params(7) = 0.67;
labor_share = M_.params(7);
M_.params(8) = 0.32;
phi = M_.params(8);
M_.params(9) = 0.20;
eta = M_.params(9);
M_.params(10) = 0.81;
Psi = M_.params(10);
M_.params(15) = 1.0;
p_I_ss = M_.params(15);
M_.params(16) = 0.30;
N_ss = M_.params(16);
M_.params(11) = 0.9;
rho_Z = M_.params(11);
M_.params(12) = 0.9;
rho_ZI = M_.params(12);
M_.params(13) = 0.9;
rho_N = M_.params(13);
M_.params(14) = 0.9;
rho_D = M_.params(14);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 5.184e-05;
M_.Sigma_e(2, 2) = 5.184e-05;
M_.Sigma_e(3, 3) = 5.184e-05;
M_.Sigma_e(4, 4) = 5.184e-05;
options_ident = struct();
options_ident.ar = 10;
dynare_identification(options_ident);
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 11, 0.6, 0.01, 0.99999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 0.6, 0.01, 0.99999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 0.6, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 0.6, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
options_.TeX=1;
options_.TeX = true;
options_.bayesian_irf = true;
options_.lik_init = 1;
options_.load_mh_file = true;
options_.mh_drop = 0.3;
options_.mh_jscale = 0.3;
options_.mh_nblck = 2;
options_.mh_replic = 0;
options_.mode_check.status = true;
options_.mode_compute = 0;
options_.moments_varendo = true;
options_.presample = 0;
options_.prior_trunc = 0;
options_.datafile = 'observables';
options_.mode_file = 'BRS_mode';
options_.optim_opt = '''MaxIter'',200';
options_.order = 1;
var_list_ = {'I_obs';'C_obs';'Y_obs';'lab_prod_obs';'p_I_obs';'log_D';'log_N'};
oo_recursive_=dynare_estimation(var_list_);
write_latex_parameter_table;
write_latex_definitions;
write_latex_prior_table;
generate_trace_plots(1);
collect_latex_files;
options_.irf = 100;
options_.nofunctions = true;
options_.order = 1;
options_.periods = 0;
options_.conditional_variance_decomposition = [1;4;8;40;];
var_list_ = {'I_obs';'C_obs';'Y_obs';'lab_prod_obs';'p_I_obs';'log_D';'log_N'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'BRS_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
