%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'RBC_sectoral';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(13,1);
M_.exo_names_tex = cell(13,1);
M_.exo_names_long = cell(13,1);
M_.exo_names(1) = {'e_g'};
M_.exo_names_tex(1) = {'{e_g}'};
M_.exo_names_long(1) = {'Labor-augmenting-technology growth shock'};
M_.exo_names(2) = {'e_g_news'};
M_.exo_names_tex(2) = {'{e_{g,-4}}'};
M_.exo_names_long(2) = {'Labor-augmenting-technology growth shock: news'};
M_.exo_names(3) = {'e_Z'};
M_.exo_names_tex(3) = {'{e_Z}'};
M_.exo_names_long(3) = {'TFP shock'};
M_.exo_names(4) = {'e_Z_news'};
M_.exo_names_tex(4) = {'{e_{Z,-4}}'};
M_.exo_names_long(4) = {'TFP shock: news'};
M_.exo_names(5) = {'e_ZI'};
M_.exo_names_tex(5) = {'{e_{ZI}}'};
M_.exo_names_long(5) = {'Investment-specific tech shock'};
M_.exo_names(6) = {'e_ZI_news'};
M_.exo_names_tex(6) = {'{e_{ZI,-4}}'};
M_.exo_names_long(6) = {'Investment-specific tech shock: news'};
M_.exo_names(7) = {'e_N'};
M_.exo_names_tex(7) = {'{e_N}'};
M_.exo_names_long(7) = {'Labor supply shock'};
M_.exo_names(8) = {'e_b'};
M_.exo_names_tex(8) = {'{e_b}'};
M_.exo_names_long(8) = {'Discount factor shock'};
M_.exo_names(9) = {'e_b_news'};
M_.exo_names_tex(9) = {'{e_{b,-4}}'};
M_.exo_names_long(9) = {'Discount factor shock'};
M_.exo_names(10) = {'e_muC'};
M_.exo_names_tex(10) = {'{e_{muC}}'};
M_.exo_names_long(10) = {'Wage markup shock: C'};
M_.exo_names(11) = {'e_muC_news'};
M_.exo_names_tex(11) = {'{e_{muC,-4}}'};
M_.exo_names_long(11) = {'Wage markup shock: C: news'};
M_.exo_names(12) = {'e_muI'};
M_.exo_names_tex(12) = {'{e_{muI}}'};
M_.exo_names_long(12) = {'Wage markup shock: I'};
M_.exo_names(13) = {'e_muI_news'};
M_.exo_names_tex(13) = {'{e_{muI,-4}}'};
M_.exo_names_long(13) = {'Wage markup shock: I: news'};
M_.endo_names = cell(97,1);
M_.endo_names_tex = cell(97,1);
M_.endo_names_long = cell(97,1);
M_.endo_names(1) = {'Y'};
M_.endo_names_tex(1) = {'{Y}'};
M_.endo_names_long(1) = {'output'};
M_.endo_names(2) = {'C'};
M_.endo_names_tex(2) = {'{C}'};
M_.endo_names_long(2) = {'consumption'};
M_.endo_names(3) = {'I'};
M_.endo_names_tex(3) = {'{I}'};
M_.endo_names_long(3) = {'investment'};
M_.endo_names(4) = {'I_C'};
M_.endo_names_tex(4) = {'{I_C}'};
M_.endo_names_long(4) = {'investment:C'};
M_.endo_names(5) = {'I_I'};
M_.endo_names_tex(5) = {'{I_I}'};
M_.endo_names_long(5) = {'investment:I'};
M_.endo_names(6) = {'K'};
M_.endo_names_tex(6) = {'{K}'};
M_.endo_names_long(6) = {'Capital'};
M_.endo_names(7) = {'K_C'};
M_.endo_names_tex(7) = {'{K_C}'};
M_.endo_names_long(7) = {'Capital:C'};
M_.endo_names(8) = {'K_I'};
M_.endo_names_tex(8) = {'{K_I}'};
M_.endo_names_long(8) = {'Capital:I'};
M_.endo_names(9) = {'N'};
M_.endo_names_tex(9) = {'{N}'};
M_.endo_names_long(9) = {'Hours'};
M_.endo_names(10) = {'N_C'};
M_.endo_names_tex(10) = {'{N_C}'};
M_.endo_names_long(10) = {'Hours:C'};
M_.endo_names(11) = {'N_I'};
M_.endo_names_tex(11) = {'{N_I}'};
M_.endo_names_long(11) = {'Hours:I'};
M_.endo_names(12) = {'N_comp'};
M_.endo_names_tex(12) = {'{N}'};
M_.endo_names_long(12) = {'Labor CES aggregate'};
M_.endo_names(13) = {'Z_C'};
M_.endo_names_tex(13) = {'{Z_C}'};
M_.endo_names_long(13) = {'Tech:C'};
M_.endo_names(14) = {'u_ZI'};
M_.endo_names_tex(14) = {'u\_ZI'};
M_.endo_names_long(14) = {'u_ZI'};
M_.endo_names(15) = {'Z_I'};
M_.endo_names_tex(15) = {'{Z_I}'};
M_.endo_names_long(15) = {'Tech:I'};
M_.endo_names(16) = {'theta_N'};
M_.endo_names_tex(16) = {'{\theta_N}'};
M_.endo_names_long(16) = {'Labor disutility'};
M_.endo_names(17) = {'theta_b'};
M_.endo_names_tex(17) = {'{\theta_b}'};
M_.endo_names_long(17) = {'Discount factor shock'};
M_.endo_names(18) = {'mu_C'};
M_.endo_names_tex(18) = {'{\mu_C}'};
M_.endo_names_long(18) = {'mu_C'};
M_.endo_names(19) = {'mu_I'};
M_.endo_names_tex(19) = {'\mu_I}'};
M_.endo_names_long(19) = {'mu_I'};
M_.endo_names(20) = {'R_C'};
M_.endo_names_tex(20) = {'{R_C}'};
M_.endo_names_long(20) = {'Capital rental rate:C'};
M_.endo_names(21) = {'R_I'};
M_.endo_names_tex(21) = {'{R_I}'};
M_.endo_names_long(21) = {'Capital rental rate:I'};
M_.endo_names(22) = {'W_C'};
M_.endo_names_tex(22) = {'{W_C}'};
M_.endo_names_long(22) = {'Real wage:C'};
M_.endo_names(23) = {'W_I'};
M_.endo_names_tex(23) = {'{W_I}'};
M_.endo_names_long(23) = {'Real wage:C'};
M_.endo_names(24) = {'W'};
M_.endo_names_tex(24) = {'{W}'};
M_.endo_names_long(24) = {'Real wage'};
M_.endo_names(25) = {'h_C'};
M_.endo_names_tex(25) = {'{h_C}'};
M_.endo_names_long(25) = {'Capital utilization rate:C'};
M_.endo_names(26) = {'h_I'};
M_.endo_names_tex(26) = {'{h_I}'};
M_.endo_names_long(26) = {'Capital utilization rate:I'};
M_.endo_names(27) = {'delta_C'};
M_.endo_names_tex(27) = {'{\delta_C}'};
M_.endo_names_long(27) = {'Capital depreciation rate:C'};
M_.endo_names(28) = {'delta_I'};
M_.endo_names_tex(28) = {'{\delta_I}'};
M_.endo_names_long(28) = {'Capital depreciation rate:I'};
M_.endo_names(29) = {'delta_C_pr'};
M_.endo_names_tex(29) = {'{\delta_C}'};
M_.endo_names_long(29) = {'Capital depreciation rate derivative:C'};
M_.endo_names(30) = {'delta_I_pr'};
M_.endo_names_tex(30) = {'{\delta_I}'};
M_.endo_names_long(30) = {'Capital depreciation rate derivative:I'};
M_.endo_names(31) = {'Sc'};
M_.endo_names_tex(31) = {'S'};
M_.endo_names_long(31) = {'Investment adjustment cost:C'};
M_.endo_names(32) = {'Si'};
M_.endo_names_tex(32) = {'S'};
M_.endo_names_long(32) = {'Investment adjustment cost:I'};
M_.endo_names(33) = {'Sc_pr'};
M_.endo_names_tex(33) = {'S_pr'};
M_.endo_names_long(33) = {'Derivative investment adjustment cost:C'};
M_.endo_names(34) = {'Si_pr'};
M_.endo_names_tex(34) = {'S_pr'};
M_.endo_names_long(34) = {'Derivative investment adjustment cost:I'};
M_.endo_names(35) = {'Gam'};
M_.endo_names_tex(35) = {'{\Gamma}'};
M_.endo_names_long(35) = {'Composite utility term'};
M_.endo_names(36) = {'zeta'};
M_.endo_names_tex(36) = {'{\zeta}'};
M_.endo_names_long(36) = {'Wealth effects parameter'};
M_.endo_names(37) = {'p_I'};
M_.endo_names_tex(37) = {'{p_I}'};
M_.endo_names_long(37) = {'Relative investment price'};
M_.endo_names(38) = {'Q_C'};
M_.endo_names_tex(38) = {'{Q}'};
M_.endo_names_long(38) = {'Relative price of capital:C'};
M_.endo_names(39) = {'Q_I'};
M_.endo_names_tex(39) = {'{Q}'};
M_.endo_names_long(39) = {'Relative price of capital:I'};
M_.endo_names(40) = {'x_C'};
M_.endo_names_tex(40) = {'{x}'};
M_.endo_names_long(40) = {'Growth rate of investment:C'};
M_.endo_names(41) = {'x_I'};
M_.endo_names_tex(41) = {'{x}'};
M_.endo_names_long(41) = {'Growth rate of investment:I'};
M_.endo_names(42) = {'log_SR'};
M_.endo_names_tex(42) = {'log\_SR'};
M_.endo_names_long(42) = {'Solow residual'};
M_.endo_names(43) = {'util'};
M_.endo_names_tex(43) = {'{util}'};
M_.endo_names_long(43) = {'Capacity utilization'};
M_.endo_names(44) = {'util_ND'};
M_.endo_names_tex(44) = {'{util_{ND}}'};
M_.endo_names_long(44) = {'Capacity utilization:ND'};
M_.endo_names(45) = {'util_D'};
M_.endo_names_tex(45) = {'{util_D}'};
M_.endo_names_long(45) = {'Capacity utilization:D'};
M_.endo_names(46) = {'g'};
M_.endo_names_tex(46) = {'{g}'};
M_.endo_names_long(46) = {'Growth rate of stochastic trend'};
M_.endo_names(47) = {'log_Y'};
M_.endo_names_tex(47) = {'log\_Y'};
M_.endo_names_long(47) = {'log_Y'};
M_.endo_names(48) = {'log_C'};
M_.endo_names_tex(48) = {'log\_C'};
M_.endo_names_long(48) = {'log_C'};
M_.endo_names(49) = {'log_I'};
M_.endo_names_tex(49) = {'log\_I'};
M_.endo_names_long(49) = {'log_I'};
M_.endo_names(50) = {'log_N'};
M_.endo_names_tex(50) = {'log\_N'};
M_.endo_names_long(50) = {'log_N'};
M_.endo_names(51) = {'log_NC'};
M_.endo_names_tex(51) = {'log\_NC'};
M_.endo_names_long(51) = {'log_NC'};
M_.endo_names(52) = {'log_NI'};
M_.endo_names_tex(52) = {'log\_NI'};
M_.endo_names_long(52) = {'log_NI'};
M_.endo_names(53) = {'log_K'};
M_.endo_names_tex(53) = {'log\_K'};
M_.endo_names_long(53) = {'log_K'};
M_.endo_names(54) = {'log_Y_N'};
M_.endo_names_tex(54) = {'log\_Y\_N'};
M_.endo_names_long(54) = {'log_Y_N'};
M_.endo_names(55) = {'log_p_I'};
M_.endo_names_tex(55) = {'log\_p\_I'};
M_.endo_names_long(55) = {'log_p_I'};
M_.endo_names(56) = {'log_util'};
M_.endo_names_tex(56) = {'log\_util'};
M_.endo_names_long(56) = {'log_util'};
M_.endo_names(57) = {'log_util_ND'};
M_.endo_names_tex(57) = {'log\_util\_ND'};
M_.endo_names_long(57) = {'log_util_ND'};
M_.endo_names(58) = {'log_util_D'};
M_.endo_names_tex(58) = {'log\_util\_D'};
M_.endo_names_long(58) = {'log_util_D'};
M_.endo_names(59) = {'log_W'};
M_.endo_names_tex(59) = {'log\_W'};
M_.endo_names_long(59) = {'log_W'};
M_.endo_names(60) = {'C_obs'};
M_.endo_names_tex(60) = {'C\_obs'};
M_.endo_names_long(60) = {'C_obs'};
M_.endo_names(61) = {'I_obs'};
M_.endo_names_tex(61) = {'I\_obs'};
M_.endo_names_long(61) = {'I_obs'};
M_.endo_names(62) = {'Y_obs'};
M_.endo_names_tex(62) = {'Y\_obs'};
M_.endo_names_long(62) = {'Y_obs'};
M_.endo_names(63) = {'Y_N_obs'};
M_.endo_names_tex(63) = {'Y\_N\_obs'};
M_.endo_names_long(63) = {'Y_N_obs'};
M_.endo_names(64) = {'p_I_obs'};
M_.endo_names_tex(64) = {'p\_I\_obs'};
M_.endo_names_long(64) = {'p_I_obs'};
M_.endo_names(65) = {'N_obs'};
M_.endo_names_tex(65) = {'N\_obs'};
M_.endo_names_long(65) = {'N_obs'};
M_.endo_names(66) = {'NC_obs'};
M_.endo_names_tex(66) = {'NC\_obs'};
M_.endo_names_long(66) = {'NC_obs'};
M_.endo_names(67) = {'NI_obs'};
M_.endo_names_tex(67) = {'NI\_obs'};
M_.endo_names_long(67) = {'NI_obs'};
M_.endo_names(68) = {'util_ND_obs'};
M_.endo_names_tex(68) = {'util\_ND\_obs'};
M_.endo_names_long(68) = {'util_ND_obs'};
M_.endo_names(69) = {'util_D_obs'};
M_.endo_names_tex(69) = {'util\_D\_obs'};
M_.endo_names_long(69) = {'util_D_obs'};
M_.endo_names(70) = {'w_obs'};
M_.endo_names_tex(70) = {'w\_obs'};
M_.endo_names_long(70) = {'w_obs'};
M_.endo_names(71) = {'util_obs'};
M_.endo_names_tex(71) = {'util\_obs'};
M_.endo_names_long(71) = {'util_obs'};
M_.endo_names(72) = {'K_obs'};
M_.endo_names_tex(72) = {'K\_obs'};
M_.endo_names_long(72) = {'K_obs'};
M_.endo_names(73) = {'SR_obs'};
M_.endo_names_tex(73) = {'SR\_obs'};
M_.endo_names_long(73) = {'SR_obs'};
M_.endo_names(74) = {'AUX_EXO_LAG_74_0'};
M_.endo_names_tex(74) = {'AUX\_EXO\_LAG\_74\_0'};
M_.endo_names_long(74) = {'AUX_EXO_LAG_74_0'};
M_.endo_names(75) = {'AUX_EXO_LAG_74_1'};
M_.endo_names_tex(75) = {'AUX\_EXO\_LAG\_74\_1'};
M_.endo_names_long(75) = {'AUX_EXO_LAG_74_1'};
M_.endo_names(76) = {'AUX_EXO_LAG_74_2'};
M_.endo_names_tex(76) = {'AUX\_EXO\_LAG\_74\_2'};
M_.endo_names_long(76) = {'AUX_EXO_LAG_74_2'};
M_.endo_names(77) = {'AUX_EXO_LAG_74_3'};
M_.endo_names_tex(77) = {'AUX\_EXO\_LAG\_74\_3'};
M_.endo_names_long(77) = {'AUX_EXO_LAG_74_3'};
M_.endo_names(78) = {'AUX_EXO_LAG_76_0'};
M_.endo_names_tex(78) = {'AUX\_EXO\_LAG\_76\_0'};
M_.endo_names_long(78) = {'AUX_EXO_LAG_76_0'};
M_.endo_names(79) = {'AUX_EXO_LAG_76_1'};
M_.endo_names_tex(79) = {'AUX\_EXO\_LAG\_76\_1'};
M_.endo_names_long(79) = {'AUX_EXO_LAG_76_1'};
M_.endo_names(80) = {'AUX_EXO_LAG_76_2'};
M_.endo_names_tex(80) = {'AUX\_EXO\_LAG\_76\_2'};
M_.endo_names_long(80) = {'AUX_EXO_LAG_76_2'};
M_.endo_names(81) = {'AUX_EXO_LAG_76_3'};
M_.endo_names_tex(81) = {'AUX\_EXO\_LAG\_76\_3'};
M_.endo_names_long(81) = {'AUX_EXO_LAG_76_3'};
M_.endo_names(82) = {'AUX_EXO_LAG_78_0'};
M_.endo_names_tex(82) = {'AUX\_EXO\_LAG\_78\_0'};
M_.endo_names_long(82) = {'AUX_EXO_LAG_78_0'};
M_.endo_names(83) = {'AUX_EXO_LAG_78_1'};
M_.endo_names_tex(83) = {'AUX\_EXO\_LAG\_78\_1'};
M_.endo_names_long(83) = {'AUX_EXO_LAG_78_1'};
M_.endo_names(84) = {'AUX_EXO_LAG_78_2'};
M_.endo_names_tex(84) = {'AUX\_EXO\_LAG\_78\_2'};
M_.endo_names_long(84) = {'AUX_EXO_LAG_78_2'};
M_.endo_names(85) = {'AUX_EXO_LAG_78_3'};
M_.endo_names_tex(85) = {'AUX\_EXO\_LAG\_78\_3'};
M_.endo_names_long(85) = {'AUX_EXO_LAG_78_3'};
M_.endo_names(86) = {'AUX_EXO_LAG_81_0'};
M_.endo_names_tex(86) = {'AUX\_EXO\_LAG\_81\_0'};
M_.endo_names_long(86) = {'AUX_EXO_LAG_81_0'};
M_.endo_names(87) = {'AUX_EXO_LAG_81_1'};
M_.endo_names_tex(87) = {'AUX\_EXO\_LAG\_81\_1'};
M_.endo_names_long(87) = {'AUX_EXO_LAG_81_1'};
M_.endo_names(88) = {'AUX_EXO_LAG_81_2'};
M_.endo_names_tex(88) = {'AUX\_EXO\_LAG\_81\_2'};
M_.endo_names_long(88) = {'AUX_EXO_LAG_81_2'};
M_.endo_names(89) = {'AUX_EXO_LAG_81_3'};
M_.endo_names_tex(89) = {'AUX\_EXO\_LAG\_81\_3'};
M_.endo_names_long(89) = {'AUX_EXO_LAG_81_3'};
M_.endo_names(90) = {'AUX_EXO_LAG_83_0'};
M_.endo_names_tex(90) = {'AUX\_EXO\_LAG\_83\_0'};
M_.endo_names_long(90) = {'AUX_EXO_LAG_83_0'};
M_.endo_names(91) = {'AUX_EXO_LAG_83_1'};
M_.endo_names_tex(91) = {'AUX\_EXO\_LAG\_83\_1'};
M_.endo_names_long(91) = {'AUX_EXO_LAG_83_1'};
M_.endo_names(92) = {'AUX_EXO_LAG_83_2'};
M_.endo_names_tex(92) = {'AUX\_EXO\_LAG\_83\_2'};
M_.endo_names_long(92) = {'AUX_EXO_LAG_83_2'};
M_.endo_names(93) = {'AUX_EXO_LAG_83_3'};
M_.endo_names_tex(93) = {'AUX\_EXO\_LAG\_83\_3'};
M_.endo_names_long(93) = {'AUX_EXO_LAG_83_3'};
M_.endo_names(94) = {'AUX_EXO_LAG_85_0'};
M_.endo_names_tex(94) = {'AUX\_EXO\_LAG\_85\_0'};
M_.endo_names_long(94) = {'AUX_EXO_LAG_85_0'};
M_.endo_names(95) = {'AUX_EXO_LAG_85_1'};
M_.endo_names_tex(95) = {'AUX\_EXO\_LAG\_85\_1'};
M_.endo_names_long(95) = {'AUX_EXO_LAG_85_1'};
M_.endo_names(96) = {'AUX_EXO_LAG_85_2'};
M_.endo_names_tex(96) = {'AUX\_EXO\_LAG\_85\_2'};
M_.endo_names_long(96) = {'AUX_EXO_LAG_85_2'};
M_.endo_names(97) = {'AUX_EXO_LAG_85_3'};
M_.endo_names_tex(97) = {'AUX\_EXO\_LAG\_85\_3'};
M_.endo_names_long(97) = {'AUX_EXO_LAG_85_3'};
M_.endo_partitions = struct();
M_.param_names = cell(26,1);
M_.param_names_tex = cell(26,1);
M_.param_names_long = cell(26,1);
M_.param_names(1) = {'gam'};
M_.param_names_tex(1) = {'{\gamma}'};
M_.param_names_long(1) = {'Risk aversion'};
M_.param_names(2) = {'gam_max'};
M_.param_names_tex(2) = {'{\gamma_{max}}'};
M_.param_names_long(2) = {'Upper bound on risk aversion'};
M_.param_names(3) = {'beta'};
M_.param_names_tex(3) = {'{\beta}'};
M_.param_names_long(3) = {'Discount factor'};
M_.param_names(4) = {'g_bar'};
M_.param_names_tex(4) = {'{\overline{g}}'};
M_.param_names_long(4) = {'Quarterly trend growth rate'};
M_.param_names(5) = {'nu'};
M_.param_names_tex(5) = {'\nu'};
M_.param_names_long(5) = {'Frisch elasticity'};
M_.param_names(6) = {'sigma_s'};
M_.param_names_tex(6) = {'\sigma_s'};
M_.param_names_long(6) = {'wealth effect on labor supply'};
M_.param_names(7) = {'mu_ss'};
M_.param_names_tex(7) = {'\mu_{ss}'};
M_.param_names_long(7) = {'steady-state wage markup'};
M_.param_names(8) = {'sigma_ac'};
M_.param_names_tex(8) = {'{\sigma_{ac}}'};
M_.param_names_long(8) = {'Inverse elasticity of marginal utilization cost wrt rental rate:C'};
M_.param_names(9) = {'sigma_ai'};
M_.param_names_tex(9) = {'{\sigma_{ai}}'};
M_.param_names_long(9) = {'Inverse elasticity of marginal utilization cost wrt rental rate:I'};
M_.param_names(10) = {'Psi_C'};
M_.param_names_tex(10) = {'{\Psi_C}'};
M_.param_names_long(10) = {'Investment adjustment cost parameter:C'};
M_.param_names(11) = {'Psi_I'};
M_.param_names_tex(11) = {'{\Psi_I}'};
M_.param_names_long(11) = {'Investment adjustment cost parameter:I'};
M_.param_names(12) = {'I_Y'};
M_.param_names_tex(12) = {'{I_Y}'};
M_.param_names_long(12) = {'Investment-output ratio'};
M_.param_names(13) = {'K_Y'};
M_.param_names_tex(13) = {'{K_Y}'};
M_.param_names_long(13) = {'Capital-output ratio (quarterly)'};
M_.param_names(14) = {'labor_share'};
M_.param_names_tex(14) = {'(labor share)'};
M_.param_names_long(14) = {'Labor share'};
M_.param_names(15) = {'nu_R'};
M_.param_names_tex(15) = {'{\nu_R}'};
M_.param_names_long(15) = {'Fixed cost share'};
M_.param_names(16) = {'ha'};
M_.param_names_tex(16) = {'{ha}'};
M_.param_names_long(16) = {'Habit persistence'};
M_.param_names(17) = {'theta'};
M_.param_names_tex(17) = {'{\theta}'};
M_.param_names_long(17) = {'Inverse intersectoral elasticity of labor supply'};
M_.param_names(18) = {'rho_g'};
M_.param_names_tex(18) = {'{\rho_g}'};
M_.param_names_long(18) = {'persistence TFP growth shock'};
M_.param_names(19) = {'rho_Z'};
M_.param_names_tex(19) = {'{\rho_Z}'};
M_.param_names_long(19) = {'persistence TFP shock'};
M_.param_names(20) = {'rho_ZI'};
M_.param_names_tex(20) = {'{\rho_{ZI}}'};
M_.param_names_long(20) = {'persistence I-specific shock'};
M_.param_names(21) = {'rho_N'};
M_.param_names_tex(21) = {'{\rho_N}'};
M_.param_names_long(21) = {'persistence labor supply shock'};
M_.param_names(22) = {'rho_b'};
M_.param_names_tex(22) = {'{\rho_b}'};
M_.param_names_long(22) = {'persistence discount factor shock'};
M_.param_names(23) = {'rho_muC'};
M_.param_names_tex(23) = {'{\rho_{muC}}'};
M_.param_names_long(23) = {'persistence wage markup shock:C'};
M_.param_names(24) = {'rho_muI'};
M_.param_names_tex(24) = {'{\rho_{muI}}'};
M_.param_names_long(24) = {'persistence wage markup shock:I'};
M_.param_names(25) = {'p_I_ss'};
M_.param_names_tex(25) = {'p\_I\_ss'};
M_.param_names_long(25) = {'p_I_ss'};
M_.param_names(26) = {'N_ss'};
M_.param_names_tex(26) = {'N\_ss'};
M_.param_names_long(26) = {'N_ss'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 13;
M_.endo_nbr = 97;
M_.param_nbr = 26;
M_.orig_endo_nbr = 73;
M_.aux_vars(1).endo_index = 74;
M_.aux_vars(1).type = 3;
M_.aux_vars(1).orig_index = 2;
M_.aux_vars(1).orig_lead_lag = 0;
M_.aux_vars(1).orig_expr = 'e_g_news';
M_.aux_vars(2).endo_index = 75;
M_.aux_vars(2).type = 3;
M_.aux_vars(2).orig_index = 2;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(2).orig_expr = 'AUX_EXO_LAG_74_0(-1)';
M_.aux_vars(3).endo_index = 76;
M_.aux_vars(3).type = 3;
M_.aux_vars(3).orig_index = 2;
M_.aux_vars(3).orig_lead_lag = -2;
M_.aux_vars(3).orig_expr = 'AUX_EXO_LAG_74_1(-1)';
M_.aux_vars(4).endo_index = 77;
M_.aux_vars(4).type = 3;
M_.aux_vars(4).orig_index = 2;
M_.aux_vars(4).orig_lead_lag = -3;
M_.aux_vars(4).orig_expr = 'AUX_EXO_LAG_74_2(-1)';
M_.aux_vars(5).endo_index = 78;
M_.aux_vars(5).type = 3;
M_.aux_vars(5).orig_index = 4;
M_.aux_vars(5).orig_lead_lag = 0;
M_.aux_vars(5).orig_expr = 'e_Z_news';
M_.aux_vars(6).endo_index = 79;
M_.aux_vars(6).type = 3;
M_.aux_vars(6).orig_index = 4;
M_.aux_vars(6).orig_lead_lag = -1;
M_.aux_vars(6).orig_expr = 'AUX_EXO_LAG_76_0(-1)';
M_.aux_vars(7).endo_index = 80;
M_.aux_vars(7).type = 3;
M_.aux_vars(7).orig_index = 4;
M_.aux_vars(7).orig_lead_lag = -2;
M_.aux_vars(7).orig_expr = 'AUX_EXO_LAG_76_1(-1)';
M_.aux_vars(8).endo_index = 81;
M_.aux_vars(8).type = 3;
M_.aux_vars(8).orig_index = 4;
M_.aux_vars(8).orig_lead_lag = -3;
M_.aux_vars(8).orig_expr = 'AUX_EXO_LAG_76_2(-1)';
M_.aux_vars(9).endo_index = 82;
M_.aux_vars(9).type = 3;
M_.aux_vars(9).orig_index = 6;
M_.aux_vars(9).orig_lead_lag = 0;
M_.aux_vars(9).orig_expr = 'e_ZI_news';
M_.aux_vars(10).endo_index = 83;
M_.aux_vars(10).type = 3;
M_.aux_vars(10).orig_index = 6;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(10).orig_expr = 'AUX_EXO_LAG_78_0(-1)';
M_.aux_vars(11).endo_index = 84;
M_.aux_vars(11).type = 3;
M_.aux_vars(11).orig_index = 6;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(11).orig_expr = 'AUX_EXO_LAG_78_1(-1)';
M_.aux_vars(12).endo_index = 85;
M_.aux_vars(12).type = 3;
M_.aux_vars(12).orig_index = 6;
M_.aux_vars(12).orig_lead_lag = -3;
M_.aux_vars(12).orig_expr = 'AUX_EXO_LAG_78_2(-1)';
M_.aux_vars(13).endo_index = 86;
M_.aux_vars(13).type = 3;
M_.aux_vars(13).orig_index = 9;
M_.aux_vars(13).orig_lead_lag = 0;
M_.aux_vars(13).orig_expr = 'e_b_news';
M_.aux_vars(14).endo_index = 87;
M_.aux_vars(14).type = 3;
M_.aux_vars(14).orig_index = 9;
M_.aux_vars(14).orig_lead_lag = -1;
M_.aux_vars(14).orig_expr = 'AUX_EXO_LAG_81_0(-1)';
M_.aux_vars(15).endo_index = 88;
M_.aux_vars(15).type = 3;
M_.aux_vars(15).orig_index = 9;
M_.aux_vars(15).orig_lead_lag = -2;
M_.aux_vars(15).orig_expr = 'AUX_EXO_LAG_81_1(-1)';
M_.aux_vars(16).endo_index = 89;
M_.aux_vars(16).type = 3;
M_.aux_vars(16).orig_index = 9;
M_.aux_vars(16).orig_lead_lag = -3;
M_.aux_vars(16).orig_expr = 'AUX_EXO_LAG_81_2(-1)';
M_.aux_vars(17).endo_index = 90;
M_.aux_vars(17).type = 3;
M_.aux_vars(17).orig_index = 11;
M_.aux_vars(17).orig_lead_lag = 0;
M_.aux_vars(17).orig_expr = 'e_muC_news';
M_.aux_vars(18).endo_index = 91;
M_.aux_vars(18).type = 3;
M_.aux_vars(18).orig_index = 11;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(18).orig_expr = 'AUX_EXO_LAG_83_0(-1)';
M_.aux_vars(19).endo_index = 92;
M_.aux_vars(19).type = 3;
M_.aux_vars(19).orig_index = 11;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(19).orig_expr = 'AUX_EXO_LAG_83_1(-1)';
M_.aux_vars(20).endo_index = 93;
M_.aux_vars(20).type = 3;
M_.aux_vars(20).orig_index = 11;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(20).orig_expr = 'AUX_EXO_LAG_83_2(-1)';
M_.aux_vars(21).endo_index = 94;
M_.aux_vars(21).type = 3;
M_.aux_vars(21).orig_index = 13;
M_.aux_vars(21).orig_lead_lag = 0;
M_.aux_vars(21).orig_expr = 'e_muI_news';
M_.aux_vars(22).endo_index = 95;
M_.aux_vars(22).type = 3;
M_.aux_vars(22).orig_index = 13;
M_.aux_vars(22).orig_lead_lag = -1;
M_.aux_vars(22).orig_expr = 'AUX_EXO_LAG_85_0(-1)';
M_.aux_vars(23).endo_index = 96;
M_.aux_vars(23).type = 3;
M_.aux_vars(23).orig_index = 13;
M_.aux_vars(23).orig_lead_lag = -2;
M_.aux_vars(23).orig_expr = 'AUX_EXO_LAG_85_1(-1)';
M_.aux_vars(24).endo_index = 97;
M_.aux_vars(24).type = 3;
M_.aux_vars(24).orig_index = 13;
M_.aux_vars(24).orig_lead_lag = -3;
M_.aux_vars(24).orig_expr = 'AUX_EXO_LAG_85_2(-1)';
options_.varobs = cell(8, 1);
options_.varobs(1)  = {'NC_obs'};
options_.varobs(2)  = {'NI_obs'};
options_.varobs(3)  = {'C_obs'};
options_.varobs(4)  = {'I_obs'};
options_.varobs(5)  = {'p_I_obs'};
options_.varobs(6)  = {'util_ND_obs'};
options_.varobs(7)  = {'util_D_obs'};
options_.varobs(8)  = {'w_obs'};
options_.varobs_id = [ 66 67 60 61 64 68 69 70  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(13, 13);
M_.Correlation_matrix = eye(13, 13);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 73;
M_.eq_nbr = 97;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 4;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 4;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 4;
M_.lead_lag_incidence = [
 0 52 0;
 1 53 0;
 0 54 0;
 2 55 0;
 3 56 0;
 0 57 0;
 4 58 0;
 5 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 6 64 0;
 0 65 0;
 7 66 0;
 8 67 0;
 9 68 0;
 10 69 0;
 11 70 0;
 0 71 149;
 0 72 150;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 151;
 0 77 152;
 0 78 153;
 0 79 154;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 155;
 0 85 156;
 0 86 157;
 12 87 0;
 0 88 0;
 0 89 158;
 0 90 159;
 0 91 160;
 0 92 161;
 0 93 0;
 0 94 0;
 0 95 0;
 0 96 0;
 13 97 162;
 14 98 0;
 15 99 0;
 16 100 0;
 17 101 0;
 18 102 0;
 19 103 0;
 20 104 0;
 21 105 0;
 22 106 0;
 23 107 0;
 24 108 0;
 25 109 0;
 26 110 0;
 0 111 0;
 0 112 0;
 0 113 0;
 0 114 0;
 0 115 0;
 0 116 0;
 0 117 0;
 0 118 0;
 0 119 0;
 0 120 0;
 0 121 0;
 0 122 0;
 27 123 0;
 0 124 0;
 28 125 0;
 29 126 0;
 30 127 0;
 31 128 0;
 32 129 0;
 33 130 0;
 34 131 0;
 35 132 0;
 36 133 0;
 37 134 0;
 38 135 0;
 39 136 0;
 40 137 0;
 41 138 0;
 42 139 0;
 43 140 0;
 44 141 0;
 45 142 0;
 46 143 0;
 47 144 0;
 48 145 0;
 49 146 0;
 50 147 0;
 51 148 0;]';
M_.nstatic = 33;
M_.nfwrd   = 13;
M_.npred   = 50;
M_.nboth   = 1;
M_.nsfwrd   = 14;
M_.nspred   = 51;
M_.ndynamic   = 64;
M_.dynamic_tmp_nbr = [37; 14; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Labor composite' ;
  2 , 'name' , 'Labor leisure:C' ;
  3 , 'name' , 'Labor leisure:I' ;
  4 , 'name' , 'Composite utility term' ;
  5 , 'name' , 'Law of motion of wealth effects variable' ;
  6 , 'name' , 'Investment adjustment cost function:C' ;
  7 , 'name' , 'Investment adjustment cost function:I' ;
  8 , 'name' , 'Investment adjustment cost function: derivative C' ;
  9 , 'name' , 'Investment adjustment cost function: derivative I' ;
  10 , 'name' , 'Investment growth:C' ;
  11 , 'name' , 'Investment growth:I' ;
  12 , 'name' , 'Tobins Q: C' ;
  13 , 'name' , 'Tobins Q: I' ;
  14 , 'name' , 'Euler equation: C' ;
  15 , 'name' , 'Euler equation: I' ;
  16 , 'name' , 'Utilization: C' ;
  17 , 'name' , 'Utilization: I' ;
  18 , 'name' , 'Depreciation rate: C' ;
  19 , 'name' , 'Depreciation rate: I' ;
  20 , 'name' , 'Depreciation rate derivative: C' ;
  21 , 'name' , 'Depreciation rate derivative: I' ;
  22 , 'name' , 'Consumption production' ;
  23 , 'name' , 'Investment production' ;
  24 , 'name' , 'Capital law of motion:C' ;
  25 , 'name' , 'Capital law of motion:I' ;
  26 , 'name' , 'Labor demand:C' ;
  27 , 'name' , 'Labor demand:I' ;
  28 , 'name' , 'Capital demand:C' ;
  29 , 'name' , 'Capital demand:I' ;
  30 , 'name' , 'Labor composition' ;
  31 , 'name' , 'Capital composition' ;
  32 , 'name' , 'Investment composition' ;
  33 , 'name' , 'Aggregate wage' ;
  34 , 'name' , 'Output (base-year prices)' ;
  35 , 'name' , 'Capacity utilization' ;
  36 , 'name' , 'util_D' ;
  37 , 'name' , 'util' ;
  38 , 'name' , 'stochastic trend process' ;
  39 , 'name' , 'Stationary TFP process' ;
  40 , 'name' , 'Independent component of I-specific tech' ;
  41 , 'name' , 'Investment-specific TFP process' ;
  42 , 'name' , 'Labor supply process' ;
  43 , 'name' , 'Consumption preference process' ;
  44 , 'name' , 'Wage-markup process: C' ;
  45 , 'name' , 'Wage-markup process: I' ;
  46 , 'name' , 'Definition log output' ;
  47 , 'name' , 'Definition log consumption' ;
  48 , 'name' , 'Definition log investment' ;
  49 , 'name' , 'Definition log hours' ;
  50 , 'name' , 'log_NC' ;
  51 , 'name' , 'log_NI' ;
  52 , 'name' , 'log capital' ;
  53 , 'name' , 'Definition log labor productivity' ;
  54 , 'name' , 'Definition of log relative investment  price' ;
  55 , 'name' , 'Definition of log capacity utilization' ;
  56 , 'name' , 'log_util_ND' ;
  57 , 'name' , 'log_util_D' ;
  58 , 'name' , 'Definition of log wages' ;
  59 , 'name' , 'Definition of log Solow residual' ;
  60 , 'name' , 'C_obs' ;
  61 , 'name' , 'I_obs' ;
  62 , 'name' , 'Y_obs' ;
  63 , 'name' , 'Y_N_obs' ;
  64 , 'name' , 'K_obs' ;
  65 , 'name' , 'w_obs' ;
  66 , 'name' , 'SR_obs' ;
  67 , 'name' , 'p_I_obs' ;
  68 , 'name' , 'N_obs' ;
  69 , 'name' , 'NC_obs' ;
  70 , 'name' , 'NI_obs' ;
  71 , 'name' , 'util_ND_obs' ;
  72 , 'name' , 'util_D_obs' ;
  73 , 'name' , 'util_obs' ;
};
M_.mapping.Y.eqidx = [34 37 46 ];
M_.mapping.C.eqidx = [4 5 22 26 28 34 37 47 ];
M_.mapping.I.eqidx = [23 27 29 32 34 37 48 ];
M_.mapping.I_C.eqidx = [10 24 32 ];
M_.mapping.I_I.eqidx = [11 25 32 ];
M_.mapping.K.eqidx = [31 52 ];
M_.mapping.K_C.eqidx = [22 24 28 31 35 ];
M_.mapping.K_I.eqidx = [23 25 29 31 36 ];
M_.mapping.N.eqidx = [30 33 49 ];
M_.mapping.N_C.eqidx = [1 2 22 26 30 33 35 50 ];
M_.mapping.N_I.eqidx = [1 3 23 27 30 33 36 51 ];
M_.mapping.N_comp.eqidx = [1 2 3 4 ];
M_.mapping.Z_C.eqidx = [22 39 41 ];
M_.mapping.u_ZI.eqidx = [40 41 ];
M_.mapping.Z_I.eqidx = [23 40 41 ];
M_.mapping.theta_N.eqidx = [2 3 4 42 ];
M_.mapping.theta_b.eqidx = [12 13 14 15 43 ];
M_.mapping.mu_C.eqidx = [2 44 ];
M_.mapping.mu_I.eqidx = [3 45 ];
M_.mapping.R_C.eqidx = [14 16 28 ];
M_.mapping.R_I.eqidx = [15 17 29 ];
M_.mapping.W_C.eqidx = [2 26 33 ];
M_.mapping.W_I.eqidx = [3 27 33 ];
M_.mapping.W.eqidx = [33 58 ];
M_.mapping.h_C.eqidx = [14 18 20 22 28 35 ];
M_.mapping.h_I.eqidx = [15 19 21 23 29 36 ];
M_.mapping.delta_C.eqidx = [14 18 24 ];
M_.mapping.delta_I.eqidx = [15 19 25 ];
M_.mapping.delta_C_pr.eqidx = [16 20 ];
M_.mapping.delta_I_pr.eqidx = [17 21 ];
M_.mapping.Sc.eqidx = [6 12 24 ];
M_.mapping.Si.eqidx = [7 13 25 ];
M_.mapping.Sc_pr.eqidx = [8 12 ];
M_.mapping.Si_pr.eqidx = [9 13 ];
M_.mapping.Gam.eqidx = [4 12 13 14 15 ];
M_.mapping.zeta.eqidx = [2 3 4 5 ];
M_.mapping.p_I.eqidx = [12 13 27 29 54 ];
M_.mapping.Q_C.eqidx = [12 14 16 ];
M_.mapping.Q_I.eqidx = [13 15 17 ];
M_.mapping.x_C.eqidx = [6 8 10 12 ];
M_.mapping.x_I.eqidx = [7 9 11 13 ];
M_.mapping.log_SR.eqidx = [59 ];
M_.mapping.util.eqidx = [37 55 ];
M_.mapping.util_ND.eqidx = [35 37 56 ];
M_.mapping.util_D.eqidx = [36 37 57 ];
M_.mapping.g.eqidx = [10 11 12 13 14 15 22 23 24 25 28 29 38 60 61 62 63 64 65 ];
M_.mapping.log_Y.eqidx = [46 53 59 62 ];
M_.mapping.log_C.eqidx = [47 60 ];
M_.mapping.log_I.eqidx = [48 61 ];
M_.mapping.log_N.eqidx = [49 53 59 68 ];
M_.mapping.log_NC.eqidx = [50 69 ];
M_.mapping.log_NI.eqidx = [51 70 ];
M_.mapping.log_K.eqidx = [52 59 64 ];
M_.mapping.log_Y_N.eqidx = [53 63 ];
M_.mapping.log_p_I.eqidx = [54 67 ];
M_.mapping.log_util.eqidx = [55 73 ];
M_.mapping.log_util_ND.eqidx = [56 71 ];
M_.mapping.log_util_D.eqidx = [57 72 ];
M_.mapping.log_W.eqidx = [58 65 ];
M_.mapping.C_obs.eqidx = [60 ];
M_.mapping.I_obs.eqidx = [61 ];
M_.mapping.Y_obs.eqidx = [62 66 ];
M_.mapping.Y_N_obs.eqidx = [63 ];
M_.mapping.p_I_obs.eqidx = [67 ];
M_.mapping.N_obs.eqidx = [66 68 ];
M_.mapping.NC_obs.eqidx = [69 ];
M_.mapping.NI_obs.eqidx = [70 ];
M_.mapping.util_ND_obs.eqidx = [71 ];
M_.mapping.util_D_obs.eqidx = [72 ];
M_.mapping.w_obs.eqidx = [65 ];
M_.mapping.util_obs.eqidx = [73 ];
M_.mapping.K_obs.eqidx = [64 66 ];
M_.mapping.SR_obs.eqidx = [66 ];
M_.mapping.e_g.eqidx = [38 ];
M_.mapping.e_g_news.eqidx = [38 ];
M_.mapping.e_Z.eqidx = [39 ];
M_.mapping.e_Z_news.eqidx = [39 ];
M_.mapping.e_ZI.eqidx = [40 ];
M_.mapping.e_ZI_news.eqidx = [40 ];
M_.mapping.e_N.eqidx = [42 ];
M_.mapping.e_b.eqidx = [43 ];
M_.mapping.e_b_news.eqidx = [43 ];
M_.mapping.e_muC.eqidx = [44 ];
M_.mapping.e_muC_news.eqidx = [44 ];
M_.mapping.e_muI.eqidx = [45 ];
M_.mapping.e_muI_news.eqidx = [45 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [2 4 5 7 8 13 15 16 17 18 19 36 46 47 48 49 50 51 52 53 54 55 56 57 58 59 72 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 ];
M_.exo_names_orig_ord = [1:13];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(97, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(13, 1);
M_.params = NaN(26, 1);
M_.endo_trends = struct('deflator', cell(97, 1), 'log_deflator', cell(97, 1), 'growth_factor', cell(97, 1), 'log_growth_factor', cell(97, 1));
M_.NNZDerivatives = [329; -1; -1; ];
M_.static_tmp_nbr = [35; 10; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 2.0;
gam = M_.params(1);
M_.params(3) = 0.99;
beta = M_.params(3);
M_.params(4) = 0.0045;
g_bar = M_.params(4);
M_.params(5) = 0.72;
nu = M_.params(5);
M_.params(6) = 0.5;
sigma_s = M_.params(6);
M_.params(16) = 0.1;
ha = M_.params(16);
M_.params(7) = 1.15;
mu_ss = M_.params(7);
M_.params(8) = 0.32;
sigma_ac = M_.params(8);
M_.params(9) = 0.32;
sigma_ai = M_.params(9);
M_.params(10) = 1.5;
Psi_C = M_.params(10);
M_.params(11) = 1.5;
Psi_I = M_.params(11);
M_.params(12) = 0.20;
I_Y = M_.params(12);
M_.params(13) = 11;
K_Y = M_.params(13);
M_.params(14) = 0.67;
labor_share = M_.params(14);
M_.params(15) = 0.2;
nu_R = M_.params(15);
M_.params(17) = 0.5;
theta = M_.params(17);
M_.params(25) = 1.0;
p_I_ss = M_.params(25);
M_.params(26) = 0.30;
N_ss = M_.params(26);
M_.params(18) = 0.1;
rho_g = M_.params(18);
M_.params(19) = 0.9;
rho_Z = M_.params(19);
M_.params(20) = 0.9;
rho_ZI = M_.params(20);
M_.params(21) = 0.9;
rho_N = M_.params(21);
rho_D = 0.9;
rho_DI = 0.9;
M_.params(22) = 0.9;
rho_b = M_.params(22);
M_.params(23) = 0.9;
rho_muC = M_.params(23);
M_.params(24) = 0.9;
rho_muI = M_.params(24);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 5.184e-05;
M_.Sigma_e(3, 3) = 5.184e-05;
M_.Sigma_e(5, 5) = 5.184e-05;
M_.Sigma_e(7, 7) = 5.184e-05;
M_.Sigma_e(8, 8) = 5.184e-05;
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 1, 1.5, 1.0, 4.0, 1, 1.5, 0.25, 1.0, 4.0, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.5, 0.0, 0.95, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, 0.72, 0.05, 2.0, 2, 0.72, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, 0.5, 0.0, 1.0, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.20, 0.01, 0.5, 1, 0.2, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, 0.32, 0.0, 10, 4, 1, 1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, 0.32, 0.0, 10, 4, 1, 1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, 1.5, 0.0, 50, 2, 4, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, 1.5, 0.0, 50, 2, 4, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.5, .00, 10, 2, 1, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.1, 0.0001, 0.9, 1, 0.1, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, 0.95, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.95, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.6, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 0.95, 0.01, 0.99999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.95, 0.01, 0.99999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, 0.95, 0.01, 0.99999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.01, 0.00001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.01, 0.00001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.01, 0.00001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.01, 0.00001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, 0.01, 0.0001, 0.4, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, 0.01, 0.0001, 0.4, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 10, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 11, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 12, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 13, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_endo = [estim_params_.var_endo; 70, 0.01, 0.0001, 0.05, 2, 0.01, 0.01, NaN, NaN, NaN ];
options_.TeX=1;
options_.TeX = true;
options_.lik_init = 2;
options_.mh_drop = 0.3;
options_.mh_init_scale = 0.0001;
options_.mh_jscale = 0.003;
options_.mh_nblck = 2;
options_.mh_replic = 100000;
options_.mode_check.status = true;
options_.mode_compute = 4;
options_.presample = 0;
options_.prior_trunc = 0;
options_.MCMC_jumping_covariance = 'prior_variance';
options_.datafile = 'observables_sectoral';
options_.optim_opt = '''MaxIter'',200';
options_.order = 1;
var_list_ = {'Y_obs';'Y_N_obs';'I_obs';'p_I_obs';'C_obs';'NC_obs';'NI_obs';'util_ND_obs';'util_D_obs';'w_obs'};
oo_recursive_=dynare_estimation(var_list_);
write_latex_parameter_table;
write_latex_definitions;
write_latex_prior_table;
collect_latex_files;
options_.irf = 100;
options_.nofunctions = true;
options_.order = 1;
options_.periods = 0;
var_list_ = {'Y_obs';'Y_N_obs';'SR_obs';'I_obs';'p_I_obs';'C_obs';'NC_obs';'NI_obs';'util_ND_obs';'util_D_obs';'w_obs'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'RBC_sectoral_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_sectoral_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_sectoral_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_sectoral_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_sectoral_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_sectoral_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_sectoral_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
