%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'BRS_growth_util_shock';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(6,1);
M_.exo_names_tex = cell(6,1);
M_.exo_names_long = cell(6,1);
M_.exo_names(1) = {'e_g'};
M_.exo_names_tex(1) = {'{e_g}'};
M_.exo_names_long(1) = {'Labor-augmenting-technology growth shock'};
M_.exo_names(2) = {'e_Z'};
M_.exo_names_tex(2) = {'{e_Z}'};
M_.exo_names_long(2) = {'TFP shock'};
M_.exo_names(3) = {'e_ZI'};
M_.exo_names_tex(3) = {'{e_{ZI}}'};
M_.exo_names_long(3) = {'Investment-specific tech shock'};
M_.exo_names(4) = {'e_N'};
M_.exo_names_tex(4) = {'{e_N}'};
M_.exo_names_long(4) = {'Labor supply shock'};
M_.exo_names(5) = {'e_D'};
M_.exo_names_tex(5) = {'{e_D}'};
M_.exo_names_long(5) = {'Shopping disutility shock'};
M_.exo_names(6) = {'e_h'};
M_.exo_names_tex(6) = {'{e_h}'};
M_.exo_names_long(6) = {'Capacity utilization depreciation shock'};
M_.endo_names = cell(52,1);
M_.endo_names_tex = cell(52,1);
M_.endo_names_long = cell(52,1);
M_.endo_names(1) = {'Y'};
M_.endo_names_tex(1) = {'{Y}'};
M_.endo_names_long(1) = {'output'};
M_.endo_names(2) = {'C'};
M_.endo_names_tex(2) = {'{C}'};
M_.endo_names_long(2) = {'consumption'};
M_.endo_names(3) = {'I'};
M_.endo_names_tex(3) = {'{I}'};
M_.endo_names_long(3) = {'investment'};
M_.endo_names(4) = {'K'};
M_.endo_names_tex(4) = {'{K}'};
M_.endo_names_long(4) = {'Capital'};
M_.endo_names(5) = {'K_C'};
M_.endo_names_tex(5) = {'{K_C}'};
M_.endo_names_long(5) = {'Capital:C'};
M_.endo_names(6) = {'K_I'};
M_.endo_names_tex(6) = {'{K_I}'};
M_.endo_names_long(6) = {'Capital:I'};
M_.endo_names(7) = {'N'};
M_.endo_names_tex(7) = {'{N}'};
M_.endo_names_long(7) = {'Hours'};
M_.endo_names(8) = {'N_C'};
M_.endo_names_tex(8) = {'{N_C}'};
M_.endo_names_long(8) = {'Hours:C'};
M_.endo_names(9) = {'N_I'};
M_.endo_names_tex(9) = {'{N_I}'};
M_.endo_names_long(9) = {'Hours:I'};
M_.endo_names(10) = {'Z_C'};
M_.endo_names_tex(10) = {'{Z_C}'};
M_.endo_names_long(10) = {'Tech:C'};
M_.endo_names(11) = {'u_ZI'};
M_.endo_names_tex(11) = {'u\_ZI'};
M_.endo_names_long(11) = {'u_ZI'};
M_.endo_names(12) = {'Z_I'};
M_.endo_names_tex(12) = {'{Z_I}'};
M_.endo_names_long(12) = {'Tech:I'};
M_.endo_names(13) = {'theta_N'};
M_.endo_names_tex(13) = {'{\theta_N}'};
M_.endo_names_long(13) = {'Labor disutility'};
M_.endo_names(14) = {'theta_D'};
M_.endo_names_tex(14) = {'{\theta_D}'};
M_.endo_names_long(14) = {'Shopping disutility'};
M_.endo_names(15) = {'theta_h'};
M_.endo_names_tex(15) = {'{\theta_h}'};
M_.endo_names_long(15) = {'Capacity utilization depreciation shock'};
M_.endo_names(16) = {'R_C'};
M_.endo_names_tex(16) = {'{R_C}'};
M_.endo_names_long(16) = {'Capital rental rate:C'};
M_.endo_names(17) = {'R_I'};
M_.endo_names_tex(17) = {'{R_I}'};
M_.endo_names_long(17) = {'Capital rental rate:I'};
M_.endo_names(18) = {'W'};
M_.endo_names_tex(18) = {'{W}'};
M_.endo_names_long(18) = {'Real wage'};
M_.endo_names(19) = {'h_C'};
M_.endo_names_tex(19) = {'{h_C}'};
M_.endo_names_long(19) = {'Capital utilization rate:C'};
M_.endo_names(20) = {'h_I'};
M_.endo_names_tex(20) = {'{h_I}'};
M_.endo_names_long(20) = {'Capital utilization rate:I'};
M_.endo_names(21) = {'delta_C'};
M_.endo_names_tex(21) = {'{\delta_C}'};
M_.endo_names_long(21) = {'Capital depreciation rate:C'};
M_.endo_names(22) = {'delta_I'};
M_.endo_names_tex(22) = {'{\delta_I}'};
M_.endo_names_long(22) = {'Capital depreciation rate:I'};
M_.endo_names(23) = {'delta_C_pr'};
M_.endo_names_tex(23) = {'{\delta_C}'};
M_.endo_names_long(23) = {'Capital depreciation rate derivative:C'};
M_.endo_names(24) = {'delta_I_pr'};
M_.endo_names_tex(24) = {'{\delta_I}'};
M_.endo_names_long(24) = {'Capital depreciation rate derivative:I'};
M_.endo_names(25) = {'D'};
M_.endo_names_tex(25) = {'{D}'};
M_.endo_names_long(25) = {'Shopping effort'};
M_.endo_names(26) = {'D_C'};
M_.endo_names_tex(26) = {'{D}'};
M_.endo_names_long(26) = {'Shopping effort:C'};
M_.endo_names(27) = {'D_I'};
M_.endo_names_tex(27) = {'{D}'};
M_.endo_names_long(27) = {'Shopping effort:I'};
M_.endo_names(28) = {'Gam'};
M_.endo_names_tex(28) = {'{\Gamma}'};
M_.endo_names_long(28) = {'Composite utility term'};
M_.endo_names(29) = {'p_I'};
M_.endo_names_tex(29) = {'{p_I}'};
M_.endo_names_long(29) = {'Relative investment price'};
M_.endo_names(30) = {'Q'};
M_.endo_names_tex(30) = {'{Q}'};
M_.endo_names_long(30) = {'Relative price of capital'};
M_.endo_names(31) = {'util'};
M_.endo_names_tex(31) = {'{util}'};
M_.endo_names_long(31) = {'Capacity utilization:'};
M_.endo_names(32) = {'g'};
M_.endo_names_tex(32) = {'{g}'};
M_.endo_names_long(32) = {'Output growth rate (labor-augmenting technology)'};
M_.endo_names(33) = {'log_Y'};
M_.endo_names_tex(33) = {'log\_Y'};
M_.endo_names_long(33) = {'log_Y'};
M_.endo_names(34) = {'log_C'};
M_.endo_names_tex(34) = {'log\_C'};
M_.endo_names_long(34) = {'log_C'};
M_.endo_names(35) = {'log_I'};
M_.endo_names_tex(35) = {'log\_I'};
M_.endo_names_long(35) = {'log_I'};
M_.endo_names(36) = {'log_N'};
M_.endo_names_tex(36) = {'log\_N'};
M_.endo_names_long(36) = {'log_N'};
M_.endo_names(37) = {'log_NC'};
M_.endo_names_tex(37) = {'log\_NC'};
M_.endo_names_long(37) = {'log_NC'};
M_.endo_names(38) = {'log_NI'};
M_.endo_names_tex(38) = {'log\_NI'};
M_.endo_names_long(38) = {'log_NI'};
M_.endo_names(39) = {'log_Y_N'};
M_.endo_names_tex(39) = {'log\_Y\_N'};
M_.endo_names_long(39) = {'log_Y_N'};
M_.endo_names(40) = {'log_D'};
M_.endo_names_tex(40) = {'log\_D'};
M_.endo_names_long(40) = {'log_D'};
M_.endo_names(41) = {'log_p_I'};
M_.endo_names_tex(41) = {'log\_p\_I'};
M_.endo_names_long(41) = {'log_p_I'};
M_.endo_names(42) = {'log_util'};
M_.endo_names_tex(42) = {'log\_util'};
M_.endo_names_long(42) = {'log_util'};
M_.endo_names(43) = {'C_obs'};
M_.endo_names_tex(43) = {'C\_obs'};
M_.endo_names_long(43) = {'C_obs'};
M_.endo_names(44) = {'I_obs'};
M_.endo_names_tex(44) = {'I\_obs'};
M_.endo_names_long(44) = {'I_obs'};
M_.endo_names(45) = {'Y_obs'};
M_.endo_names_tex(45) = {'Y\_obs'};
M_.endo_names_long(45) = {'Y_obs'};
M_.endo_names(46) = {'Y_N_obs'};
M_.endo_names_tex(46) = {'Y\_N\_obs'};
M_.endo_names_long(46) = {'Y_N_obs'};
M_.endo_names(47) = {'p_I_obs'};
M_.endo_names_tex(47) = {'p\_I\_obs'};
M_.endo_names_long(47) = {'p_I_obs'};
M_.endo_names(48) = {'N_obs'};
M_.endo_names_tex(48) = {'N\_obs'};
M_.endo_names_long(48) = {'N_obs'};
M_.endo_names(49) = {'NC_obs'};
M_.endo_names_tex(49) = {'NC\_obs'};
M_.endo_names_long(49) = {'NC_obs'};
M_.endo_names(50) = {'NI_obs'};
M_.endo_names_tex(50) = {'NI\_obs'};
M_.endo_names_long(50) = {'NI_obs'};
M_.endo_names(51) = {'util_obs'};
M_.endo_names_tex(51) = {'util\_obs'};
M_.endo_names_long(51) = {'util_obs'};
M_.endo_names(52) = {'D_obs'};
M_.endo_names_tex(52) = {'D\_obs'};
M_.endo_names_long(52) = {'D_obs'};
M_.endo_partitions = struct();
M_.param_names = cell(21,1);
M_.param_names_tex = cell(21,1);
M_.param_names_long = cell(21,1);
M_.param_names(1) = {'gam'};
M_.param_names_tex(1) = {'{\gamma}'};
M_.param_names_long(1) = {'Risk aversion'};
M_.param_names(2) = {'gam_max'};
M_.param_names_tex(2) = {'{\gamma_{max}}'};
M_.param_names_long(2) = {'Upper bound on risk aversion'};
M_.param_names(3) = {'r_ann'};
M_.param_names_tex(3) = {'{r_ann}'};
M_.param_names_long(3) = {'Annual interest rate'};
M_.param_names(4) = {'g_bar'};
M_.param_names_tex(4) = {'{\overline{g}}'};
M_.param_names_long(4) = {'Quarterly trend growth rate'};
M_.param_names(5) = {'nu'};
M_.param_names_tex(5) = {'\nu'};
M_.param_names_long(5) = {'Frisch elasticity'};
M_.param_names(6) = {'sigma_a'};
M_.param_names_tex(6) = {'{\sigma_a}'};
M_.param_names_long(6) = {'Inverse elasticity of marginal utilization cost wrt rental rate'};
M_.param_names(7) = {'Psi_K'};
M_.param_names_tex(7) = {'{\Psi_K}'};
M_.param_names_long(7) = {'Investment adjustment cost parameter'};
M_.param_names(8) = {'I_Y'};
M_.param_names_tex(8) = {'{I_Y}'};
M_.param_names_long(8) = {'Investment-output ratio'};
M_.param_names(9) = {'K_Y'};
M_.param_names_tex(9) = {'{K_Y}'};
M_.param_names_long(9) = {'Capital-output ratio (quarterly)'};
M_.param_names(10) = {'labor_share'};
M_.param_names_tex(10) = {'(labor share)'};
M_.param_names_long(10) = {'Labor share'};
M_.param_names(11) = {'m'};
M_.param_names_tex(11) = {'{m}'};
M_.param_names_long(11) = {'Ratio of price dispersion to consumption dispersion'};
M_.param_names(12) = {'eta'};
M_.param_names_tex(12) = {'{\eta}'};
M_.param_names_long(12) = {'Shopping disutility'};
M_.param_names(13) = {'Psi'};
M_.param_names_tex(13) = {'{\Psi}'};
M_.param_names_long(13) = {'Matching utilization'};
M_.param_names(14) = {'rho_g'};
M_.param_names_tex(14) = {'{\rho_g}'};
M_.param_names_long(14) = {'persistence TFP growth shock'};
M_.param_names(15) = {'rho_Z'};
M_.param_names_tex(15) = {'{\rho_Z}'};
M_.param_names_long(15) = {'persistence TFP shock'};
M_.param_names(16) = {'rho_ZI'};
M_.param_names_tex(16) = {'{\rho_{ZI}}'};
M_.param_names_long(16) = {'persistence I-specific shock'};
M_.param_names(17) = {'rho_N'};
M_.param_names_tex(17) = {'{\rho_N}'};
M_.param_names_long(17) = {'persistence labor supply shock'};
M_.param_names(18) = {'rho_D'};
M_.param_names_tex(18) = {'{\rho_D}'};
M_.param_names_long(18) = {'persistence shopping effort shock'};
M_.param_names(19) = {'rho_h'};
M_.param_names_tex(19) = {'{\rho_h}'};
M_.param_names_long(19) = {'persistence utilization depreciation shock'};
M_.param_names(20) = {'p_I_ss'};
M_.param_names_tex(20) = {'p\_I\_ss'};
M_.param_names_long(20) = {'p_I_ss'};
M_.param_names(21) = {'N_ss'};
M_.param_names_tex(21) = {'N\_ss'};
M_.param_names_long(21) = {'N_ss'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 6;
M_.endo_nbr = 52;
M_.param_nbr = 21;
M_.orig_endo_nbr = 52;
M_.aux_vars = [];
options_.varobs = cell(5, 1);
options_.varobs(1)  = {'I_obs'};
options_.varobs(2)  = {'Y_obs'};
options_.varobs(3)  = {'Y_N_obs'};
options_.varobs(4)  = {'p_I_obs'};
options_.varobs(5)  = {'util_obs'};
options_.varobs_id = [ 44 45 46 47 51  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(6, 6);
M_.Correlation_matrix = eye(6, 6);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 52;
M_.eq_nbr = 52;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 19 0;
 0 20 0;
 0 21 0;
 0 22 0;
 1 23 0;
 2 24 0;
 0 25 0;
 0 26 0;
 0 27 0;
 3 28 0;
 0 29 0;
 4 30 0;
 5 31 0;
 6 32 0;
 7 33 0;
 0 34 71;
 0 35 72;
 0 36 0;
 0 37 73;
 0 38 74;
 0 39 75;
 0 40 76;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 77;
 0 47 0;
 0 48 78;
 0 49 0;
 8 50 79;
 9 51 0;
 10 52 0;
 11 53 0;
 12 54 0;
 13 55 0;
 14 56 0;
 15 57 0;
 16 58 0;
 17 59 0;
 18 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;]';
M_.nstatic = 26;
M_.nfwrd   = 8;
M_.npred   = 17;
M_.nboth   = 1;
M_.nsfwrd   = 9;
M_.nspred   = 18;
M_.ndynamic   = 26;
M_.dynamic_tmp_nbr = [38; 9; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Labor leisure' ;
  2 , 'name' , 'Shopping:C' ;
  3 , 'name' , 'Shopping:I' ;
  4 , 'name' , 'Composite utility term' ;
  5 , 'name' , 'Tobins Q' ;
  6 , 'name' , 'Euler equation: C' ;
  7 , 'name' , 'Euler equation: I' ;
  8 , 'name' , 'Utilization: C' ;
  9 , 'name' , 'Utilization: I' ;
  10 , 'name' , 'Depreciation rate: C' ;
  11 , 'name' , 'Depreciation rate: I' ;
  12 , 'name' , 'Depreciation rate derivative: C' ;
  13 , 'name' , 'Depreciation rate derivative: I' ;
  14 , 'name' , 'Consumption production' ;
  15 , 'name' , 'Investment production' ;
  16 , 'name' , 'Capital law of motion' ;
  17 , 'name' , 'Labor demand:C' ;
  18 , 'name' , 'Labor demand:I' ;
  19 , 'name' , 'Capital demand:C' ;
  20 , 'name' , 'Capital demand:I' ;
  21 , 'name' , 'Labor composition' ;
  22 , 'name' , 'Capital composition' ;
  23 , 'name' , 'Shopping composition' ;
  24 , 'name' , 'Output (base-year prices)' ;
  25 , 'name' , 'Capacity utilization' ;
  26 , 'name' , 'exogenous labor-augmenting growth process' ;
  27 , 'name' , 'Stationary TFP process' ;
  28 , 'name' , 'Independent component of I-specific tech' ;
  29 , 'name' , 'Investment-specific TFP process' ;
  30 , 'name' , 'Labor supply process' ;
  31 , 'name' , 'Shopping effort process' ;
  32 , 'name' , ' Cost of varying capital utilization process' ;
  33 , 'name' , 'Definition log output' ;
  34 , 'name' , 'Definition log consumption' ;
  35 , 'name' , 'Definition log investment' ;
  36 , 'name' , 'Definition log hours' ;
  37 , 'name' , 'Definition log labor productivity' ;
  38 , 'name' , 'log_NI' ;
  39 , 'name' , 'log_Y_N' ;
  40 , 'name' , 'Definition log shopping effort' ;
  41 , 'name' , 'Definition of log relative investment  price' ;
  42 , 'name' , 'Definition of log capacity utilization' ;
  43 , 'name' , 'C_obs' ;
  44 , 'name' , 'I_obs' ;
  45 , 'name' , 'Y_obs' ;
  46 , 'name' , 'Y_N_obs' ;
  47 , 'name' , 'p_I_obs' ;
  48 , 'name' , 'N_obs' ;
  49 , 'name' , 'NC_obs' ;
  50 , 'name' , 'NI_obs' ;
  51 , 'name' , 'util_obs' ;
  52 , 'name' , 'D_obs' ;
};
M_.mapping.Y.eqidx = [24 25 33 ];
M_.mapping.C.eqidx = [2 4 14 17 19 24 25 34 ];
M_.mapping.I.eqidx = [3 15 16 18 20 24 25 35 ];
M_.mapping.K.eqidx = [22 ];
M_.mapping.K_C.eqidx = [14 16 19 22 ];
M_.mapping.K_I.eqidx = [15 16 20 22 ];
M_.mapping.N.eqidx = [1 4 21 36 ];
M_.mapping.N_C.eqidx = [14 17 21 37 ];
M_.mapping.N_I.eqidx = [15 18 21 38 ];
M_.mapping.Z_C.eqidx = [14 27 29 ];
M_.mapping.u_ZI.eqidx = [28 29 ];
M_.mapping.Z_I.eqidx = [15 28 29 ];
M_.mapping.theta_N.eqidx = [1 4 30 ];
M_.mapping.theta_D.eqidx = [2 3 4 31 ];
M_.mapping.theta_h.eqidx = [10 11 12 13 32 ];
M_.mapping.R_C.eqidx = [6 8 19 ];
M_.mapping.R_I.eqidx = [7 9 20 ];
M_.mapping.W.eqidx = [1 17 18 ];
M_.mapping.h_C.eqidx = [6 10 12 14 19 25 ];
M_.mapping.h_I.eqidx = [7 11 13 15 20 25 ];
M_.mapping.delta_C.eqidx = [6 10 16 ];
M_.mapping.delta_I.eqidx = [7 11 16 ];
M_.mapping.delta_C_pr.eqidx = [8 12 ];
M_.mapping.delta_I_pr.eqidx = [9 13 ];
M_.mapping.D.eqidx = [2 3 4 23 40 ];
M_.mapping.D_C.eqidx = [2 14 23 25 ];
M_.mapping.D_I.eqidx = [3 15 23 25 ];
M_.mapping.Gam.eqidx = [4 6 7 ];
M_.mapping.p_I.eqidx = [3 5 18 20 41 ];
M_.mapping.Q.eqidx = [5 6 7 8 9 ];
M_.mapping.util.eqidx = [25 42 ];
M_.mapping.g.eqidx = [6 7 14 15 16 19 20 26 43 44 45 46 ];
M_.mapping.log_Y.eqidx = [33 39 45 ];
M_.mapping.log_C.eqidx = [34 43 ];
M_.mapping.log_I.eqidx = [35 44 ];
M_.mapping.log_N.eqidx = [36 39 48 ];
M_.mapping.log_NC.eqidx = [37 49 ];
M_.mapping.log_NI.eqidx = [38 50 ];
M_.mapping.log_Y_N.eqidx = [39 46 ];
M_.mapping.log_D.eqidx = [40 52 ];
M_.mapping.log_p_I.eqidx = [41 47 ];
M_.mapping.log_util.eqidx = [42 51 ];
M_.mapping.C_obs.eqidx = [43 ];
M_.mapping.I_obs.eqidx = [44 ];
M_.mapping.Y_obs.eqidx = [45 ];
M_.mapping.Y_N_obs.eqidx = [46 ];
M_.mapping.p_I_obs.eqidx = [47 ];
M_.mapping.N_obs.eqidx = [48 ];
M_.mapping.NC_obs.eqidx = [49 ];
M_.mapping.NI_obs.eqidx = [50 ];
M_.mapping.util_obs.eqidx = [51 ];
M_.mapping.D_obs.eqidx = [52 ];
M_.mapping.e_g.eqidx = [26 ];
M_.mapping.e_Z.eqidx = [27 ];
M_.mapping.e_ZI.eqidx = [28 ];
M_.mapping.e_N.eqidx = [30 ];
M_.mapping.e_D.eqidx = [31 ];
M_.mapping.e_h.eqidx = [32 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [5 6 10 12 13 14 15 32 33 34 35 36 37 38 39 40 41 42 ];
M_.exo_names_orig_ord = [1:6];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(52, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(6, 1);
M_.params = NaN(21, 1);
M_.endo_trends = struct('deflator', cell(52, 1), 'log_deflator', cell(52, 1), 'growth_factor', cell(52, 1), 'log_growth_factor', cell(52, 1));
M_.NNZDerivatives = [190; -1; -1; ];
M_.static_tmp_nbr = [36; 8; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 2.0;
gam = M_.params(1);
M_.params(3) = 0.04;
r_ann = M_.params(3);
M_.params(4) = 0.00451;
g_bar = M_.params(4);
M_.params(2) = 0.25*log(1+M_.params(3))/M_.params(4);
gam_max = M_.params(2);
M_.params(5) = 0.72;
nu = M_.params(5);
M_.params(6) = 0.32;
sigma_a = M_.params(6);
M_.params(8) = 0.20;
I_Y = M_.params(8);
M_.params(9) = 11;
K_Y = M_.params(9);
M_.params(10) = 0.67;
labor_share = M_.params(10);
M_.params(11) = 0.286;
m = M_.params(11);
M_.params(12) = 0.20;
eta = M_.params(12);
M_.params(13) = 0.81;
Psi = M_.params(13);
theta = 1/0.1735;
M_.params(20) = 1.0;
p_I_ss = M_.params(20);
M_.params(21) = 0.30;
N_ss = M_.params(21);
M_.params(14) = 0.2;
rho_g = M_.params(14);
M_.params(15) = 0.9;
rho_Z = M_.params(15);
M_.params(16) = 0.9;
rho_ZI = M_.params(16);
M_.params(17) = 0.9;
rho_N = M_.params(17);
M_.params(18) = 0.9;
rho_D = M_.params(18);
M_.params(19) = 0.9;
rho_h = M_.params(19);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 5.184e-05;
M_.Sigma_e(2, 2) = 5.184e-05;
M_.Sigma_e(3, 3) = 5.184e-05;
M_.Sigma_e(4, 4) = 5.184e-05;
M_.Sigma_e(5, 5) = 5.184e-05;
M_.Sigma_e(6, 6) = 5.184e-05;
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 1, 1.5, 1.0, M_.params(2), 1, 1.5, 0.25, 1.0, M_.params(2), NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, 0.32, 0.0, 10, 2, 0.32, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 0.20, 0.00, 10.0, 2, 0.2, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 0.1, 0.0001, 0.9, 1, 0.1, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.95, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.95, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.6, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.9, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, 0.6, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.01, 0.00001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.01, 0.00001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.01, 0.0001, 0.4, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.01, 0.0001, 0.4, 4, 0.01, 0.1, NaN, NaN, NaN ];
options_.TeX=1;
options_.TeX = true;
options_.lik_init = 2;
options_.mh_drop = 0.3;
options_.mh_init_scale = 0.0004;
options_.mh_jscale = 0.0015;
options_.mh_nblck = 2;
options_.mh_replic = 100000;
options_.mode_check.status = true;
options_.mode_compute = 4;
options_.presample = 0;
options_.prior_trunc = 0;
options_.MCMC_jumping_covariance = 'prior_variance';
options_.datafile = 'observables_fd';
options_.optim_opt = '''MaxIter'',200';
options_.order = 1;
var_list_ = {'Y_obs';'Y_N_obs';'I_obs';'p_I_obs';'C_obs';'N_obs';'NC_obs';'NI_obs';'util_obs'};
oo_recursive_=dynare_estimation(var_list_);
write_latex_parameter_table;
write_latex_definitions;
write_latex_prior_table;
collect_latex_files;
options_.irf = 100;
options_.nofunctions = true;
options_.order = 1;
options_.periods = 0;
options_.conditional_variance_decomposition = [1;4;8;40;];
var_list_ = {'Y_obs';'Y_N_obs';'I_obs';'p_I_obs';'C_obs';'N_obs';'NC_obs';'NI_obs';'util_obs';'D_obs';'log_Y';'log_Y_N';'log_I';'log_p_I';'log_C';'log_N';'log_NC';'log_NI';'log_util';'log_D'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'BRS_growth_util_shock_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_growth_util_shock_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_growth_util_shock_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_growth_util_shock_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_growth_util_shock_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_growth_util_shock_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_growth_util_shock_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
