%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'BRS_sectoral_wo_gmf';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(13,1);
M_.exo_names_tex = cell(13,1);
M_.exo_names_long = cell(13,1);
M_.exo_names(1) = {'e_g'};
M_.exo_names_tex(1) = {'{e_g}'};
M_.exo_names_long(1) = {'Labor-augmenting-technology growth shock'};
M_.exo_names(2) = {'e_g_news'};
M_.exo_names_tex(2) = {'{e_{g,-4}}'};
M_.exo_names_long(2) = {'Labor-augmenting-technology growth shock: news'};
M_.exo_names(3) = {'e_Z'};
M_.exo_names_tex(3) = {'{e_Z}'};
M_.exo_names_long(3) = {'TFP shock'};
M_.exo_names(4) = {'e_Z_news'};
M_.exo_names_tex(4) = {'{e_{Z,-4}}'};
M_.exo_names_long(4) = {'TFP shock: news'};
M_.exo_names(5) = {'e_ZI'};
M_.exo_names_tex(5) = {'{e_{ZI}}'};
M_.exo_names_long(5) = {'Investment-specific tech shock'};
M_.exo_names(6) = {'e_ZI_news'};
M_.exo_names_tex(6) = {'{e_{ZI,-4}}'};
M_.exo_names_long(6) = {'Investment-specific tech shock: news'};
M_.exo_names(7) = {'e_N'};
M_.exo_names_tex(7) = {'{e_N}'};
M_.exo_names_long(7) = {'Labor supply shock'};
M_.exo_names(8) = {'e_b'};
M_.exo_names_tex(8) = {'{e_b}'};
M_.exo_names_long(8) = {'Discount factor shock'};
M_.exo_names(9) = {'e_b_news'};
M_.exo_names_tex(9) = {'{e_{b,-4}}'};
M_.exo_names_long(9) = {'Discount factor shock'};
M_.exo_names(10) = {'e_muC'};
M_.exo_names_tex(10) = {'{e_{muC}}'};
M_.exo_names_long(10) = {'Wage markup shock: C'};
M_.exo_names(11) = {'e_muC_news'};
M_.exo_names_tex(11) = {'{e_{muC,-4}}'};
M_.exo_names_long(11) = {'Wage markup shock: C: news'};
M_.exo_names(12) = {'e_muI'};
M_.exo_names_tex(12) = {'{e_{muI}}'};
M_.exo_names_long(12) = {'Wage markup shock: I'};
M_.exo_names(13) = {'e_muI_news'};
M_.exo_names_tex(13) = {'{e_{muI,-4}}'};
M_.exo_names_long(13) = {'Wage markup shock: I: news'};
M_.endo_names = cell(114,1);
M_.endo_names_tex = cell(114,1);
M_.endo_names_long = cell(114,1);
M_.endo_names(1) = {'Y'};
M_.endo_names_tex(1) = {'{Y}'};
M_.endo_names_long(1) = {'output'};
M_.endo_names(2) = {'C'};
M_.endo_names_tex(2) = {'{C}'};
M_.endo_names_long(2) = {'consumption'};
M_.endo_names(3) = {'Y_mc'};
M_.endo_names_tex(3) = {'{Y_{mc}}'};
M_.endo_names_long(3) = {'consumption non-durable goods'};
M_.endo_names(4) = {'Y_sc'};
M_.endo_names_tex(4) = {'Y_{sc}}'};
M_.endo_names_long(4) = {'consumption services'};
M_.endo_names(5) = {'I'};
M_.endo_names_tex(5) = {'{I}'};
M_.endo_names_long(5) = {'investment'};
M_.endo_names(6) = {'I_mc'};
M_.endo_names_tex(6) = {'{I_C}'};
M_.endo_names_long(6) = {'investment:mc'};
M_.endo_names(7) = {'I_sc'};
M_.endo_names_tex(7) = {'{I_C}'};
M_.endo_names_long(7) = {'investment:sc'};
M_.endo_names(8) = {'I_I'};
M_.endo_names_tex(8) = {'{I_I}'};
M_.endo_names_long(8) = {'investment:I'};
M_.endo_names(9) = {'K'};
M_.endo_names_tex(9) = {'{K}'};
M_.endo_names_long(9) = {'Capital'};
M_.endo_names(10) = {'K_mc'};
M_.endo_names_tex(10) = {'{K_{mc}}'};
M_.endo_names_long(10) = {'Capital:mc'};
M_.endo_names(11) = {'K_sc'};
M_.endo_names_tex(11) = {'{K_{sc}}'};
M_.endo_names_long(11) = {'Capital:sc'};
M_.endo_names(12) = {'K_I'};
M_.endo_names_tex(12) = {'{K_I}'};
M_.endo_names_long(12) = {'Capital:I'};
M_.endo_names(13) = {'N'};
M_.endo_names_tex(13) = {'{N}'};
M_.endo_names_long(13) = {'Hours'};
M_.endo_names(14) = {'N_mc'};
M_.endo_names_tex(14) = {'{N_{mc}}'};
M_.endo_names_long(14) = {'Hours:mc'};
M_.endo_names(15) = {'N_sc'};
M_.endo_names_tex(15) = {'{N_{sc}}'};
M_.endo_names_long(15) = {'Hours:sc'};
M_.endo_names(16) = {'N_C'};
M_.endo_names_tex(16) = {'{N_C}'};
M_.endo_names_long(16) = {'Hours:C'};
M_.endo_names(17) = {'N_I'};
M_.endo_names_tex(17) = {'{N_I}'};
M_.endo_names_long(17) = {'Hours:I'};
M_.endo_names(18) = {'N_comp'};
M_.endo_names_tex(18) = {'{N}'};
M_.endo_names_long(18) = {'Labor CES aggregate'};
M_.endo_names(19) = {'Z_C'};
M_.endo_names_tex(19) = {'{Z_{C}}'};
M_.endo_names_long(19) = {'Tech:mc'};
M_.endo_names(20) = {'u_ZI'};
M_.endo_names_tex(20) = {'u\_ZI'};
M_.endo_names_long(20) = {'u_ZI'};
M_.endo_names(21) = {'Z_I'};
M_.endo_names_tex(21) = {'{Z_I}'};
M_.endo_names_long(21) = {'Tech:I'};
M_.endo_names(22) = {'theta_N'};
M_.endo_names_tex(22) = {'{\theta_N}'};
M_.endo_names_long(22) = {'Labor disutility'};
M_.endo_names(23) = {'theta_b'};
M_.endo_names_tex(23) = {'{\theta_b}'};
M_.endo_names_long(23) = {'Discount factor shock'};
M_.endo_names(24) = {'mu_C'};
M_.endo_names_tex(24) = {'{\mu_C}'};
M_.endo_names_long(24) = {'mu_C'};
M_.endo_names(25) = {'mu_I'};
M_.endo_names_tex(25) = {'\mu_I}'};
M_.endo_names_long(25) = {'mu_I'};
M_.endo_names(26) = {'R_mc'};
M_.endo_names_tex(26) = {'{R_{mc}}'};
M_.endo_names_long(26) = {'Capital rental rate:mc'};
M_.endo_names(27) = {'R_sc'};
M_.endo_names_tex(27) = {'{R_{sc}}'};
M_.endo_names_long(27) = {'Capital rental rate:sc'};
M_.endo_names(28) = {'R_I'};
M_.endo_names_tex(28) = {'{R_I}'};
M_.endo_names_long(28) = {'Capital rental rate:I'};
M_.endo_names(29) = {'W_C'};
M_.endo_names_tex(29) = {'{W_C}'};
M_.endo_names_long(29) = {'Real wage:C'};
M_.endo_names(30) = {'W_I'};
M_.endo_names_tex(30) = {'{W_I}'};
M_.endo_names_long(30) = {'Real wage:I'};
M_.endo_names(31) = {'W'};
M_.endo_names_tex(31) = {'{W}'};
M_.endo_names_long(31) = {'Real wage'};
M_.endo_names(32) = {'h_mc'};
M_.endo_names_tex(32) = {'{h_mc}'};
M_.endo_names_long(32) = {'Capital utilization rate:mc'};
M_.endo_names(33) = {'h_sc'};
M_.endo_names_tex(33) = {'{h_sc}'};
M_.endo_names_long(33) = {'Capital utilization rate:sc'};
M_.endo_names(34) = {'h_I'};
M_.endo_names_tex(34) = {'{h_I}'};
M_.endo_names_long(34) = {'Capital utilization rate:I'};
M_.endo_names(35) = {'delta_mc'};
M_.endo_names_tex(35) = {'{\delta_{mc}}'};
M_.endo_names_long(35) = {'Capital depreciation rate:mc'};
M_.endo_names(36) = {'delta_sc'};
M_.endo_names_tex(36) = {'{\delta_{sc}}'};
M_.endo_names_long(36) = {'Capital depreciation rate:sc'};
M_.endo_names(37) = {'delta_I'};
M_.endo_names_tex(37) = {'{\delta_I}'};
M_.endo_names_long(37) = {'Capital depreciation rate:I'};
M_.endo_names(38) = {'delta_mc_pr'};
M_.endo_names_tex(38) = {'{\delta_{mc,pr}'};
M_.endo_names_long(38) = {'Capital depreciation rate derivative:mc'};
M_.endo_names(39) = {'delta_sc_pr'};
M_.endo_names_tex(39) = {'{\delta_{sc,pr}}'};
M_.endo_names_long(39) = {'Capital depreciation rate derivative:sc'};
M_.endo_names(40) = {'delta_I_pr'};
M_.endo_names_tex(40) = {'{\delta_{I,pr}}'};
M_.endo_names_long(40) = {'Capital depreciation rate derivative:I'};
M_.endo_names(41) = {'Smc'};
M_.endo_names_tex(41) = {'S'};
M_.endo_names_long(41) = {'Investment adjustment cost:mc'};
M_.endo_names(42) = {'Ssc'};
M_.endo_names_tex(42) = {'S'};
M_.endo_names_long(42) = {'Investment adjustment cost:sc'};
M_.endo_names(43) = {'Si'};
M_.endo_names_tex(43) = {'S'};
M_.endo_names_long(43) = {'Investment adjustment cost:I'};
M_.endo_names(44) = {'Smc_pr'};
M_.endo_names_tex(44) = {'S_pr'};
M_.endo_names_long(44) = {'Derivative investment adjustment cost:mc'};
M_.endo_names(45) = {'Ssc_pr'};
M_.endo_names_tex(45) = {'S_pr'};
M_.endo_names_long(45) = {'Derivative investment adjustment cost:sc'};
M_.endo_names(46) = {'Si_pr'};
M_.endo_names_tex(46) = {'S_pr'};
M_.endo_names_long(46) = {'Derivative investment adjustment cost:I'};
M_.endo_names(47) = {'Gam'};
M_.endo_names_tex(47) = {'{\Gamma}'};
M_.endo_names_long(47) = {'Composite utility term'};
M_.endo_names(48) = {'zeta'};
M_.endo_names_tex(48) = {'{\zeta}'};
M_.endo_names_long(48) = {'Wealth effects parameter'};
M_.endo_names(49) = {'p_mc'};
M_.endo_names_tex(49) = {'{p_{mc}}'};
M_.endo_names_long(49) = {'Relative non-durable price'};
M_.endo_names(50) = {'p_sc'};
M_.endo_names_tex(50) = {'{p_{sc}}'};
M_.endo_names_long(50) = {'Relative service price'};
M_.endo_names(51) = {'p_I'};
M_.endo_names_tex(51) = {'{p_I}'};
M_.endo_names_long(51) = {'Relative investment price'};
M_.endo_names(52) = {'lam'};
M_.endo_names_tex(52) = {'{\lambda}'};
M_.endo_names_long(52) = {'Marginal utility of wealth'};
M_.endo_names(53) = {'Q_mc'};
M_.endo_names_tex(53) = {'{Q}'};
M_.endo_names_long(53) = {'Relative price of capital:mc'};
M_.endo_names(54) = {'Q_sc'};
M_.endo_names_tex(54) = {'{Q}'};
M_.endo_names_long(54) = {'Relative price of capital:sc'};
M_.endo_names(55) = {'Q_I'};
M_.endo_names_tex(55) = {'{Q}'};
M_.endo_names_long(55) = {'Relative price of capital:I'};
M_.endo_names(56) = {'x_mc'};
M_.endo_names_tex(56) = {'{x}'};
M_.endo_names_long(56) = {'Growth rate of investment:mc'};
M_.endo_names(57) = {'x_sc'};
M_.endo_names_tex(57) = {'{x}'};
M_.endo_names_long(57) = {'Growth rate of investment:sc'};
M_.endo_names(58) = {'x_I'};
M_.endo_names_tex(58) = {'{x}'};
M_.endo_names_long(58) = {'Growth rate of investment:I'};
M_.endo_names(59) = {'log_SR'};
M_.endo_names_tex(59) = {'log\_SR'};
M_.endo_names_long(59) = {'Solow residual'};
M_.endo_names(60) = {'util'};
M_.endo_names_tex(60) = {'{util}'};
M_.endo_names_long(60) = {'Capacity utilization'};
M_.endo_names(61) = {'util_ND'};
M_.endo_names_tex(61) = {'{util_{ND}}'};
M_.endo_names_long(61) = {'Capacity utilization:ND'};
M_.endo_names(62) = {'util_D'};
M_.endo_names_tex(62) = {'{util_D}'};
M_.endo_names_long(62) = {'Capacity utilization:D'};
M_.endo_names(63) = {'g'};
M_.endo_names_tex(63) = {'{g}'};
M_.endo_names_long(63) = {'Growth rate of stochastic trend'};
M_.endo_names(64) = {'log_Y'};
M_.endo_names_tex(64) = {'log\_Y'};
M_.endo_names_long(64) = {'log_Y'};
M_.endo_names(65) = {'log_C'};
M_.endo_names_tex(65) = {'log\_C'};
M_.endo_names_long(65) = {'log_C'};
M_.endo_names(66) = {'log_I'};
M_.endo_names_tex(66) = {'log\_I'};
M_.endo_names_long(66) = {'log_I'};
M_.endo_names(67) = {'log_N'};
M_.endo_names_tex(67) = {'log\_N'};
M_.endo_names_long(67) = {'log_N'};
M_.endo_names(68) = {'log_NC'};
M_.endo_names_tex(68) = {'log\_NC'};
M_.endo_names_long(68) = {'log_NC'};
M_.endo_names(69) = {'log_NI'};
M_.endo_names_tex(69) = {'log\_NI'};
M_.endo_names_long(69) = {'log_NI'};
M_.endo_names(70) = {'log_K'};
M_.endo_names_tex(70) = {'log\_K'};
M_.endo_names_long(70) = {'log_K'};
M_.endo_names(71) = {'log_Y_N'};
M_.endo_names_tex(71) = {'log\_Y\_N'};
M_.endo_names_long(71) = {'log_Y_N'};
M_.endo_names(72) = {'log_p_I'};
M_.endo_names_tex(72) = {'log\_p\_I'};
M_.endo_names_long(72) = {'log_p_I'};
M_.endo_names(73) = {'log_util'};
M_.endo_names_tex(73) = {'log\_util'};
M_.endo_names_long(73) = {'log_util'};
M_.endo_names(74) = {'log_util_ND'};
M_.endo_names_tex(74) = {'log\_util\_ND'};
M_.endo_names_long(74) = {'log_util_ND'};
M_.endo_names(75) = {'log_util_D'};
M_.endo_names_tex(75) = {'log\_util\_D'};
M_.endo_names_long(75) = {'log_util_D'};
M_.endo_names(76) = {'log_W'};
M_.endo_names_tex(76) = {'log\_W'};
M_.endo_names_long(76) = {'log_W'};
M_.endo_names(77) = {'C_obs'};
M_.endo_names_tex(77) = {'C\_obs'};
M_.endo_names_long(77) = {'C_obs'};
M_.endo_names(78) = {'I_obs'};
M_.endo_names_tex(78) = {'I\_obs'};
M_.endo_names_long(78) = {'I_obs'};
M_.endo_names(79) = {'Y_obs'};
M_.endo_names_tex(79) = {'Y\_obs'};
M_.endo_names_long(79) = {'Y_obs'};
M_.endo_names(80) = {'Y_N_obs'};
M_.endo_names_tex(80) = {'Y\_N\_obs'};
M_.endo_names_long(80) = {'Y_N_obs'};
M_.endo_names(81) = {'p_I_obs'};
M_.endo_names_tex(81) = {'p\_I\_obs'};
M_.endo_names_long(81) = {'p_I_obs'};
M_.endo_names(82) = {'N_obs'};
M_.endo_names_tex(82) = {'N\_obs'};
M_.endo_names_long(82) = {'N_obs'};
M_.endo_names(83) = {'NC_obs'};
M_.endo_names_tex(83) = {'NC\_obs'};
M_.endo_names_long(83) = {'NC_obs'};
M_.endo_names(84) = {'NI_obs'};
M_.endo_names_tex(84) = {'NI\_obs'};
M_.endo_names_long(84) = {'NI_obs'};
M_.endo_names(85) = {'util_ND_obs'};
M_.endo_names_tex(85) = {'util\_ND\_obs'};
M_.endo_names_long(85) = {'util_ND_obs'};
M_.endo_names(86) = {'util_D_obs'};
M_.endo_names_tex(86) = {'util\_D\_obs'};
M_.endo_names_long(86) = {'util_D_obs'};
M_.endo_names(87) = {'w_obs'};
M_.endo_names_tex(87) = {'w\_obs'};
M_.endo_names_long(87) = {'w_obs'};
M_.endo_names(88) = {'util_obs'};
M_.endo_names_tex(88) = {'util\_obs'};
M_.endo_names_long(88) = {'util_obs'};
M_.endo_names(89) = {'K_obs'};
M_.endo_names_tex(89) = {'K\_obs'};
M_.endo_names_long(89) = {'K_obs'};
M_.endo_names(90) = {'SR_obs'};
M_.endo_names_tex(90) = {'SR\_obs'};
M_.endo_names_long(90) = {'SR_obs'};
M_.endo_names(91) = {'AUX_EXO_LAG_91_0'};
M_.endo_names_tex(91) = {'AUX\_EXO\_LAG\_91\_0'};
M_.endo_names_long(91) = {'AUX_EXO_LAG_91_0'};
M_.endo_names(92) = {'AUX_EXO_LAG_91_1'};
M_.endo_names_tex(92) = {'AUX\_EXO\_LAG\_91\_1'};
M_.endo_names_long(92) = {'AUX_EXO_LAG_91_1'};
M_.endo_names(93) = {'AUX_EXO_LAG_91_2'};
M_.endo_names_tex(93) = {'AUX\_EXO\_LAG\_91\_2'};
M_.endo_names_long(93) = {'AUX_EXO_LAG_91_2'};
M_.endo_names(94) = {'AUX_EXO_LAG_91_3'};
M_.endo_names_tex(94) = {'AUX\_EXO\_LAG\_91\_3'};
M_.endo_names_long(94) = {'AUX_EXO_LAG_91_3'};
M_.endo_names(95) = {'AUX_EXO_LAG_93_0'};
M_.endo_names_tex(95) = {'AUX\_EXO\_LAG\_93\_0'};
M_.endo_names_long(95) = {'AUX_EXO_LAG_93_0'};
M_.endo_names(96) = {'AUX_EXO_LAG_93_1'};
M_.endo_names_tex(96) = {'AUX\_EXO\_LAG\_93\_1'};
M_.endo_names_long(96) = {'AUX_EXO_LAG_93_1'};
M_.endo_names(97) = {'AUX_EXO_LAG_93_2'};
M_.endo_names_tex(97) = {'AUX\_EXO\_LAG\_93\_2'};
M_.endo_names_long(97) = {'AUX_EXO_LAG_93_2'};
M_.endo_names(98) = {'AUX_EXO_LAG_93_3'};
M_.endo_names_tex(98) = {'AUX\_EXO\_LAG\_93\_3'};
M_.endo_names_long(98) = {'AUX_EXO_LAG_93_3'};
M_.endo_names(99) = {'AUX_EXO_LAG_95_0'};
M_.endo_names_tex(99) = {'AUX\_EXO\_LAG\_95\_0'};
M_.endo_names_long(99) = {'AUX_EXO_LAG_95_0'};
M_.endo_names(100) = {'AUX_EXO_LAG_95_1'};
M_.endo_names_tex(100) = {'AUX\_EXO\_LAG\_95\_1'};
M_.endo_names_long(100) = {'AUX_EXO_LAG_95_1'};
M_.endo_names(101) = {'AUX_EXO_LAG_95_2'};
M_.endo_names_tex(101) = {'AUX\_EXO\_LAG\_95\_2'};
M_.endo_names_long(101) = {'AUX_EXO_LAG_95_2'};
M_.endo_names(102) = {'AUX_EXO_LAG_95_3'};
M_.endo_names_tex(102) = {'AUX\_EXO\_LAG\_95\_3'};
M_.endo_names_long(102) = {'AUX_EXO_LAG_95_3'};
M_.endo_names(103) = {'AUX_EXO_LAG_98_0'};
M_.endo_names_tex(103) = {'AUX\_EXO\_LAG\_98\_0'};
M_.endo_names_long(103) = {'AUX_EXO_LAG_98_0'};
M_.endo_names(104) = {'AUX_EXO_LAG_98_1'};
M_.endo_names_tex(104) = {'AUX\_EXO\_LAG\_98\_1'};
M_.endo_names_long(104) = {'AUX_EXO_LAG_98_1'};
M_.endo_names(105) = {'AUX_EXO_LAG_98_2'};
M_.endo_names_tex(105) = {'AUX\_EXO\_LAG\_98\_2'};
M_.endo_names_long(105) = {'AUX_EXO_LAG_98_2'};
M_.endo_names(106) = {'AUX_EXO_LAG_98_3'};
M_.endo_names_tex(106) = {'AUX\_EXO\_LAG\_98\_3'};
M_.endo_names_long(106) = {'AUX_EXO_LAG_98_3'};
M_.endo_names(107) = {'AUX_EXO_LAG_100_0'};
M_.endo_names_tex(107) = {'AUX\_EXO\_LAG\_100\_0'};
M_.endo_names_long(107) = {'AUX_EXO_LAG_100_0'};
M_.endo_names(108) = {'AUX_EXO_LAG_100_1'};
M_.endo_names_tex(108) = {'AUX\_EXO\_LAG\_100\_1'};
M_.endo_names_long(108) = {'AUX_EXO_LAG_100_1'};
M_.endo_names(109) = {'AUX_EXO_LAG_100_2'};
M_.endo_names_tex(109) = {'AUX\_EXO\_LAG\_100\_2'};
M_.endo_names_long(109) = {'AUX_EXO_LAG_100_2'};
M_.endo_names(110) = {'AUX_EXO_LAG_100_3'};
M_.endo_names_tex(110) = {'AUX\_EXO\_LAG\_100\_3'};
M_.endo_names_long(110) = {'AUX_EXO_LAG_100_3'};
M_.endo_names(111) = {'AUX_EXO_LAG_102_0'};
M_.endo_names_tex(111) = {'AUX\_EXO\_LAG\_102\_0'};
M_.endo_names_long(111) = {'AUX_EXO_LAG_102_0'};
M_.endo_names(112) = {'AUX_EXO_LAG_102_1'};
M_.endo_names_tex(112) = {'AUX\_EXO\_LAG\_102\_1'};
M_.endo_names_long(112) = {'AUX_EXO_LAG_102_1'};
M_.endo_names(113) = {'AUX_EXO_LAG_102_2'};
M_.endo_names_tex(113) = {'AUX\_EXO\_LAG\_102\_2'};
M_.endo_names_long(113) = {'AUX_EXO_LAG_102_2'};
M_.endo_names(114) = {'AUX_EXO_LAG_102_3'};
M_.endo_names_tex(114) = {'AUX\_EXO\_LAG\_102\_3'};
M_.endo_names_long(114) = {'AUX_EXO_LAG_102_3'};
M_.endo_partitions = struct();
M_.param_names = cell(27,1);
M_.param_names_tex = cell(27,1);
M_.param_names_long = cell(27,1);
M_.param_names(1) = {'sigma'};
M_.param_names_tex(1) = {'{\sigma}'};
M_.param_names_long(1) = {'Risk aversion'};
M_.param_names(2) = {'beta'};
M_.param_names_tex(2) = {'{\beta}'};
M_.param_names_long(2) = {'Discount factor'};
M_.param_names(3) = {'g_bar'};
M_.param_names_tex(3) = {'{\overline{g}}'};
M_.param_names_long(3) = {'Quarterly trend growth rate'};
M_.param_names(4) = {'nu'};
M_.param_names_tex(4) = {'\nu'};
M_.param_names_long(4) = {'Frisch elasticity'};
M_.param_names(5) = {'gam'};
M_.param_names_tex(5) = {'\gamma'};
M_.param_names_long(5) = {'wealth effect on labor supply'};
M_.param_names(6) = {'xi'};
M_.param_names_tex(6) = {'\xi'};
M_.param_names_long(6) = {'elasticity of substitution between non-durables and services'};
M_.param_names(7) = {'omega_sc'};
M_.param_names_tex(7) = {'\omega_{sc}'};
M_.param_names_long(7) = {'Weight of services in aggregator'};
M_.param_names(8) = {'mu_ss'};
M_.param_names_tex(8) = {'\mu_{ss}'};
M_.param_names_long(8) = {'steady-state wage markup'};
M_.param_names(9) = {'sigma_ac'};
M_.param_names_tex(9) = {'{\sigma_{ac}}'};
M_.param_names_long(9) = {'Inverse elasticity of marginal utilization cost wrt rental rate:C'};
M_.param_names(10) = {'sigma_ai'};
M_.param_names_tex(10) = {'{\sigma_{ai}}'};
M_.param_names_long(10) = {'Inverse elasticity of marginal utilization cost wrt rental rate:I'};
M_.param_names(11) = {'Psi_C'};
M_.param_names_tex(11) = {'{\Psi_{C}}'};
M_.param_names_long(11) = {'Investment adjustment cost parameter:non-durable goods'};
M_.param_names(12) = {'Psi_I'};
M_.param_names_tex(12) = {'{\Psi_I}'};
M_.param_names_long(12) = {'Investment adjustment cost parameter:I'};
M_.param_names(13) = {'I_Y'};
M_.param_names_tex(13) = {'{I_Y}'};
M_.param_names_long(13) = {'Investment-output ratio'};
M_.param_names(14) = {'K_Y'};
M_.param_names_tex(14) = {'{K_Y}'};
M_.param_names_long(14) = {'Capital-output ratio (quarterly)'};
M_.param_names(15) = {'labor_share'};
M_.param_names_tex(15) = {'(labor share)'};
M_.param_names_long(15) = {'Labor share'};
M_.param_names(16) = {'nu_R'};
M_.param_names_tex(16) = {'{\nu_R}'};
M_.param_names_long(16) = {'Fixed cost share'};
M_.param_names(17) = {'ha'};
M_.param_names_tex(17) = {'{ha}'};
M_.param_names_long(17) = {'Habit persistence'};
M_.param_names(18) = {'theta'};
M_.param_names_tex(18) = {'{\theta}'};
M_.param_names_long(18) = {'Inverse intersectoral elasticity of labor supply'};
M_.param_names(19) = {'rho_g'};
M_.param_names_tex(19) = {'{\rho_g}'};
M_.param_names_long(19) = {'persistence TFP growth shock'};
M_.param_names(20) = {'rho_Z'};
M_.param_names_tex(20) = {'{\rho_Z}'};
M_.param_names_long(20) = {'persistence TFP shock'};
M_.param_names(21) = {'rho_ZI'};
M_.param_names_tex(21) = {'{\rho_{ZI}}'};
M_.param_names_long(21) = {'persistence I-specific shock'};
M_.param_names(22) = {'rho_N'};
M_.param_names_tex(22) = {'{\rho_N}'};
M_.param_names_long(22) = {'persistence labor supply shock'};
M_.param_names(23) = {'rho_b'};
M_.param_names_tex(23) = {'{\rho_b}'};
M_.param_names_long(23) = {'persistence discount factor shock'};
M_.param_names(24) = {'rho_muC'};
M_.param_names_tex(24) = {'{\rho_{muC}}'};
M_.param_names_long(24) = {'persistence wage markup shock:C'};
M_.param_names(25) = {'rho_muI'};
M_.param_names_tex(25) = {'{\rho_{muI}}'};
M_.param_names_long(25) = {'persistence wage markup shock:I'};
M_.param_names(26) = {'p_I_ss'};
M_.param_names_tex(26) = {'p\_I\_ss'};
M_.param_names_long(26) = {'p_I_ss'};
M_.param_names(27) = {'N_ss'};
M_.param_names_tex(27) = {'N\_ss'};
M_.param_names_long(27) = {'N_ss'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 13;
M_.endo_nbr = 114;
M_.param_nbr = 27;
M_.orig_endo_nbr = 90;
M_.aux_vars(1).endo_index = 91;
M_.aux_vars(1).type = 3;
M_.aux_vars(1).orig_index = 2;
M_.aux_vars(1).orig_lead_lag = 0;
M_.aux_vars(1).orig_expr = 'e_g_news';
M_.aux_vars(2).endo_index = 92;
M_.aux_vars(2).type = 3;
M_.aux_vars(2).orig_index = 2;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(2).orig_expr = 'AUX_EXO_LAG_91_0(-1)';
M_.aux_vars(3).endo_index = 93;
M_.aux_vars(3).type = 3;
M_.aux_vars(3).orig_index = 2;
M_.aux_vars(3).orig_lead_lag = -2;
M_.aux_vars(3).orig_expr = 'AUX_EXO_LAG_91_1(-1)';
M_.aux_vars(4).endo_index = 94;
M_.aux_vars(4).type = 3;
M_.aux_vars(4).orig_index = 2;
M_.aux_vars(4).orig_lead_lag = -3;
M_.aux_vars(4).orig_expr = 'AUX_EXO_LAG_91_2(-1)';
M_.aux_vars(5).endo_index = 95;
M_.aux_vars(5).type = 3;
M_.aux_vars(5).orig_index = 4;
M_.aux_vars(5).orig_lead_lag = 0;
M_.aux_vars(5).orig_expr = 'e_Z_news';
M_.aux_vars(6).endo_index = 96;
M_.aux_vars(6).type = 3;
M_.aux_vars(6).orig_index = 4;
M_.aux_vars(6).orig_lead_lag = -1;
M_.aux_vars(6).orig_expr = 'AUX_EXO_LAG_93_0(-1)';
M_.aux_vars(7).endo_index = 97;
M_.aux_vars(7).type = 3;
M_.aux_vars(7).orig_index = 4;
M_.aux_vars(7).orig_lead_lag = -2;
M_.aux_vars(7).orig_expr = 'AUX_EXO_LAG_93_1(-1)';
M_.aux_vars(8).endo_index = 98;
M_.aux_vars(8).type = 3;
M_.aux_vars(8).orig_index = 4;
M_.aux_vars(8).orig_lead_lag = -3;
M_.aux_vars(8).orig_expr = 'AUX_EXO_LAG_93_2(-1)';
M_.aux_vars(9).endo_index = 99;
M_.aux_vars(9).type = 3;
M_.aux_vars(9).orig_index = 6;
M_.aux_vars(9).orig_lead_lag = 0;
M_.aux_vars(9).orig_expr = 'e_ZI_news';
M_.aux_vars(10).endo_index = 100;
M_.aux_vars(10).type = 3;
M_.aux_vars(10).orig_index = 6;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(10).orig_expr = 'AUX_EXO_LAG_95_0(-1)';
M_.aux_vars(11).endo_index = 101;
M_.aux_vars(11).type = 3;
M_.aux_vars(11).orig_index = 6;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(11).orig_expr = 'AUX_EXO_LAG_95_1(-1)';
M_.aux_vars(12).endo_index = 102;
M_.aux_vars(12).type = 3;
M_.aux_vars(12).orig_index = 6;
M_.aux_vars(12).orig_lead_lag = -3;
M_.aux_vars(12).orig_expr = 'AUX_EXO_LAG_95_2(-1)';
M_.aux_vars(13).endo_index = 103;
M_.aux_vars(13).type = 3;
M_.aux_vars(13).orig_index = 9;
M_.aux_vars(13).orig_lead_lag = 0;
M_.aux_vars(13).orig_expr = 'e_b_news';
M_.aux_vars(14).endo_index = 104;
M_.aux_vars(14).type = 3;
M_.aux_vars(14).orig_index = 9;
M_.aux_vars(14).orig_lead_lag = -1;
M_.aux_vars(14).orig_expr = 'AUX_EXO_LAG_98_0(-1)';
M_.aux_vars(15).endo_index = 105;
M_.aux_vars(15).type = 3;
M_.aux_vars(15).orig_index = 9;
M_.aux_vars(15).orig_lead_lag = -2;
M_.aux_vars(15).orig_expr = 'AUX_EXO_LAG_98_1(-1)';
M_.aux_vars(16).endo_index = 106;
M_.aux_vars(16).type = 3;
M_.aux_vars(16).orig_index = 9;
M_.aux_vars(16).orig_lead_lag = -3;
M_.aux_vars(16).orig_expr = 'AUX_EXO_LAG_98_2(-1)';
M_.aux_vars(17).endo_index = 107;
M_.aux_vars(17).type = 3;
M_.aux_vars(17).orig_index = 11;
M_.aux_vars(17).orig_lead_lag = 0;
M_.aux_vars(17).orig_expr = 'e_muC_news';
M_.aux_vars(18).endo_index = 108;
M_.aux_vars(18).type = 3;
M_.aux_vars(18).orig_index = 11;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(18).orig_expr = 'AUX_EXO_LAG_100_0(-1)';
M_.aux_vars(19).endo_index = 109;
M_.aux_vars(19).type = 3;
M_.aux_vars(19).orig_index = 11;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(19).orig_expr = 'AUX_EXO_LAG_100_1(-1)';
M_.aux_vars(20).endo_index = 110;
M_.aux_vars(20).type = 3;
M_.aux_vars(20).orig_index = 11;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(20).orig_expr = 'AUX_EXO_LAG_100_2(-1)';
M_.aux_vars(21).endo_index = 111;
M_.aux_vars(21).type = 3;
M_.aux_vars(21).orig_index = 13;
M_.aux_vars(21).orig_lead_lag = 0;
M_.aux_vars(21).orig_expr = 'e_muI_news';
M_.aux_vars(22).endo_index = 112;
M_.aux_vars(22).type = 3;
M_.aux_vars(22).orig_index = 13;
M_.aux_vars(22).orig_lead_lag = -1;
M_.aux_vars(22).orig_expr = 'AUX_EXO_LAG_102_0(-1)';
M_.aux_vars(23).endo_index = 113;
M_.aux_vars(23).type = 3;
M_.aux_vars(23).orig_index = 13;
M_.aux_vars(23).orig_lead_lag = -2;
M_.aux_vars(23).orig_expr = 'AUX_EXO_LAG_102_1(-1)';
M_.aux_vars(24).endo_index = 114;
M_.aux_vars(24).type = 3;
M_.aux_vars(24).orig_index = 13;
M_.aux_vars(24).orig_lead_lag = -3;
M_.aux_vars(24).orig_expr = 'AUX_EXO_LAG_102_2(-1)';
options_.varobs = cell(7, 1);
options_.varobs(1)  = {'NC_obs'};
options_.varobs(2)  = {'NI_obs'};
options_.varobs(3)  = {'C_obs'};
options_.varobs(4)  = {'I_obs'};
options_.varobs(5)  = {'p_I_obs'};
options_.varobs(6)  = {'util_ND_obs'};
options_.varobs(7)  = {'util_D_obs'};
options_.varobs_id = [ 83 84 77 78 81 85 86  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(13, 13);
M_.Correlation_matrix = eye(13, 13);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 90;
M_.eq_nbr = 114;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 4;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 4;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 4;
M_.lead_lag_incidence = [
 0 54 0;
 1 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 2 59 0;
 3 60 0;
 4 61 0;
 0 62 0;
 5 63 0;
 6 64 0;
 7 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 8 72 0;
 0 73 0;
 9 74 0;
 10 75 0;
 11 76 0;
 12 77 0;
 13 78 0;
 0 79 168;
 0 80 169;
 0 81 170;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 171;
 0 86 172;
 0 87 173;
 0 88 174;
 0 89 175;
 0 90 176;
 0 91 0;
 0 92 0;
 0 93 0;
 0 94 0;
 0 95 0;
 0 96 0;
 0 97 177;
 0 98 178;
 0 99 179;
 0 100 0;
 14 101 0;
 0 102 0;
 0 103 0;
 0 104 0;
 0 105 180;
 0 106 181;
 0 107 182;
 0 108 183;
 0 109 184;
 0 110 185;
 0 111 186;
 0 112 0;
 0 113 0;
 0 114 0;
 0 115 0;
 15 116 187;
 16 117 0;
 17 118 0;
 18 119 0;
 19 120 0;
 20 121 0;
 21 122 0;
 22 123 0;
 23 124 0;
 24 125 0;
 25 126 0;
 26 127 0;
 27 128 0;
 28 129 0;
 0 130 0;
 0 131 0;
 0 132 0;
 0 133 0;
 0 134 0;
 0 135 0;
 0 136 0;
 0 137 0;
 0 138 0;
 0 139 0;
 0 140 0;
 0 141 0;
 29 142 0;
 0 143 0;
 30 144 0;
 31 145 0;
 32 146 0;
 33 147 0;
 34 148 0;
 35 149 0;
 36 150 0;
 37 151 0;
 38 152 0;
 39 153 0;
 40 154 0;
 41 155 0;
 42 156 0;
 43 157 0;
 44 158 0;
 45 159 0;
 46 160 0;
 47 161 0;
 48 162 0;
 49 163 0;
 50 164 0;
 51 165 0;
 52 166 0;
 53 167 0;]';
M_.nstatic = 42;
M_.nfwrd   = 19;
M_.npred   = 52;
M_.nboth   = 1;
M_.nsfwrd   = 20;
M_.nspred   = 53;
M_.ndynamic   = 72;
M_.dynamic_tmp_nbr = [58; 17; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Labor composite' ;
  2 , 'name' , 'Labor leisure:C' ;
  3 , 'name' , 'Labor leisure:I' ;
  4 , 'name' , 'Marginal utility of wealth' ;
  5 , 'name' , 'Demand curve: mc' ;
  6 , 'name' , 'Demand curve: sc' ;
  7 , 'name' , 'Composite utility term' ;
  8 , 'name' , 'Law of motion of wealth effects variable' ;
  9 , 'name' , 'Consumption CES aggregator' ;
  10 , 'name' , 'Investment adjustment cost function:mc' ;
  11 , 'name' , 'Investment adjustment cost function:mc' ;
  12 , 'name' , 'Investment adjustment cost function:I' ;
  13 , 'name' , 'Investment adjustment cost function: derivative mc' ;
  14 , 'name' , 'Investment adjustment cost function: derivative mc' ;
  15 , 'name' , 'Investment adjustment cost function: derivative I' ;
  16 , 'name' , 'Investment growth:mc' ;
  17 , 'name' , 'Investment growth:mc' ;
  18 , 'name' , 'Investment growth:I' ;
  19 , 'name' , 'Depreciation rate: mc' ;
  20 , 'name' , 'Depreciation rate: sc' ;
  21 , 'name' , 'Depreciation rate: I' ;
  22 , 'name' , 'Depreciation rate derivative: mc' ;
  23 , 'name' , 'Depreciation rate derivative: sc' ;
  24 , 'name' , 'Depreciation rate derivative: I' ;
  25 , 'name' , 'Tobins Q: mc' ;
  26 , 'name' , 'Tobins Q: sc' ;
  27 , 'name' , 'Tobins Q: I' ;
  28 , 'name' , 'Euler equation: mc' ;
  29 , 'name' , 'Euler equation: sc' ;
  30 , 'name' , 'Euler equation: I' ;
  31 , 'name' , 'Utilization: mc' ;
  32 , 'name' , 'Utilization: sc' ;
  33 , 'name' , 'Utilization: I' ;
  34 , 'name' , 'Non-durable goods production' ;
  35 , 'name' , 'Services production' ;
  36 , 'name' , 'Investment production' ;
  37 , 'name' , 'Capital law of motion:mc' ;
  38 , 'name' , 'Capital law of motion:sc' ;
  39 , 'name' , 'Capital law of motion:I' ;
  40 , 'name' , 'Labor demand:mc' ;
  41 , 'name' , 'Labor demand:sc' ;
  42 , 'name' , 'Labor demand:I' ;
  43 , 'name' , 'Capital demand:mc' ;
  44 , 'name' , 'Capital demand:sc' ;
  45 , 'name' , 'Capital demand:I' ;
  46 , 'name' , 'Labor composition' ;
  47 , 'name' , 'Labor composition: C' ;
  48 , 'name' , 'Capital composition' ;
  49 , 'name' , 'Investment composition' ;
  50 , 'name' , 'Aggregate wage' ;
  51 , 'name' , 'Output (base-year prices)' ;
  52 , 'name' , 'Capacity utilization' ;
  53 , 'name' , 'util_D' ;
  54 , 'name' , 'util' ;
  55 , 'name' , 'stochastic trend process' ;
  56 , 'name' , 'Stationary TFP process' ;
  57 , 'name' , 'Independent component of I-specific tech' ;
  58 , 'name' , 'Investment-specific TFP process' ;
  59 , 'name' , 'Labor supply process' ;
  60 , 'name' , 'Consumption preference process' ;
  61 , 'name' , 'Wage-markup process: C' ;
  62 , 'name' , 'Wage-markup process: I' ;
  63 , 'name' , 'Definition log output' ;
  64 , 'name' , 'Definition log consumption' ;
  65 , 'name' , 'Definition log investment' ;
  66 , 'name' , 'Definition log hours' ;
  67 , 'name' , 'log_NC' ;
  68 , 'name' , 'log_NI' ;
  69 , 'name' , 'log capital' ;
  70 , 'name' , 'Definition log labor productivity' ;
  71 , 'name' , 'Definition of log relative investment  price' ;
  72 , 'name' , 'Definition of log capacity utilization' ;
  73 , 'name' , 'log_util_ND' ;
  74 , 'name' , 'log_util_D' ;
  75 , 'name' , 'Definition of log wages' ;
  76 , 'name' , 'Definition of log Solow residual' ;
  77 , 'name' , 'C_obs' ;
  78 , 'name' , 'I_obs' ;
  79 , 'name' , 'Y_obs' ;
  80 , 'name' , 'Y_N_obs' ;
  81 , 'name' , 'K_obs' ;
  82 , 'name' , 'w_obs' ;
  83 , 'name' , 'SR_obs' ;
  84 , 'name' , 'p_I_obs' ;
  85 , 'name' , 'N_obs' ;
  86 , 'name' , 'NC_obs' ;
  87 , 'name' , 'NI_obs' ;
  88 , 'name' , 'util_ND_obs' ;
  89 , 'name' , 'util_D_obs' ;
  90 , 'name' , 'util_obs' ;
};
M_.mapping.Y.eqidx = [51 63 ];
M_.mapping.C.eqidx = [5 6 7 8 9 51 64 ];
M_.mapping.Y_mc.eqidx = [5 9 34 40 43 54 ];
M_.mapping.Y_sc.eqidx = [6 9 35 41 44 ];
M_.mapping.I.eqidx = [36 42 45 49 51 54 65 ];
M_.mapping.I_mc.eqidx = [16 37 49 ];
M_.mapping.I_sc.eqidx = [17 38 49 ];
M_.mapping.I_I.eqidx = [18 39 49 ];
M_.mapping.K.eqidx = [48 69 ];
M_.mapping.K_mc.eqidx = [34 37 43 48 52 ];
M_.mapping.K_sc.eqidx = [35 38 44 48 ];
M_.mapping.K_I.eqidx = [36 39 45 48 53 ];
M_.mapping.N.eqidx = [46 50 66 ];
M_.mapping.N_mc.eqidx = [34 40 46 47 52 ];
M_.mapping.N_sc.eqidx = [35 41 46 47 ];
M_.mapping.N_C.eqidx = [1 2 47 50 67 ];
M_.mapping.N_I.eqidx = [1 3 36 42 46 50 53 68 ];
M_.mapping.N_comp.eqidx = [1 2 3 7 ];
M_.mapping.Z_C.eqidx = [34 35 52 56 58 ];
M_.mapping.u_ZI.eqidx = [57 58 ];
M_.mapping.Z_I.eqidx = [36 53 57 58 ];
M_.mapping.theta_N.eqidx = [2 3 7 59 ];
M_.mapping.theta_b.eqidx = [25 26 27 28 29 30 60 ];
M_.mapping.mu_C.eqidx = [2 61 ];
M_.mapping.mu_I.eqidx = [3 62 ];
M_.mapping.R_mc.eqidx = [28 31 43 ];
M_.mapping.R_sc.eqidx = [29 32 44 ];
M_.mapping.R_I.eqidx = [30 33 45 ];
M_.mapping.W_C.eqidx = [2 40 41 50 ];
M_.mapping.W_I.eqidx = [3 42 50 ];
M_.mapping.W.eqidx = [50 75 ];
M_.mapping.h_mc.eqidx = [19 22 28 34 43 52 ];
M_.mapping.h_sc.eqidx = [20 23 29 35 44 ];
M_.mapping.h_I.eqidx = [21 24 30 36 45 53 ];
M_.mapping.delta_mc.eqidx = [19 28 37 ];
M_.mapping.delta_sc.eqidx = [20 29 38 ];
M_.mapping.delta_I.eqidx = [21 30 39 ];
M_.mapping.delta_mc_pr.eqidx = [22 31 ];
M_.mapping.delta_sc_pr.eqidx = [23 32 ];
M_.mapping.delta_I_pr.eqidx = [24 33 ];
M_.mapping.Smc.eqidx = [10 25 37 ];
M_.mapping.Ssc.eqidx = [11 26 38 ];
M_.mapping.Si.eqidx = [12 27 39 ];
M_.mapping.Smc_pr.eqidx = [13 25 ];
M_.mapping.Ssc_pr.eqidx = [14 26 ];
M_.mapping.Si_pr.eqidx = [15 27 ];
M_.mapping.Gam.eqidx = [4 7 ];
M_.mapping.zeta.eqidx = [2 3 7 8 ];
M_.mapping.p_mc.eqidx = [5 40 43 ];
M_.mapping.p_sc.eqidx = [6 41 44 ];
M_.mapping.p_I.eqidx = [25 26 27 42 45 71 ];
M_.mapping.lam.eqidx = [4 25 26 27 28 29 30 ];
M_.mapping.Q_mc.eqidx = [25 28 31 ];
M_.mapping.Q_sc.eqidx = [26 29 32 ];
M_.mapping.Q_I.eqidx = [27 30 33 ];
M_.mapping.x_mc.eqidx = [10 13 16 25 ];
M_.mapping.x_sc.eqidx = [11 14 17 26 ];
M_.mapping.x_I.eqidx = [12 15 18 27 ];
M_.mapping.log_SR.eqidx = [76 ];
M_.mapping.util.eqidx = [54 72 ];
M_.mapping.util_ND.eqidx = [52 54 73 ];
M_.mapping.util_D.eqidx = [53 54 74 ];
M_.mapping.g.eqidx = [16 17 18 25 26 27 28 29 30 34 35 36 37 38 39 43 44 45 52 53 55 77 78 79 80 81 82 ];
M_.mapping.log_Y.eqidx = [63 70 76 79 ];
M_.mapping.log_C.eqidx = [64 77 ];
M_.mapping.log_I.eqidx = [65 78 ];
M_.mapping.log_N.eqidx = [66 70 76 85 ];
M_.mapping.log_NC.eqidx = [67 86 ];
M_.mapping.log_NI.eqidx = [68 87 ];
M_.mapping.log_K.eqidx = [69 76 81 ];
M_.mapping.log_Y_N.eqidx = [70 80 ];
M_.mapping.log_p_I.eqidx = [71 84 ];
M_.mapping.log_util.eqidx = [72 90 ];
M_.mapping.log_util_ND.eqidx = [73 88 ];
M_.mapping.log_util_D.eqidx = [74 89 ];
M_.mapping.log_W.eqidx = [75 82 ];
M_.mapping.C_obs.eqidx = [77 ];
M_.mapping.I_obs.eqidx = [78 ];
M_.mapping.Y_obs.eqidx = [79 83 ];
M_.mapping.Y_N_obs.eqidx = [80 ];
M_.mapping.p_I_obs.eqidx = [84 ];
M_.mapping.N_obs.eqidx = [83 85 ];
M_.mapping.NC_obs.eqidx = [86 ];
M_.mapping.NI_obs.eqidx = [87 ];
M_.mapping.util_ND_obs.eqidx = [88 ];
M_.mapping.util_D_obs.eqidx = [89 ];
M_.mapping.w_obs.eqidx = [82 ];
M_.mapping.util_obs.eqidx = [90 ];
M_.mapping.K_obs.eqidx = [81 83 ];
M_.mapping.SR_obs.eqidx = [83 ];
M_.mapping.e_g.eqidx = [55 ];
M_.mapping.e_g_news.eqidx = [55 ];
M_.mapping.e_Z.eqidx = [56 ];
M_.mapping.e_Z_news.eqidx = [56 ];
M_.mapping.e_ZI.eqidx = [57 ];
M_.mapping.e_ZI_news.eqidx = [57 ];
M_.mapping.e_N.eqidx = [59 ];
M_.mapping.e_b.eqidx = [60 ];
M_.mapping.e_b_news.eqidx = [60 ];
M_.mapping.e_muC.eqidx = [61 ];
M_.mapping.e_muC_news.eqidx = [61 ];
M_.mapping.e_muI.eqidx = [62 ];
M_.mapping.e_muI_news.eqidx = [62 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [2 6 7 8 10 11 12 19 21 22 23 24 25 48 63 64 65 66 67 68 69 70 71 72 73 74 75 76 89 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 ];
M_.exo_names_orig_ord = [1:13];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(114, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(13, 1);
M_.params = NaN(27, 1);
M_.endo_trends = struct('deflator', cell(114, 1), 'log_deflator', cell(114, 1), 'growth_factor', cell(114, 1), 'log_growth_factor', cell(114, 1));
M_.NNZDerivatives = [409; -1; -1; ];
M_.static_tmp_nbr = [57; 14; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 2.0;
sigma = M_.params(1);
M_.params(2) = 0.99;
beta = M_.params(2);
M_.params(3) = 0.0045;
g_bar = M_.params(3);
M_.params(4) = 0.72;
nu = M_.params(4);
M_.params(5) = 0.5;
gam = M_.params(5);
M_.params(17) = 0.1;
ha = M_.params(17);
M_.params(8) = 1.15;
mu_ss = M_.params(8);
M_.params(6) = 0.85;
xi = M_.params(6);
M_.params(7) = 0.65;
omega_sc = M_.params(7);
M_.params(9) = 0.32;
sigma_ac = M_.params(9);
M_.params(10) = 0.32;
sigma_ai = M_.params(10);
M_.params(11) = 1.5;
Psi_C = M_.params(11);
M_.params(12) = 1.5;
Psi_I = M_.params(12);
M_.params(13) = 0.20;
I_Y = M_.params(13);
M_.params(14) = 11;
K_Y = M_.params(14);
M_.params(15) = 0.67;
labor_share = M_.params(15);
M_.params(16) = 0.2;
nu_R = M_.params(16);
M_.params(18) = 0.5;
theta = M_.params(18);
M_.params(26) = 1.0;
p_I_ss = M_.params(26);
M_.params(27) = 0.30;
N_ss = M_.params(27);
M_.params(19) = 0.1;
rho_g = M_.params(19);
M_.params(20) = 0.9;
rho_Z = M_.params(20);
M_.params(21) = 0.9;
rho_ZI = M_.params(21);
M_.params(22) = 0.9;
rho_N = M_.params(22);
M_.params(23) = 0.9;
rho_b = M_.params(23);
M_.params(24) = 0.9;
rho_muC = M_.params(24);
M_.params(25) = 0.9;
rho_muI = M_.params(25);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 5.184e-05;
M_.Sigma_e(3, 3) = 5.184e-05;
M_.Sigma_e(5, 5) = 5.184e-05;
M_.Sigma_e(7, 7) = 5.184e-05;
M_.Sigma_e(8, 8) = 5.184e-05;
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 1, 1.5, 1.0, 4.0, 1, 1.5, 0.25, 1.0, 4.0, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.5, 0.0, 0.95, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, 0.72, 0.05, 2.0, 2, 0.72, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, 0.5, 0.0, 1.0, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, 0.85, 0.5, 2.0, 2, 0.85, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.20, 0.01, 0.5, 1, 0.2, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, 0.32, 0.0, 10, 4, 1, 1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, 0.32, 0.0, 10, 4, 1, 1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, 1.5, 0.0, 50, 2, 4, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 1.5, 0.0, 50, 2, 4, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.5, .00, 10, 2, 1, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, 0.1, 0.0001, 0.9, 1, 0.1, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.95, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.95, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 0.6, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.95, 0.01, 0.99999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, 0.95, 0.01, 0.99999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, 0.95, 0.01, 0.99999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.01, 0.00001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.01, 0.00001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.01, 0.00001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.01, 0.00001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, 0.01, 0.0001, 0.4, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, 0.01, 0.0001, 0.4, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 10, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 11, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 12, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 13, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
options_.TeX=1;
options_.TeX = true;
options_.lik_init = 2;
options_.mh_drop = 0.3;
options_.mh_init_scale = 0.0001;
options_.mh_jscale = 0.006;
options_.mh_nblck = 2;
options_.mh_replic = 150000;
options_.mode_check.status = true;
options_.mode_compute = 4;
options_.presample = 0;
options_.prior_trunc = 0;
options_.MCMC_jumping_covariance = 'prior_variance';
options_.datafile = 'observables_sectoral';
options_.optim_opt = '''MaxIter'',200';
options_.order = 1;
var_list_ = {'Y_obs';'Y_N_obs';'I_obs';'p_I_obs';'C_obs';'NC_obs';'NI_obs';'util_ND_obs';'util_D_obs';'w_obs'};
oo_recursive_=dynare_estimation(var_list_);
write_latex_parameter_table;
write_latex_definitions;
write_latex_prior_table;
generate_trace_plots(1);
collect_latex_files;
options_.irf = 0;
options_.nofunctions = true;
options_.order = 1;
options_.periods = 0;
var_list_ = {'Y_obs';'Y_N_obs';'SR_obs';'I_obs';'p_I_obs';'C_obs';'NC_obs';'NI_obs';'util_ND_obs';'util_D_obs';'w_obs'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'BRS_sectoral_wo_gmf_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_wo_gmf_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_wo_gmf_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_wo_gmf_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_wo_gmf_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_wo_gmf_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_wo_gmf_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
