%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'RBC';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(4,1);
M_.exo_names_tex = cell(4,1);
M_.exo_names_long = cell(4,1);
M_.exo_names(1) = {'e_g'};
M_.exo_names_tex(1) = {'{e_g}'};
M_.exo_names_long(1) = {'TFP shock'};
M_.exo_names(2) = {'e_Z'};
M_.exo_names_tex(2) = {'{e_Z}'};
M_.exo_names_long(2) = {'TFP shock'};
M_.exo_names(3) = {'e_ZI'};
M_.exo_names_tex(3) = {'{e_{ZI}}'};
M_.exo_names_long(3) = {'Investment-specific tech shock'};
M_.exo_names(4) = {'e_N'};
M_.exo_names_tex(4) = {'{e_N}'};
M_.exo_names_long(4) = {'Labor supply shock'};
M_.endo_names = cell(38,1);
M_.endo_names_tex = cell(38,1);
M_.endo_names_long = cell(38,1);
M_.endo_names(1) = {'Y'};
M_.endo_names_tex(1) = {'{Y}'};
M_.endo_names_long(1) = {'output'};
M_.endo_names(2) = {'C'};
M_.endo_names_tex(2) = {'{C}'};
M_.endo_names_long(2) = {'consumption'};
M_.endo_names(3) = {'I'};
M_.endo_names_tex(3) = {'{I}'};
M_.endo_names_long(3) = {'investment'};
M_.endo_names(4) = {'SR'};
M_.endo_names_tex(4) = {'{SR}'};
M_.endo_names_long(4) = {'aggregate share-weighted Solow residual'};
M_.endo_names(5) = {'K'};
M_.endo_names_tex(5) = {'{K}'};
M_.endo_names_long(5) = {'Capital'};
M_.endo_names(6) = {'K_C'};
M_.endo_names_tex(6) = {'{K_C}'};
M_.endo_names_long(6) = {'Capital:C'};
M_.endo_names(7) = {'K_I'};
M_.endo_names_tex(7) = {'{K_I}'};
M_.endo_names_long(7) = {'Capital:I'};
M_.endo_names(8) = {'N'};
M_.endo_names_tex(8) = {'{N}'};
M_.endo_names_long(8) = {'Hours'};
M_.endo_names(9) = {'N_C'};
M_.endo_names_tex(9) = {'{N_C}'};
M_.endo_names_long(9) = {'Hours:C'};
M_.endo_names(10) = {'N_I'};
M_.endo_names_tex(10) = {'{N_I}'};
M_.endo_names_long(10) = {'Hours:I'};
M_.endo_names(11) = {'Z_C'};
M_.endo_names_tex(11) = {'{Z_C}'};
M_.endo_names_long(11) = {'Tech:C'};
M_.endo_names(12) = {'u_ZI'};
M_.endo_names_tex(12) = {'u\_ZI'};
M_.endo_names_long(12) = {'u_ZI'};
M_.endo_names(13) = {'Z_I'};
M_.endo_names_tex(13) = {'{Z_I}'};
M_.endo_names_long(13) = {'Tech:I'};
M_.endo_names(14) = {'theta_N'};
M_.endo_names_tex(14) = {'{\theta_N}'};
M_.endo_names_long(14) = {'Labor disutility'};
M_.endo_names(15) = {'R_C'};
M_.endo_names_tex(15) = {'{R_C}'};
M_.endo_names_long(15) = {'Capital rental rate:C'};
M_.endo_names(16) = {'R_I'};
M_.endo_names_tex(16) = {'{R_I}'};
M_.endo_names_long(16) = {'Capital rental rate:I'};
M_.endo_names(17) = {'W'};
M_.endo_names_tex(17) = {'{W}'};
M_.endo_names_long(17) = {'Real wage'};
M_.endo_names(18) = {'Gam'};
M_.endo_names_tex(18) = {'{\Gamma}'};
M_.endo_names_long(18) = {'Composite utility term'};
M_.endo_names(19) = {'p_I'};
M_.endo_names_tex(19) = {'{p_I}'};
M_.endo_names_long(19) = {'Relative investment price'};
M_.endo_names(20) = {'g'};
M_.endo_names_tex(20) = {'{g}'};
M_.endo_names_long(20) = {'Output growth rate (labor-augmenting technology)'};
M_.endo_names(21) = {'log_Y'};
M_.endo_names_tex(21) = {'log\_Y'};
M_.endo_names_long(21) = {'log_Y'};
M_.endo_names(22) = {'log_C'};
M_.endo_names_tex(22) = {'log\_C'};
M_.endo_names_long(22) = {'log_C'};
M_.endo_names(23) = {'log_I'};
M_.endo_names_tex(23) = {'log\_I'};
M_.endo_names_long(23) = {'log_I'};
M_.endo_names(24) = {'log_N'};
M_.endo_names_tex(24) = {'log\_N'};
M_.endo_names_long(24) = {'log_N'};
M_.endo_names(25) = {'log_NC'};
M_.endo_names_tex(25) = {'log\_NC'};
M_.endo_names_long(25) = {'log_NC'};
M_.endo_names(26) = {'log_NI'};
M_.endo_names_tex(26) = {'log\_NI'};
M_.endo_names_long(26) = {'log_NI'};
M_.endo_names(27) = {'log_Y_N'};
M_.endo_names_tex(27) = {'log\_Y\_N'};
M_.endo_names_long(27) = {'log_Y_N'};
M_.endo_names(28) = {'log_SR'};
M_.endo_names_tex(28) = {'log\_SR'};
M_.endo_names_long(28) = {'log_SR'};
M_.endo_names(29) = {'log_p_I'};
M_.endo_names_tex(29) = {'log\_p\_I'};
M_.endo_names_long(29) = {'log_p_I'};
M_.endo_names(30) = {'C_obs'};
M_.endo_names_tex(30) = {'C\_obs'};
M_.endo_names_long(30) = {'C_obs'};
M_.endo_names(31) = {'I_obs'};
M_.endo_names_tex(31) = {'I\_obs'};
M_.endo_names_long(31) = {'I_obs'};
M_.endo_names(32) = {'Y_obs'};
M_.endo_names_tex(32) = {'Y\_obs'};
M_.endo_names_long(32) = {'Y_obs'};
M_.endo_names(33) = {'Y_N_obs'};
M_.endo_names_tex(33) = {'Y\_N\_obs'};
M_.endo_names_long(33) = {'Y_N_obs'};
M_.endo_names(34) = {'SR_obs'};
M_.endo_names_tex(34) = {'SR\_obs'};
M_.endo_names_long(34) = {'SR_obs'};
M_.endo_names(35) = {'p_I_obs'};
M_.endo_names_tex(35) = {'p\_I\_obs'};
M_.endo_names_long(35) = {'p_I_obs'};
M_.endo_names(36) = {'NC_obs'};
M_.endo_names_tex(36) = {'NC\_obs'};
M_.endo_names_long(36) = {'NC_obs'};
M_.endo_names(37) = {'NI_obs'};
M_.endo_names_tex(37) = {'NI\_obs'};
M_.endo_names_long(37) = {'NI_obs'};
M_.endo_names(38) = {'N_obs'};
M_.endo_names_tex(38) = {'N\_obs'};
M_.endo_names_long(38) = {'N_obs'};
M_.endo_partitions = struct();
M_.param_names = cell(13,1);
M_.param_names_tex = cell(13,1);
M_.param_names_long = cell(13,1);
M_.param_names(1) = {'sigma'};
M_.param_names_tex(1) = {'{\sigma}'};
M_.param_names_long(1) = {'Risk aversion'};
M_.param_names(2) = {'beta'};
M_.param_names_tex(2) = {'{\beta}'};
M_.param_names_long(2) = {'Discount factor'};
M_.param_names(3) = {'g_bar'};
M_.param_names_tex(3) = {'{\overline{g}}'};
M_.param_names_long(3) = {'Quarterly growth rate'};
M_.param_names(4) = {'nu'};
M_.param_names_tex(4) = {'(\nu)'};
M_.param_names_long(4) = {'Frisch elasticity'};
M_.param_names(5) = {'I_Y'};
M_.param_names_tex(5) = {'(I_Y)'};
M_.param_names_long(5) = {'Investment-output ratio'};
M_.param_names(6) = {'K_Y'};
M_.param_names_tex(6) = {'(K_Y)'};
M_.param_names_long(6) = {'Capital-output ratio (quarterly)'};
M_.param_names(7) = {'labor_share'};
M_.param_names_tex(7) = {'(labor share)'};
M_.param_names_long(7) = {'Labor share'};
M_.param_names(8) = {'rho_g'};
M_.param_names_tex(8) = {'{\rho_g}'};
M_.param_names_long(8) = {'persistence shock to labor-augmenting technology growth rate'};
M_.param_names(9) = {'rho_Z'};
M_.param_names_tex(9) = {'{\rho_Z}'};
M_.param_names_long(9) = {'persistence TFP shock'};
M_.param_names(10) = {'rho_ZI'};
M_.param_names_tex(10) = {'{\rho_{ZI}}'};
M_.param_names_long(10) = {'persistence I-specific shock'};
M_.param_names(11) = {'rho_N'};
M_.param_names_tex(11) = {'{\rho_N}'};
M_.param_names_long(11) = {'persistence labor supply shock'};
M_.param_names(12) = {'p_I_ss'};
M_.param_names_tex(12) = {'p\_I\_ss'};
M_.param_names_long(12) = {'p_I_ss'};
M_.param_names(13) = {'N_ss'};
M_.param_names_tex(13) = {'N\_ss'};
M_.param_names_long(13) = {'N_ss'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 38;
M_.param_nbr = 13;
M_.orig_endo_nbr = 38;
M_.aux_vars = [];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 38;
M_.eq_nbr = 38;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 16 0;
 0 17 0;
 0 18 0;
 0 19 0;
 0 20 0;
 1 21 0;
 2 22 0;
 0 23 0;
 0 24 0;
 0 25 0;
 3 26 0;
 0 27 0;
 4 28 0;
 5 29 0;
 0 30 54;
 0 31 55;
 0 32 0;
 0 33 56;
 0 34 57;
 6 35 58;
 7 36 0;
 8 37 0;
 9 38 0;
 10 39 0;
 11 40 0;
 12 41 0;
 13 42 0;
 14 43 0;
 15 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;]';
M_.nstatic = 19;
M_.nfwrd   = 4;
M_.npred   = 14;
M_.nboth   = 1;
M_.nsfwrd   = 5;
M_.nspred   = 15;
M_.ndynamic   = 19;
M_.dynamic_tmp_nbr = [27; 3; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Labor leisure' ;
  2 , 'name' , 'Composite utility term' ;
  3 , 'name' , 'Euler equation: C' ;
  4 , 'name' , 'Euler equation: I' ;
  5 , 'name' , 'Consumption production' ;
  6 , 'name' , 'Investment production' ;
  7 , 'name' , 'Capital law of motion' ;
  8 , 'name' , 'Labor demand:C' ;
  9 , 'name' , 'Capital demand:C' ;
  10 , 'name' , 'Labor demand:I' ;
  11 , 'name' , 'Capital demand:I' ;
  12 , 'name' , 'Labor composition' ;
  13 , 'name' , 'Capital composition' ;
  14 , 'name' , 'Output (base-year prices)' ;
  15 , 'name' , 'Solow residual' ;
  16 , 'name' , 'exogenous labor-augmenting growth process' ;
  17 , 'name' , 'Stationary TFP process' ;
  18 , 'name' , 'Independent component of I-specific tech' ;
  19 , 'name' , 'Investment-specific TFP process' ;
  20 , 'name' , 'Labor supply process' ;
  21 , 'name' , 'Definition log output' ;
  22 , 'name' , 'Definition log consumption' ;
  23 , 'name' , 'Definition log investment' ;
  24 , 'name' , 'Definition log hours' ;
  25 , 'name' , 'log_NC' ;
  26 , 'name' , 'log_NI' ;
  27 , 'name' , 'Definition log labor productivity' ;
  28 , 'name' , 'Definition of log Solow residual' ;
  29 , 'name' , 'Definition of log relative investment  price' ;
  30 , 'name' , 'C_obs' ;
  31 , 'name' , 'I_obs' ;
  32 , 'name' , 'Y_obs' ;
  33 , 'name' , 'Y_N_obs' ;
  34 , 'name' , 'SR_obs' ;
  35 , 'name' , 'p_I_obs' ;
  36 , 'name' , 'N_obs' ;
  37 , 'name' , 'NC_obs' ;
  38 , 'name' , 'NI_obs' ;
};
M_.mapping.Y.eqidx = [14 15 21 ];
M_.mapping.C.eqidx = [2 5 8 9 14 15 22 ];
M_.mapping.I.eqidx = [6 7 10 11 14 15 23 ];
M_.mapping.SR.eqidx = [15 28 ];
M_.mapping.K.eqidx = [13 ];
M_.mapping.K_C.eqidx = [5 7 9 13 15 ];
M_.mapping.K_I.eqidx = [6 7 11 13 15 ];
M_.mapping.N.eqidx = [1 2 12 24 ];
M_.mapping.N_C.eqidx = [5 8 12 15 25 ];
M_.mapping.N_I.eqidx = [6 10 12 15 26 ];
M_.mapping.Z_C.eqidx = [5 17 19 ];
M_.mapping.u_ZI.eqidx = [18 19 ];
M_.mapping.Z_I.eqidx = [6 18 19 ];
M_.mapping.theta_N.eqidx = [1 2 20 ];
M_.mapping.R_C.eqidx = [3 4 9 ];
M_.mapping.R_I.eqidx = [4 11 ];
M_.mapping.W.eqidx = [1 8 10 ];
M_.mapping.Gam.eqidx = [2 3 ];
M_.mapping.p_I.eqidx = [3 10 11 29 ];
M_.mapping.g.eqidx = [3 5 6 7 9 11 15 16 30 31 32 33 34 ];
M_.mapping.log_Y.eqidx = [21 27 32 ];
M_.mapping.log_C.eqidx = [22 30 ];
M_.mapping.log_I.eqidx = [23 31 ];
M_.mapping.log_N.eqidx = [24 27 36 ];
M_.mapping.log_NC.eqidx = [25 37 ];
M_.mapping.log_NI.eqidx = [26 38 ];
M_.mapping.log_Y_N.eqidx = [27 33 ];
M_.mapping.log_SR.eqidx = [28 34 ];
M_.mapping.log_p_I.eqidx = [29 35 ];
M_.mapping.C_obs.eqidx = [30 ];
M_.mapping.I_obs.eqidx = [31 ];
M_.mapping.Y_obs.eqidx = [32 ];
M_.mapping.Y_N_obs.eqidx = [33 ];
M_.mapping.SR_obs.eqidx = [34 ];
M_.mapping.p_I_obs.eqidx = [35 ];
M_.mapping.NC_obs.eqidx = [37 ];
M_.mapping.NI_obs.eqidx = [38 ];
M_.mapping.N_obs.eqidx = [36 ];
M_.mapping.e_g.eqidx = [16 ];
M_.mapping.e_Z.eqidx = [17 ];
M_.mapping.e_ZI.eqidx = [18 ];
M_.mapping.e_N.eqidx = [20 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [6 7 11 13 14 20 21 22 23 24 25 26 27 28 29 ];
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(38, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(13, 1);
M_.endo_trends = struct('deflator', cell(38, 1), 'log_deflator', cell(38, 1), 'growth_factor', cell(38, 1), 'log_growth_factor', cell(38, 1));
M_.NNZDerivatives = [131; -1; -1; ];
M_.static_tmp_nbr = [26; 4; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 2.0;
sigma = M_.params(1);
M_.params(2) = 0.99;
beta = M_.params(2);
M_.params(3) = 0.0045;
g_bar = M_.params(3);
M_.params(4) = 0.72;
nu = M_.params(4);
M_.params(5) = 0.20;
I_Y = M_.params(5);
M_.params(6) = 11;
K_Y = M_.params(6);
M_.params(7) = 0.67;
labor_share = M_.params(7);
M_.params(12) = 1.0;
p_I_ss = M_.params(12);
M_.params(13) = 0.30;
N_ss = M_.params(13);
M_.params(8) = 0.1;
rho_g = M_.params(8);
M_.params(9) = 0.9;
rho_Z = M_.params(9);
M_.params(10) = 0.9;
rho_ZI = M_.params(10);
M_.params(11) = 0.9;
rho_N = M_.params(11);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1e-06;
M_.Sigma_e(2, 2) = 5.184e-05;
M_.Sigma_e(3, 3) = 5.184e-05;
M_.Sigma_e(4, 4) = 5.184e-05;
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 20;
options_.nofunctions = true;
options_.order = 1;
options_.periods = 0;
var_list_ = {'Y_obs';'Y_N_obs';'SR_obs';'I_obs';'p_I_obs';'C_obs';'NC_obs';'NI_obs'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'RBC_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'RBC_results.mat'], 'oo_recursive_', '-append');
end
disp('Note: 7 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
