%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'BRS_sectoral_wo_vcu';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(17,1);
M_.exo_names_tex = cell(17,1);
M_.exo_names_long = cell(17,1);
M_.exo_names(1) = {'e_g'};
M_.exo_names_tex(1) = {'{e_g}'};
M_.exo_names_long(1) = {'Labor-augmenting-technology growth shock'};
M_.exo_names(2) = {'e_g_news'};
M_.exo_names_tex(2) = {'{e_{g,-4}}'};
M_.exo_names_long(2) = {'Labor-augmenting-technology growth shock: news'};
M_.exo_names(3) = {'e_Z'};
M_.exo_names_tex(3) = {'{e_Z}'};
M_.exo_names_long(3) = {'TFP shock'};
M_.exo_names(4) = {'e_Z_news'};
M_.exo_names_tex(4) = {'{e_{Z,-4}}'};
M_.exo_names_long(4) = {'TFP shock: news'};
M_.exo_names(5) = {'e_ZI'};
M_.exo_names_tex(5) = {'{e_{ZI}}'};
M_.exo_names_long(5) = {'Investment-specific tech shock'};
M_.exo_names(6) = {'e_ZI_news'};
M_.exo_names_tex(6) = {'{e_{ZI,-4}}'};
M_.exo_names_long(6) = {'Investment-specific tech shock: news'};
M_.exo_names(7) = {'e_N'};
M_.exo_names_tex(7) = {'{e_N}'};
M_.exo_names_long(7) = {'Labor supply shock'};
M_.exo_names(8) = {'e_D'};
M_.exo_names_tex(8) = {'{e_D}'};
M_.exo_names_long(8) = {'Shopping disutility shock'};
M_.exo_names(9) = {'e_D_news'};
M_.exo_names_tex(9) = {'{e_{D,4}}'};
M_.exo_names_long(9) = {'Shopping disutility shock: news'};
M_.exo_names(10) = {'e_DI'};
M_.exo_names_tex(10) = {'{e_DI}'};
M_.exo_names_long(10) = {'Relative investment shopping disutility shock'};
M_.exo_names(11) = {'e_DI_news'};
M_.exo_names_tex(11) = {'{e_{DI,-4}}'};
M_.exo_names_long(11) = {'Relative investment shopping disutility shock: news'};
M_.exo_names(12) = {'e_b'};
M_.exo_names_tex(12) = {'{e_b}'};
M_.exo_names_long(12) = {'Discount factor shock'};
M_.exo_names(13) = {'e_b_news'};
M_.exo_names_tex(13) = {'{e_{b,-4}}'};
M_.exo_names_long(13) = {'Discount factor shock'};
M_.exo_names(14) = {'e_muC'};
M_.exo_names_tex(14) = {'{e_{muC}}'};
M_.exo_names_long(14) = {'Wage markup shock: C'};
M_.exo_names(15) = {'e_muC_news'};
M_.exo_names_tex(15) = {'{e_{muC,-4}}'};
M_.exo_names_long(15) = {'Wage markup shock: C: news'};
M_.exo_names(16) = {'e_muI'};
M_.exo_names_tex(16) = {'{e_{muI}}'};
M_.exo_names_long(16) = {'Wage markup shock: I'};
M_.exo_names(17) = {'e_muI_news'};
M_.exo_names_tex(17) = {'{e_{muI,-4}}'};
M_.exo_names_long(17) = {'Wage markup shock: I: news'};
M_.endo_names = cell(121,1);
M_.endo_names_tex = cell(121,1);
M_.endo_names_long = cell(121,1);
M_.endo_names(1) = {'Y'};
M_.endo_names_tex(1) = {'{Y}'};
M_.endo_names_long(1) = {'output'};
M_.endo_names(2) = {'C'};
M_.endo_names_tex(2) = {'{C}'};
M_.endo_names_long(2) = {'consumption'};
M_.endo_names(3) = {'Y_mc'};
M_.endo_names_tex(3) = {'{Y_{mc}}'};
M_.endo_names_long(3) = {'consumption non-durable goods'};
M_.endo_names(4) = {'Y_sc'};
M_.endo_names_tex(4) = {'Y_{sc}}'};
M_.endo_names_long(4) = {'consumption services'};
M_.endo_names(5) = {'I'};
M_.endo_names_tex(5) = {'{I}'};
M_.endo_names_long(5) = {'investment'};
M_.endo_names(6) = {'I_mc'};
M_.endo_names_tex(6) = {'{I_C}'};
M_.endo_names_long(6) = {'investment:mc'};
M_.endo_names(7) = {'I_sc'};
M_.endo_names_tex(7) = {'{I_C}'};
M_.endo_names_long(7) = {'investment:sc'};
M_.endo_names(8) = {'I_I'};
M_.endo_names_tex(8) = {'{I_I}'};
M_.endo_names_long(8) = {'investment:I'};
M_.endo_names(9) = {'K'};
M_.endo_names_tex(9) = {'{K}'};
M_.endo_names_long(9) = {'Capital'};
M_.endo_names(10) = {'K_mc'};
M_.endo_names_tex(10) = {'{K_{mc}}'};
M_.endo_names_long(10) = {'Capital:mc'};
M_.endo_names(11) = {'K_sc'};
M_.endo_names_tex(11) = {'{K_{sc}}'};
M_.endo_names_long(11) = {'Capital:sc'};
M_.endo_names(12) = {'K_I'};
M_.endo_names_tex(12) = {'{K_I}'};
M_.endo_names_long(12) = {'Capital:I'};
M_.endo_names(13) = {'N'};
M_.endo_names_tex(13) = {'{N}'};
M_.endo_names_long(13) = {'Hours'};
M_.endo_names(14) = {'N_mc'};
M_.endo_names_tex(14) = {'{N_{mc}}'};
M_.endo_names_long(14) = {'Hours:mc'};
M_.endo_names(15) = {'N_sc'};
M_.endo_names_tex(15) = {'{N_{sc}}'};
M_.endo_names_long(15) = {'Hours:sc'};
M_.endo_names(16) = {'N_C'};
M_.endo_names_tex(16) = {'{N_C}'};
M_.endo_names_long(16) = {'Hours:C'};
M_.endo_names(17) = {'N_I'};
M_.endo_names_tex(17) = {'{N_I}'};
M_.endo_names_long(17) = {'Hours:I'};
M_.endo_names(18) = {'N_comp'};
M_.endo_names_tex(18) = {'{N}'};
M_.endo_names_long(18) = {'Labor CES aggregate'};
M_.endo_names(19) = {'Z_C'};
M_.endo_names_tex(19) = {'{Z_{C}}'};
M_.endo_names_long(19) = {'Tech:mc'};
M_.endo_names(20) = {'u_ZI'};
M_.endo_names_tex(20) = {'u\_ZI'};
M_.endo_names_long(20) = {'u_ZI'};
M_.endo_names(21) = {'Z_I'};
M_.endo_names_tex(21) = {'{Z_I}'};
M_.endo_names_long(21) = {'Tech:I'};
M_.endo_names(22) = {'theta_N'};
M_.endo_names_tex(22) = {'{\theta_N}'};
M_.endo_names_long(22) = {'Labor disutility'};
M_.endo_names(23) = {'theta_D'};
M_.endo_names_tex(23) = {'{\theta_D}'};
M_.endo_names_long(23) = {'Shopping disutility'};
M_.endo_names(24) = {'theta_I'};
M_.endo_names_tex(24) = {'{\theta_I}'};
M_.endo_names_long(24) = {'Relative shopping disutility'};
M_.endo_names(25) = {'theta_b'};
M_.endo_names_tex(25) = {'{\theta_b}'};
M_.endo_names_long(25) = {'Discount factor shock'};
M_.endo_names(26) = {'mu_C'};
M_.endo_names_tex(26) = {'{\mu_C}'};
M_.endo_names_long(26) = {'mu_C'};
M_.endo_names(27) = {'mu_I'};
M_.endo_names_tex(27) = {'\mu_I}'};
M_.endo_names_long(27) = {'mu_I'};
M_.endo_names(28) = {'R_mc'};
M_.endo_names_tex(28) = {'{R_{mc}}'};
M_.endo_names_long(28) = {'Capital rental rate:mc'};
M_.endo_names(29) = {'R_sc'};
M_.endo_names_tex(29) = {'{R_{sc}}'};
M_.endo_names_long(29) = {'Capital rental rate:sc'};
M_.endo_names(30) = {'R_I'};
M_.endo_names_tex(30) = {'{R_I}'};
M_.endo_names_long(30) = {'Capital rental rate:I'};
M_.endo_names(31) = {'W_C'};
M_.endo_names_tex(31) = {'{W_C}'};
M_.endo_names_long(31) = {'Real wage:C'};
M_.endo_names(32) = {'W_I'};
M_.endo_names_tex(32) = {'{W_I}'};
M_.endo_names_long(32) = {'Real wage:I'};
M_.endo_names(33) = {'W'};
M_.endo_names_tex(33) = {'{W}'};
M_.endo_names_long(33) = {'Real wage'};
M_.endo_names(34) = {'Smc'};
M_.endo_names_tex(34) = {'S'};
M_.endo_names_long(34) = {'Investment adjustment cost:mc'};
M_.endo_names(35) = {'Ssc'};
M_.endo_names_tex(35) = {'S'};
M_.endo_names_long(35) = {'Investment adjustment cost:sc'};
M_.endo_names(36) = {'Si'};
M_.endo_names_tex(36) = {'S'};
M_.endo_names_long(36) = {'Investment adjustment cost:I'};
M_.endo_names(37) = {'Smc_pr'};
M_.endo_names_tex(37) = {'S_pr'};
M_.endo_names_long(37) = {'Derivative investment adjustment cost:mc'};
M_.endo_names(38) = {'Ssc_pr'};
M_.endo_names_tex(38) = {'S_pr'};
M_.endo_names_long(38) = {'Derivative investment adjustment cost:sc'};
M_.endo_names(39) = {'Si_pr'};
M_.endo_names_tex(39) = {'S_pr'};
M_.endo_names_long(39) = {'Derivative investment adjustment cost:I'};
M_.endo_names(40) = {'D'};
M_.endo_names_tex(40) = {'{D}'};
M_.endo_names_long(40) = {'Shopping effort'};
M_.endo_names(41) = {'D_mc'};
M_.endo_names_tex(41) = {'{D_{mc}}'};
M_.endo_names_long(41) = {'Shopping effort:mc'};
M_.endo_names(42) = {'D_sc'};
M_.endo_names_tex(42) = {'{D_{sc}}'};
M_.endo_names_long(42) = {'Shopping effort:sc'};
M_.endo_names(43) = {'D_I'};
M_.endo_names_tex(43) = {'{D_I}'};
M_.endo_names_long(43) = {'Shopping effort:I'};
M_.endo_names(44) = {'Gam'};
M_.endo_names_tex(44) = {'{\Gamma}'};
M_.endo_names_long(44) = {'Composite utility term'};
M_.endo_names(45) = {'zeta'};
M_.endo_names_tex(45) = {'{\zeta}'};
M_.endo_names_long(45) = {'Wealth effects parameter'};
M_.endo_names(46) = {'p_mc'};
M_.endo_names_tex(46) = {'{p_{mc}}'};
M_.endo_names_long(46) = {'Relative non-durable price'};
M_.endo_names(47) = {'p_sc'};
M_.endo_names_tex(47) = {'{p_{sc}}'};
M_.endo_names_long(47) = {'Relative service price'};
M_.endo_names(48) = {'p_I'};
M_.endo_names_tex(48) = {'{p_I}'};
M_.endo_names_long(48) = {'Relative investment price'};
M_.endo_names(49) = {'lam'};
M_.endo_names_tex(49) = {'{\lambda}'};
M_.endo_names_long(49) = {'Marginal utility of wealth'};
M_.endo_names(50) = {'Q_mc'};
M_.endo_names_tex(50) = {'{Q}'};
M_.endo_names_long(50) = {'Relative price of capital:mc'};
M_.endo_names(51) = {'Q_sc'};
M_.endo_names_tex(51) = {'{Q}'};
M_.endo_names_long(51) = {'Relative price of capital:sc'};
M_.endo_names(52) = {'Q_I'};
M_.endo_names_tex(52) = {'{Q}'};
M_.endo_names_long(52) = {'Relative price of capital:I'};
M_.endo_names(53) = {'x_mc'};
M_.endo_names_tex(53) = {'{x}'};
M_.endo_names_long(53) = {'Growth rate of investment:mc'};
M_.endo_names(54) = {'x_sc'};
M_.endo_names_tex(54) = {'{x}'};
M_.endo_names_long(54) = {'Growth rate of investment:sc'};
M_.endo_names(55) = {'x_I'};
M_.endo_names_tex(55) = {'{x}'};
M_.endo_names_long(55) = {'Growth rate of investment:I'};
M_.endo_names(56) = {'log_SR'};
M_.endo_names_tex(56) = {'log\_SR'};
M_.endo_names_long(56) = {'Solow residual'};
M_.endo_names(57) = {'util'};
M_.endo_names_tex(57) = {'{util}'};
M_.endo_names_long(57) = {'Capacity utilization'};
M_.endo_names(58) = {'util_ND'};
M_.endo_names_tex(58) = {'{util_{ND}}'};
M_.endo_names_long(58) = {'Capacity utilization:ND'};
M_.endo_names(59) = {'util_D'};
M_.endo_names_tex(59) = {'{util_D}'};
M_.endo_names_long(59) = {'Capacity utilization:D'};
M_.endo_names(60) = {'g'};
M_.endo_names_tex(60) = {'{g}'};
M_.endo_names_long(60) = {'Growth rate of stochastic trend'};
M_.endo_names(61) = {'log_Y'};
M_.endo_names_tex(61) = {'log\_Y'};
M_.endo_names_long(61) = {'log_Y'};
M_.endo_names(62) = {'log_C'};
M_.endo_names_tex(62) = {'log\_C'};
M_.endo_names_long(62) = {'log_C'};
M_.endo_names(63) = {'log_I'};
M_.endo_names_tex(63) = {'log\_I'};
M_.endo_names_long(63) = {'log_I'};
M_.endo_names(64) = {'log_N'};
M_.endo_names_tex(64) = {'log\_N'};
M_.endo_names_long(64) = {'log_N'};
M_.endo_names(65) = {'log_NC'};
M_.endo_names_tex(65) = {'log\_NC'};
M_.endo_names_long(65) = {'log_NC'};
M_.endo_names(66) = {'log_NI'};
M_.endo_names_tex(66) = {'log\_NI'};
M_.endo_names_long(66) = {'log_NI'};
M_.endo_names(67) = {'log_K'};
M_.endo_names_tex(67) = {'log\_K'};
M_.endo_names_long(67) = {'log_K'};
M_.endo_names(68) = {'log_Y_N'};
M_.endo_names_tex(68) = {'log\_Y\_N'};
M_.endo_names_long(68) = {'log_Y_N'};
M_.endo_names(69) = {'log_D'};
M_.endo_names_tex(69) = {'log\_D'};
M_.endo_names_long(69) = {'log_D'};
M_.endo_names(70) = {'log_p_I'};
M_.endo_names_tex(70) = {'log\_p\_I'};
M_.endo_names_long(70) = {'log_p_I'};
M_.endo_names(71) = {'log_util'};
M_.endo_names_tex(71) = {'log\_util'};
M_.endo_names_long(71) = {'log_util'};
M_.endo_names(72) = {'log_util_ND'};
M_.endo_names_tex(72) = {'log\_util\_ND'};
M_.endo_names_long(72) = {'log_util_ND'};
M_.endo_names(73) = {'log_util_D'};
M_.endo_names_tex(73) = {'log\_util\_D'};
M_.endo_names_long(73) = {'log_util_D'};
M_.endo_names(74) = {'log_W'};
M_.endo_names_tex(74) = {'log\_W'};
M_.endo_names_long(74) = {'log_W'};
M_.endo_names(75) = {'C_obs'};
M_.endo_names_tex(75) = {'C\_obs'};
M_.endo_names_long(75) = {'C_obs'};
M_.endo_names(76) = {'I_obs'};
M_.endo_names_tex(76) = {'I\_obs'};
M_.endo_names_long(76) = {'I_obs'};
M_.endo_names(77) = {'Y_obs'};
M_.endo_names_tex(77) = {'Y\_obs'};
M_.endo_names_long(77) = {'Y_obs'};
M_.endo_names(78) = {'Y_N_obs'};
M_.endo_names_tex(78) = {'Y\_N\_obs'};
M_.endo_names_long(78) = {'Y_N_obs'};
M_.endo_names(79) = {'p_I_obs'};
M_.endo_names_tex(79) = {'p\_I\_obs'};
M_.endo_names_long(79) = {'p_I_obs'};
M_.endo_names(80) = {'N_obs'};
M_.endo_names_tex(80) = {'N\_obs'};
M_.endo_names_long(80) = {'N_obs'};
M_.endo_names(81) = {'NC_obs'};
M_.endo_names_tex(81) = {'NC\_obs'};
M_.endo_names_long(81) = {'NC_obs'};
M_.endo_names(82) = {'NI_obs'};
M_.endo_names_tex(82) = {'NI\_obs'};
M_.endo_names_long(82) = {'NI_obs'};
M_.endo_names(83) = {'util_ND_obs'};
M_.endo_names_tex(83) = {'util\_ND\_obs'};
M_.endo_names_long(83) = {'util_ND_obs'};
M_.endo_names(84) = {'util_D_obs'};
M_.endo_names_tex(84) = {'util\_D\_obs'};
M_.endo_names_long(84) = {'util_D_obs'};
M_.endo_names(85) = {'w_obs'};
M_.endo_names_tex(85) = {'w\_obs'};
M_.endo_names_long(85) = {'w_obs'};
M_.endo_names(86) = {'util_obs'};
M_.endo_names_tex(86) = {'util\_obs'};
M_.endo_names_long(86) = {'util_obs'};
M_.endo_names(87) = {'D_obs'};
M_.endo_names_tex(87) = {'D\_obs'};
M_.endo_names_long(87) = {'D_obs'};
M_.endo_names(88) = {'K_obs'};
M_.endo_names_tex(88) = {'K\_obs'};
M_.endo_names_long(88) = {'K_obs'};
M_.endo_names(89) = {'SR_obs'};
M_.endo_names_tex(89) = {'SR\_obs'};
M_.endo_names_long(89) = {'SR_obs'};
M_.endo_names(90) = {'AUX_EXO_LAG_90_0'};
M_.endo_names_tex(90) = {'AUX\_EXO\_LAG\_90\_0'};
M_.endo_names_long(90) = {'AUX_EXO_LAG_90_0'};
M_.endo_names(91) = {'AUX_EXO_LAG_90_1'};
M_.endo_names_tex(91) = {'AUX\_EXO\_LAG\_90\_1'};
M_.endo_names_long(91) = {'AUX_EXO_LAG_90_1'};
M_.endo_names(92) = {'AUX_EXO_LAG_90_2'};
M_.endo_names_tex(92) = {'AUX\_EXO\_LAG\_90\_2'};
M_.endo_names_long(92) = {'AUX_EXO_LAG_90_2'};
M_.endo_names(93) = {'AUX_EXO_LAG_90_3'};
M_.endo_names_tex(93) = {'AUX\_EXO\_LAG\_90\_3'};
M_.endo_names_long(93) = {'AUX_EXO_LAG_90_3'};
M_.endo_names(94) = {'AUX_EXO_LAG_92_0'};
M_.endo_names_tex(94) = {'AUX\_EXO\_LAG\_92\_0'};
M_.endo_names_long(94) = {'AUX_EXO_LAG_92_0'};
M_.endo_names(95) = {'AUX_EXO_LAG_92_1'};
M_.endo_names_tex(95) = {'AUX\_EXO\_LAG\_92\_1'};
M_.endo_names_long(95) = {'AUX_EXO_LAG_92_1'};
M_.endo_names(96) = {'AUX_EXO_LAG_92_2'};
M_.endo_names_tex(96) = {'AUX\_EXO\_LAG\_92\_2'};
M_.endo_names_long(96) = {'AUX_EXO_LAG_92_2'};
M_.endo_names(97) = {'AUX_EXO_LAG_92_3'};
M_.endo_names_tex(97) = {'AUX\_EXO\_LAG\_92\_3'};
M_.endo_names_long(97) = {'AUX_EXO_LAG_92_3'};
M_.endo_names(98) = {'AUX_EXO_LAG_94_0'};
M_.endo_names_tex(98) = {'AUX\_EXO\_LAG\_94\_0'};
M_.endo_names_long(98) = {'AUX_EXO_LAG_94_0'};
M_.endo_names(99) = {'AUX_EXO_LAG_94_1'};
M_.endo_names_tex(99) = {'AUX\_EXO\_LAG\_94\_1'};
M_.endo_names_long(99) = {'AUX_EXO_LAG_94_1'};
M_.endo_names(100) = {'AUX_EXO_LAG_94_2'};
M_.endo_names_tex(100) = {'AUX\_EXO\_LAG\_94\_2'};
M_.endo_names_long(100) = {'AUX_EXO_LAG_94_2'};
M_.endo_names(101) = {'AUX_EXO_LAG_94_3'};
M_.endo_names_tex(101) = {'AUX\_EXO\_LAG\_94\_3'};
M_.endo_names_long(101) = {'AUX_EXO_LAG_94_3'};
M_.endo_names(102) = {'AUX_EXO_LAG_97_0'};
M_.endo_names_tex(102) = {'AUX\_EXO\_LAG\_97\_0'};
M_.endo_names_long(102) = {'AUX_EXO_LAG_97_0'};
M_.endo_names(103) = {'AUX_EXO_LAG_97_1'};
M_.endo_names_tex(103) = {'AUX\_EXO\_LAG\_97\_1'};
M_.endo_names_long(103) = {'AUX_EXO_LAG_97_1'};
M_.endo_names(104) = {'AUX_EXO_LAG_97_2'};
M_.endo_names_tex(104) = {'AUX\_EXO\_LAG\_97\_2'};
M_.endo_names_long(104) = {'AUX_EXO_LAG_97_2'};
M_.endo_names(105) = {'AUX_EXO_LAG_97_3'};
M_.endo_names_tex(105) = {'AUX\_EXO\_LAG\_97\_3'};
M_.endo_names_long(105) = {'AUX_EXO_LAG_97_3'};
M_.endo_names(106) = {'AUX_EXO_LAG_99_0'};
M_.endo_names_tex(106) = {'AUX\_EXO\_LAG\_99\_0'};
M_.endo_names_long(106) = {'AUX_EXO_LAG_99_0'};
M_.endo_names(107) = {'AUX_EXO_LAG_99_1'};
M_.endo_names_tex(107) = {'AUX\_EXO\_LAG\_99\_1'};
M_.endo_names_long(107) = {'AUX_EXO_LAG_99_1'};
M_.endo_names(108) = {'AUX_EXO_LAG_99_2'};
M_.endo_names_tex(108) = {'AUX\_EXO\_LAG\_99\_2'};
M_.endo_names_long(108) = {'AUX_EXO_LAG_99_2'};
M_.endo_names(109) = {'AUX_EXO_LAG_99_3'};
M_.endo_names_tex(109) = {'AUX\_EXO\_LAG\_99\_3'};
M_.endo_names_long(109) = {'AUX_EXO_LAG_99_3'};
M_.endo_names(110) = {'AUX_EXO_LAG_101_0'};
M_.endo_names_tex(110) = {'AUX\_EXO\_LAG\_101\_0'};
M_.endo_names_long(110) = {'AUX_EXO_LAG_101_0'};
M_.endo_names(111) = {'AUX_EXO_LAG_101_1'};
M_.endo_names_tex(111) = {'AUX\_EXO\_LAG\_101\_1'};
M_.endo_names_long(111) = {'AUX_EXO_LAG_101_1'};
M_.endo_names(112) = {'AUX_EXO_LAG_101_2'};
M_.endo_names_tex(112) = {'AUX\_EXO\_LAG\_101\_2'};
M_.endo_names_long(112) = {'AUX_EXO_LAG_101_2'};
M_.endo_names(113) = {'AUX_EXO_LAG_101_3'};
M_.endo_names_tex(113) = {'AUX\_EXO\_LAG\_101\_3'};
M_.endo_names_long(113) = {'AUX_EXO_LAG_101_3'};
M_.endo_names(114) = {'AUX_EXO_LAG_103_0'};
M_.endo_names_tex(114) = {'AUX\_EXO\_LAG\_103\_0'};
M_.endo_names_long(114) = {'AUX_EXO_LAG_103_0'};
M_.endo_names(115) = {'AUX_EXO_LAG_103_1'};
M_.endo_names_tex(115) = {'AUX\_EXO\_LAG\_103\_1'};
M_.endo_names_long(115) = {'AUX_EXO_LAG_103_1'};
M_.endo_names(116) = {'AUX_EXO_LAG_103_2'};
M_.endo_names_tex(116) = {'AUX\_EXO\_LAG\_103\_2'};
M_.endo_names_long(116) = {'AUX_EXO_LAG_103_2'};
M_.endo_names(117) = {'AUX_EXO_LAG_103_3'};
M_.endo_names_tex(117) = {'AUX\_EXO\_LAG\_103\_3'};
M_.endo_names_long(117) = {'AUX_EXO_LAG_103_3'};
M_.endo_names(118) = {'AUX_EXO_LAG_105_0'};
M_.endo_names_tex(118) = {'AUX\_EXO\_LAG\_105\_0'};
M_.endo_names_long(118) = {'AUX_EXO_LAG_105_0'};
M_.endo_names(119) = {'AUX_EXO_LAG_105_1'};
M_.endo_names_tex(119) = {'AUX\_EXO\_LAG\_105\_1'};
M_.endo_names_long(119) = {'AUX_EXO_LAG_105_1'};
M_.endo_names(120) = {'AUX_EXO_LAG_105_2'};
M_.endo_names_tex(120) = {'AUX\_EXO\_LAG\_105\_2'};
M_.endo_names_long(120) = {'AUX_EXO_LAG_105_2'};
M_.endo_names(121) = {'AUX_EXO_LAG_105_3'};
M_.endo_names_tex(121) = {'AUX\_EXO\_LAG\_105\_3'};
M_.endo_names_long(121) = {'AUX_EXO_LAG_105_3'};
M_.endo_partitions = struct();
M_.param_names = cell(30,1);
M_.param_names_tex = cell(30,1);
M_.param_names_long = cell(30,1);
M_.param_names(1) = {'sigma'};
M_.param_names_tex(1) = {'{\sigma}'};
M_.param_names_long(1) = {'Risk aversion'};
M_.param_names(2) = {'beta'};
M_.param_names_tex(2) = {'{\beta}'};
M_.param_names_long(2) = {'Discount factor'};
M_.param_names(3) = {'g_bar'};
M_.param_names_tex(3) = {'{\overline{g}}'};
M_.param_names_long(3) = {'Quarterly trend growth rate'};
M_.param_names(4) = {'nu'};
M_.param_names_tex(4) = {'\nu'};
M_.param_names_long(4) = {'Frisch elasticity'};
M_.param_names(5) = {'gam'};
M_.param_names_tex(5) = {'\gamma'};
M_.param_names_long(5) = {'wealth effect on labor supply'};
M_.param_names(6) = {'xi'};
M_.param_names_tex(6) = {'\xi'};
M_.param_names_long(6) = {'elasticity of substitution between non-durables and services'};
M_.param_names(7) = {'omega_sc'};
M_.param_names_tex(7) = {'\omega_{sc}'};
M_.param_names_long(7) = {'Weight of services in aggregator'};
M_.param_names(8) = {'mu_ss'};
M_.param_names_tex(8) = {'\mu_{ss}'};
M_.param_names_long(8) = {'steady-state wage markup'};
M_.param_names(9) = {'Psi_C'};
M_.param_names_tex(9) = {'{\Psi_{C}}'};
M_.param_names_long(9) = {'Investment adjustment cost parameter:non-durable goods'};
M_.param_names(10) = {'Psi_I'};
M_.param_names_tex(10) = {'{\Psi_I}'};
M_.param_names_long(10) = {'Investment adjustment cost parameter:I'};
M_.param_names(11) = {'I_Y'};
M_.param_names_tex(11) = {'{I_Y}'};
M_.param_names_long(11) = {'Investment-output ratio'};
M_.param_names(12) = {'K_Y'};
M_.param_names_tex(12) = {'{K_Y}'};
M_.param_names_long(12) = {'Capital-output ratio (quarterly)'};
M_.param_names(13) = {'labor_share'};
M_.param_names_tex(13) = {'(labor share)'};
M_.param_names_long(13) = {'Labor share'};
M_.param_names(14) = {'nu_R'};
M_.param_names_tex(14) = {'{\nu_R}'};
M_.param_names_long(14) = {'Fixed cost share'};
M_.param_names(15) = {'ha'};
M_.param_names_tex(15) = {'{ha}'};
M_.param_names_long(15) = {'Habit persistence'};
M_.param_names(16) = {'phi'};
M_.param_names_tex(16) = {'{\phi}'};
M_.param_names_long(16) = {'Shopping matching function elasticity'};
M_.param_names(17) = {'eta'};
M_.param_names_tex(17) = {'{\eta}'};
M_.param_names_long(17) = {'Shopping disutility'};
M_.param_names(18) = {'Psi'};
M_.param_names_tex(18) = {'{\Psi}'};
M_.param_names_long(18) = {'Matching utilization'};
M_.param_names(19) = {'theta'};
M_.param_names_tex(19) = {'{\theta}'};
M_.param_names_long(19) = {'Inverse intersectoral elasticity of labor supply'};
M_.param_names(20) = {'rho_g'};
M_.param_names_tex(20) = {'{\rho_g}'};
M_.param_names_long(20) = {'persistence TFP growth shock'};
M_.param_names(21) = {'rho_Z'};
M_.param_names_tex(21) = {'{\rho_Z}'};
M_.param_names_long(21) = {'persistence TFP shock'};
M_.param_names(22) = {'rho_ZI'};
M_.param_names_tex(22) = {'{\rho_{ZI}}'};
M_.param_names_long(22) = {'persistence I-specific shock'};
M_.param_names(23) = {'rho_N'};
M_.param_names_tex(23) = {'{\rho_N}'};
M_.param_names_long(23) = {'persistence labor supply shock'};
M_.param_names(24) = {'rho_D'};
M_.param_names_tex(24) = {'{\rho_D}'};
M_.param_names_long(24) = {'persistence shopping effort shock'};
M_.param_names(25) = {'rho_DI'};
M_.param_names_tex(25) = {'{\rho_{DI}}'};
M_.param_names_long(25) = {'persistence relative shopping effort shock'};
M_.param_names(26) = {'rho_b'};
M_.param_names_tex(26) = {'{\rho_b}'};
M_.param_names_long(26) = {'persistence discount factor shock'};
M_.param_names(27) = {'rho_muC'};
M_.param_names_tex(27) = {'{\rho_{muC}}'};
M_.param_names_long(27) = {'persistence wage markup shock:C'};
M_.param_names(28) = {'rho_muI'};
M_.param_names_tex(28) = {'{\rho_{muI}}'};
M_.param_names_long(28) = {'persistence wage markup shock:I'};
M_.param_names(29) = {'p_I_ss'};
M_.param_names_tex(29) = {'p\_I\_ss'};
M_.param_names_long(29) = {'p_I_ss'};
M_.param_names(30) = {'N_ss'};
M_.param_names_tex(30) = {'N\_ss'};
M_.param_names_long(30) = {'N_ss'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 17;
M_.endo_nbr = 121;
M_.param_nbr = 30;
M_.orig_endo_nbr = 89;
M_.aux_vars(1).endo_index = 90;
M_.aux_vars(1).type = 3;
M_.aux_vars(1).orig_index = 2;
M_.aux_vars(1).orig_lead_lag = 0;
M_.aux_vars(1).orig_expr = 'e_g_news';
M_.aux_vars(2).endo_index = 91;
M_.aux_vars(2).type = 3;
M_.aux_vars(2).orig_index = 2;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(2).orig_expr = 'AUX_EXO_LAG_90_0(-1)';
M_.aux_vars(3).endo_index = 92;
M_.aux_vars(3).type = 3;
M_.aux_vars(3).orig_index = 2;
M_.aux_vars(3).orig_lead_lag = -2;
M_.aux_vars(3).orig_expr = 'AUX_EXO_LAG_90_1(-1)';
M_.aux_vars(4).endo_index = 93;
M_.aux_vars(4).type = 3;
M_.aux_vars(4).orig_index = 2;
M_.aux_vars(4).orig_lead_lag = -3;
M_.aux_vars(4).orig_expr = 'AUX_EXO_LAG_90_2(-1)';
M_.aux_vars(5).endo_index = 94;
M_.aux_vars(5).type = 3;
M_.aux_vars(5).orig_index = 4;
M_.aux_vars(5).orig_lead_lag = 0;
M_.aux_vars(5).orig_expr = 'e_Z_news';
M_.aux_vars(6).endo_index = 95;
M_.aux_vars(6).type = 3;
M_.aux_vars(6).orig_index = 4;
M_.aux_vars(6).orig_lead_lag = -1;
M_.aux_vars(6).orig_expr = 'AUX_EXO_LAG_92_0(-1)';
M_.aux_vars(7).endo_index = 96;
M_.aux_vars(7).type = 3;
M_.aux_vars(7).orig_index = 4;
M_.aux_vars(7).orig_lead_lag = -2;
M_.aux_vars(7).orig_expr = 'AUX_EXO_LAG_92_1(-1)';
M_.aux_vars(8).endo_index = 97;
M_.aux_vars(8).type = 3;
M_.aux_vars(8).orig_index = 4;
M_.aux_vars(8).orig_lead_lag = -3;
M_.aux_vars(8).orig_expr = 'AUX_EXO_LAG_92_2(-1)';
M_.aux_vars(9).endo_index = 98;
M_.aux_vars(9).type = 3;
M_.aux_vars(9).orig_index = 6;
M_.aux_vars(9).orig_lead_lag = 0;
M_.aux_vars(9).orig_expr = 'e_ZI_news';
M_.aux_vars(10).endo_index = 99;
M_.aux_vars(10).type = 3;
M_.aux_vars(10).orig_index = 6;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(10).orig_expr = 'AUX_EXO_LAG_94_0(-1)';
M_.aux_vars(11).endo_index = 100;
M_.aux_vars(11).type = 3;
M_.aux_vars(11).orig_index = 6;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(11).orig_expr = 'AUX_EXO_LAG_94_1(-1)';
M_.aux_vars(12).endo_index = 101;
M_.aux_vars(12).type = 3;
M_.aux_vars(12).orig_index = 6;
M_.aux_vars(12).orig_lead_lag = -3;
M_.aux_vars(12).orig_expr = 'AUX_EXO_LAG_94_2(-1)';
M_.aux_vars(13).endo_index = 102;
M_.aux_vars(13).type = 3;
M_.aux_vars(13).orig_index = 9;
M_.aux_vars(13).orig_lead_lag = 0;
M_.aux_vars(13).orig_expr = 'e_D_news';
M_.aux_vars(14).endo_index = 103;
M_.aux_vars(14).type = 3;
M_.aux_vars(14).orig_index = 9;
M_.aux_vars(14).orig_lead_lag = -1;
M_.aux_vars(14).orig_expr = 'AUX_EXO_LAG_97_0(-1)';
M_.aux_vars(15).endo_index = 104;
M_.aux_vars(15).type = 3;
M_.aux_vars(15).orig_index = 9;
M_.aux_vars(15).orig_lead_lag = -2;
M_.aux_vars(15).orig_expr = 'AUX_EXO_LAG_97_1(-1)';
M_.aux_vars(16).endo_index = 105;
M_.aux_vars(16).type = 3;
M_.aux_vars(16).orig_index = 9;
M_.aux_vars(16).orig_lead_lag = -3;
M_.aux_vars(16).orig_expr = 'AUX_EXO_LAG_97_2(-1)';
M_.aux_vars(17).endo_index = 106;
M_.aux_vars(17).type = 3;
M_.aux_vars(17).orig_index = 11;
M_.aux_vars(17).orig_lead_lag = 0;
M_.aux_vars(17).orig_expr = 'e_DI_news';
M_.aux_vars(18).endo_index = 107;
M_.aux_vars(18).type = 3;
M_.aux_vars(18).orig_index = 11;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(18).orig_expr = 'AUX_EXO_LAG_99_0(-1)';
M_.aux_vars(19).endo_index = 108;
M_.aux_vars(19).type = 3;
M_.aux_vars(19).orig_index = 11;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(19).orig_expr = 'AUX_EXO_LAG_99_1(-1)';
M_.aux_vars(20).endo_index = 109;
M_.aux_vars(20).type = 3;
M_.aux_vars(20).orig_index = 11;
M_.aux_vars(20).orig_lead_lag = -3;
M_.aux_vars(20).orig_expr = 'AUX_EXO_LAG_99_2(-1)';
M_.aux_vars(21).endo_index = 110;
M_.aux_vars(21).type = 3;
M_.aux_vars(21).orig_index = 13;
M_.aux_vars(21).orig_lead_lag = 0;
M_.aux_vars(21).orig_expr = 'e_b_news';
M_.aux_vars(22).endo_index = 111;
M_.aux_vars(22).type = 3;
M_.aux_vars(22).orig_index = 13;
M_.aux_vars(22).orig_lead_lag = -1;
M_.aux_vars(22).orig_expr = 'AUX_EXO_LAG_101_0(-1)';
M_.aux_vars(23).endo_index = 112;
M_.aux_vars(23).type = 3;
M_.aux_vars(23).orig_index = 13;
M_.aux_vars(23).orig_lead_lag = -2;
M_.aux_vars(23).orig_expr = 'AUX_EXO_LAG_101_1(-1)';
M_.aux_vars(24).endo_index = 113;
M_.aux_vars(24).type = 3;
M_.aux_vars(24).orig_index = 13;
M_.aux_vars(24).orig_lead_lag = -3;
M_.aux_vars(24).orig_expr = 'AUX_EXO_LAG_101_2(-1)';
M_.aux_vars(25).endo_index = 114;
M_.aux_vars(25).type = 3;
M_.aux_vars(25).orig_index = 15;
M_.aux_vars(25).orig_lead_lag = 0;
M_.aux_vars(25).orig_expr = 'e_muC_news';
M_.aux_vars(26).endo_index = 115;
M_.aux_vars(26).type = 3;
M_.aux_vars(26).orig_index = 15;
M_.aux_vars(26).orig_lead_lag = -1;
M_.aux_vars(26).orig_expr = 'AUX_EXO_LAG_103_0(-1)';
M_.aux_vars(27).endo_index = 116;
M_.aux_vars(27).type = 3;
M_.aux_vars(27).orig_index = 15;
M_.aux_vars(27).orig_lead_lag = -2;
M_.aux_vars(27).orig_expr = 'AUX_EXO_LAG_103_1(-1)';
M_.aux_vars(28).endo_index = 117;
M_.aux_vars(28).type = 3;
M_.aux_vars(28).orig_index = 15;
M_.aux_vars(28).orig_lead_lag = -3;
M_.aux_vars(28).orig_expr = 'AUX_EXO_LAG_103_2(-1)';
M_.aux_vars(29).endo_index = 118;
M_.aux_vars(29).type = 3;
M_.aux_vars(29).orig_index = 17;
M_.aux_vars(29).orig_lead_lag = 0;
M_.aux_vars(29).orig_expr = 'e_muI_news';
M_.aux_vars(30).endo_index = 119;
M_.aux_vars(30).type = 3;
M_.aux_vars(30).orig_index = 17;
M_.aux_vars(30).orig_lead_lag = -1;
M_.aux_vars(30).orig_expr = 'AUX_EXO_LAG_105_0(-1)';
M_.aux_vars(31).endo_index = 120;
M_.aux_vars(31).type = 3;
M_.aux_vars(31).orig_index = 17;
M_.aux_vars(31).orig_lead_lag = -2;
M_.aux_vars(31).orig_expr = 'AUX_EXO_LAG_105_1(-1)';
M_.aux_vars(32).endo_index = 121;
M_.aux_vars(32).type = 3;
M_.aux_vars(32).orig_index = 17;
M_.aux_vars(32).orig_lead_lag = -3;
M_.aux_vars(32).orig_expr = 'AUX_EXO_LAG_105_2(-1)';
options_.varobs = cell(7, 1);
options_.varobs(1)  = {'NC_obs'};
options_.varobs(2)  = {'NI_obs'};
options_.varobs(3)  = {'C_obs'};
options_.varobs(4)  = {'I_obs'};
options_.varobs(5)  = {'p_I_obs'};
options_.varobs(6)  = {'util_ND_obs'};
options_.varobs(7)  = {'util_D_obs'};
options_.varobs_id = [ 81 82 75 76 79 83 84  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(17, 17);
M_.Correlation_matrix = eye(17, 17);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 89;
M_.eq_nbr = 121;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 4;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 4;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 4;
M_.lead_lag_incidence = [
 0 65 0;
 1 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 2 70 0;
 3 71 0;
 4 72 0;
 0 73 0;
 5 74 0;
 6 75 0;
 7 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 8 83 0;
 0 84 0;
 9 85 0;
 10 86 0;
 11 87 0;
 12 88 0;
 13 89 0;
 14 90 0;
 15 91 0;
 0 92 186;
 0 93 187;
 0 94 188;
 0 95 0;
 0 96 0;
 0 97 0;
 0 98 0;
 0 99 0;
 0 100 0;
 0 101 189;
 0 102 190;
 0 103 191;
 0 104 0;
 0 105 0;
 0 106 0;
 0 107 0;
 0 108 0;
 16 109 0;
 0 110 0;
 0 111 0;
 0 112 0;
 0 113 192;
 0 114 193;
 0 115 194;
 0 116 195;
 0 117 196;
 0 118 197;
 0 119 198;
 0 120 0;
 0 121 0;
 0 122 0;
 0 123 0;
 17 124 199;
 18 125 0;
 19 126 0;
 20 127 0;
 21 128 0;
 22 129 0;
 23 130 0;
 24 131 0;
 25 132 0;
 26 133 0;
 27 134 0;
 28 135 0;
 29 136 0;
 30 137 0;
 31 138 0;
 0 139 0;
 0 140 0;
 0 141 0;
 0 142 0;
 0 143 0;
 0 144 0;
 0 145 0;
 0 146 0;
 0 147 0;
 0 148 0;
 0 149 0;
 0 150 0;
 0 151 0;
 32 152 0;
 0 153 0;
 33 154 0;
 34 155 0;
 35 156 0;
 36 157 0;
 37 158 0;
 38 159 0;
 39 160 0;
 40 161 0;
 41 162 0;
 42 163 0;
 43 164 0;
 44 165 0;
 45 166 0;
 46 167 0;
 47 168 0;
 48 169 0;
 49 170 0;
 50 171 0;
 51 172 0;
 52 173 0;
 53 174 0;
 54 175 0;
 55 176 0;
 56 177 0;
 57 178 0;
 58 179 0;
 59 180 0;
 60 181 0;
 61 182 0;
 62 183 0;
 63 184 0;
 64 185 0;]';
M_.nstatic = 44;
M_.nfwrd   = 13;
M_.npred   = 63;
M_.nboth   = 1;
M_.nsfwrd   = 14;
M_.nspred   = 64;
M_.ndynamic   = 77;
M_.dynamic_tmp_nbr = [62; 15; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Labor composite' ;
  2 , 'name' , 'Labor leisure:C' ;
  3 , 'name' , 'Labor leisure:I' ;
  4 , 'name' , 'Marginal utility of wealth' ;
  5 , 'name' , 'Demand curve: mc' ;
  6 , 'name' , 'Demand curve: sc' ;
  7 , 'name' , 'Shopping:mc' ;
  8 , 'name' , 'Shopping:sc' ;
  9 , 'name' , 'Shopping:I' ;
  10 , 'name' , 'Composite utility term' ;
  11 , 'name' , 'Law of motion of wealth effects variable' ;
  12 , 'name' , 'Consumption CES aggregator' ;
  13 , 'name' , 'Investment adjustment cost function:mc' ;
  14 , 'name' , 'Investment adjustment cost function:mc' ;
  15 , 'name' , 'Investment adjustment cost function:I' ;
  16 , 'name' , 'Investment adjustment cost function: derivative mc' ;
  17 , 'name' , 'Investment adjustment cost function: derivative mc' ;
  18 , 'name' , 'Investment adjustment cost function: derivative I' ;
  19 , 'name' , 'Investment growth:mc' ;
  20 , 'name' , 'Investment growth:mc' ;
  21 , 'name' , 'Investment growth:I' ;
  22 , 'name' , 'Tobins Q: mc' ;
  23 , 'name' , 'Tobins Q: sc' ;
  24 , 'name' , 'Tobins Q: I' ;
  25 , 'name' , 'Euler equation: mc' ;
  26 , 'name' , 'Euler equation: sc' ;
  27 , 'name' , 'Euler equation: I' ;
  28 , 'name' , 'Non-durable goods production' ;
  29 , 'name' , 'Services production' ;
  30 , 'name' , 'Investment production' ;
  31 , 'name' , 'Capital law of motion:mc' ;
  32 , 'name' , 'Capital law of motion:sc' ;
  33 , 'name' , 'Capital law of motion:I' ;
  34 , 'name' , 'Labor demand:mc' ;
  35 , 'name' , 'Labor demand:sc' ;
  36 , 'name' , 'Labor demand:I' ;
  37 , 'name' , 'Capital demand:mc' ;
  38 , 'name' , 'Capital demand:sc' ;
  39 , 'name' , 'Capital demand:I' ;
  40 , 'name' , 'Labor composition' ;
  41 , 'name' , 'Labor composition: C' ;
  42 , 'name' , 'Capital composition' ;
  43 , 'name' , 'Investment composition' ;
  44 , 'name' , 'Shopping composition' ;
  45 , 'name' , 'Aggregate wage' ;
  46 , 'name' , 'Output (base-year prices)' ;
  47 , 'name' , 'Capacity utilization' ;
  48 , 'name' , 'util_D' ;
  49 , 'name' , 'util' ;
  50 , 'name' , 'stochastic trend process' ;
  51 , 'name' , 'Stationary TFP process' ;
  52 , 'name' , 'Independent component of I-specific tech' ;
  53 , 'name' , 'Investment-specific TFP process' ;
  54 , 'name' , 'Labor supply process' ;
  55 , 'name' , 'Shopping effort process' ;
  56 , 'name' , 'Relative shopping effort process' ;
  57 , 'name' , 'Consumption preference process' ;
  58 , 'name' , 'Wage-markup process: C' ;
  59 , 'name' , 'Wage-markup process: I' ;
  60 , 'name' , 'Definition log output' ;
  61 , 'name' , 'Definition log consumption' ;
  62 , 'name' , 'Definition log investment' ;
  63 , 'name' , 'Definition log hours' ;
  64 , 'name' , 'log_NC' ;
  65 , 'name' , 'log_NI' ;
  66 , 'name' , 'log capital' ;
  67 , 'name' , 'Definition log labor productivity' ;
  68 , 'name' , 'Definition log shopping effort' ;
  69 , 'name' , 'Definition of log relative investment  price' ;
  70 , 'name' , 'Definition of log capacity utilization' ;
  71 , 'name' , 'log_util_ND' ;
  72 , 'name' , 'log_util_D' ;
  73 , 'name' , 'Definition of log wages' ;
  74 , 'name' , 'Definition of log Solow residual' ;
  75 , 'name' , 'C_obs' ;
  76 , 'name' , 'I_obs' ;
  77 , 'name' , 'Y_obs' ;
  78 , 'name' , 'Y_N_obs' ;
  79 , 'name' , 'K_obs' ;
  80 , 'name' , 'w_obs' ;
  81 , 'name' , 'SR_obs' ;
  82 , 'name' , 'p_I_obs' ;
  83 , 'name' , 'N_obs' ;
  84 , 'name' , 'NC_obs' ;
  85 , 'name' , 'NI_obs' ;
  86 , 'name' , 'util_ND_obs' ;
  87 , 'name' , 'util_D_obs' ;
  88 , 'name' , 'util_obs' ;
  89 , 'name' , 'D_obs' ;
};
M_.mapping.Y.eqidx = [46 60 ];
M_.mapping.C.eqidx = [5 6 10 11 12 46 61 ];
M_.mapping.Y_mc.eqidx = [5 7 12 28 34 37 49 ];
M_.mapping.Y_sc.eqidx = [6 8 12 29 35 38 ];
M_.mapping.I.eqidx = [9 30 36 39 43 46 49 62 ];
M_.mapping.I_mc.eqidx = [19 31 43 ];
M_.mapping.I_sc.eqidx = [20 32 43 ];
M_.mapping.I_I.eqidx = [21 33 43 ];
M_.mapping.K.eqidx = [42 66 ];
M_.mapping.K_mc.eqidx = [28 31 37 42 ];
M_.mapping.K_sc.eqidx = [29 32 38 42 ];
M_.mapping.K_I.eqidx = [30 33 39 42 ];
M_.mapping.N.eqidx = [40 45 63 ];
M_.mapping.N_mc.eqidx = [28 34 40 41 ];
M_.mapping.N_sc.eqidx = [29 35 40 41 ];
M_.mapping.N_C.eqidx = [1 2 41 45 64 ];
M_.mapping.N_I.eqidx = [1 3 30 36 40 45 65 ];
M_.mapping.N_comp.eqidx = [1 2 3 10 ];
M_.mapping.Z_C.eqidx = [28 29 51 53 ];
M_.mapping.u_ZI.eqidx = [52 53 ];
M_.mapping.Z_I.eqidx = [30 52 53 ];
M_.mapping.theta_N.eqidx = [2 3 10 54 ];
M_.mapping.theta_D.eqidx = [7 8 9 10 11 55 ];
M_.mapping.theta_I.eqidx = [9 44 56 ];
M_.mapping.theta_b.eqidx = [22 23 24 25 26 27 57 ];
M_.mapping.mu_C.eqidx = [2 58 ];
M_.mapping.mu_I.eqidx = [3 59 ];
M_.mapping.R_mc.eqidx = [25 37 ];
M_.mapping.R_sc.eqidx = [26 38 ];
M_.mapping.R_I.eqidx = [27 39 ];
M_.mapping.W_C.eqidx = [2 34 35 45 ];
M_.mapping.W_I.eqidx = [3 36 45 ];
M_.mapping.W.eqidx = [45 73 ];
M_.mapping.Smc.eqidx = [13 22 31 ];
M_.mapping.Ssc.eqidx = [14 23 32 ];
M_.mapping.Si.eqidx = [15 24 33 ];
M_.mapping.Smc_pr.eqidx = [16 22 ];
M_.mapping.Ssc_pr.eqidx = [17 23 ];
M_.mapping.Si_pr.eqidx = [18 24 ];
M_.mapping.D.eqidx = [7 8 9 10 11 44 68 ];
M_.mapping.D_mc.eqidx = [7 28 34 37 44 47 ];
M_.mapping.D_sc.eqidx = [8 29 35 38 44 ];
M_.mapping.D_I.eqidx = [9 30 36 39 44 48 ];
M_.mapping.Gam.eqidx = [4 10 ];
M_.mapping.zeta.eqidx = [2 3 10 11 ];
M_.mapping.p_mc.eqidx = [5 7 34 37 ];
M_.mapping.p_sc.eqidx = [6 8 35 38 ];
M_.mapping.p_I.eqidx = [9 22 23 24 36 39 69 ];
M_.mapping.lam.eqidx = [4 22 23 24 25 26 27 ];
M_.mapping.Q_mc.eqidx = [22 25 ];
M_.mapping.Q_sc.eqidx = [23 26 ];
M_.mapping.Q_I.eqidx = [24 27 ];
M_.mapping.x_mc.eqidx = [13 16 19 22 ];
M_.mapping.x_sc.eqidx = [14 17 20 23 ];
M_.mapping.x_I.eqidx = [15 18 21 24 ];
M_.mapping.log_SR.eqidx = [74 ];
M_.mapping.util.eqidx = [49 70 ];
M_.mapping.util_ND.eqidx = [47 49 71 ];
M_.mapping.util_D.eqidx = [48 49 72 ];
M_.mapping.g.eqidx = [19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 37 38 39 50 75 76 77 78 79 80 ];
M_.mapping.log_Y.eqidx = [60 67 74 77 ];
M_.mapping.log_C.eqidx = [61 75 ];
M_.mapping.log_I.eqidx = [62 76 ];
M_.mapping.log_N.eqidx = [63 67 74 83 ];
M_.mapping.log_NC.eqidx = [64 84 ];
M_.mapping.log_NI.eqidx = [65 85 ];
M_.mapping.log_K.eqidx = [66 74 79 ];
M_.mapping.log_Y_N.eqidx = [67 78 ];
M_.mapping.log_D.eqidx = [68 89 ];
M_.mapping.log_p_I.eqidx = [69 82 ];
M_.mapping.log_util.eqidx = [70 88 ];
M_.mapping.log_util_ND.eqidx = [71 86 ];
M_.mapping.log_util_D.eqidx = [72 87 ];
M_.mapping.log_W.eqidx = [73 80 ];
M_.mapping.C_obs.eqidx = [75 ];
M_.mapping.I_obs.eqidx = [76 ];
M_.mapping.Y_obs.eqidx = [77 81 ];
M_.mapping.Y_N_obs.eqidx = [78 ];
M_.mapping.p_I_obs.eqidx = [82 ];
M_.mapping.N_obs.eqidx = [81 83 ];
M_.mapping.NC_obs.eqidx = [84 ];
M_.mapping.NI_obs.eqidx = [85 ];
M_.mapping.util_ND_obs.eqidx = [86 ];
M_.mapping.util_D_obs.eqidx = [87 ];
M_.mapping.w_obs.eqidx = [80 ];
M_.mapping.util_obs.eqidx = [88 ];
M_.mapping.D_obs.eqidx = [89 ];
M_.mapping.K_obs.eqidx = [79 81 ];
M_.mapping.SR_obs.eqidx = [81 ];
M_.mapping.e_g.eqidx = [50 ];
M_.mapping.e_g_news.eqidx = [50 ];
M_.mapping.e_Z.eqidx = [51 ];
M_.mapping.e_Z_news.eqidx = [51 ];
M_.mapping.e_ZI.eqidx = [52 ];
M_.mapping.e_ZI_news.eqidx = [52 ];
M_.mapping.e_N.eqidx = [54 ];
M_.mapping.e_D.eqidx = [55 ];
M_.mapping.e_D_news.eqidx = [55 ];
M_.mapping.e_DI.eqidx = [56 ];
M_.mapping.e_DI_news.eqidx = [56 ];
M_.mapping.e_b.eqidx = [57 ];
M_.mapping.e_b_news.eqidx = [57 ];
M_.mapping.e_muC.eqidx = [58 ];
M_.mapping.e_muC_news.eqidx = [58 ];
M_.mapping.e_muI.eqidx = [59 ];
M_.mapping.e_muI_news.eqidx = [59 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [2 6 7 8 10 11 12 19 21 22 23 24 25 26 27 45 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 88 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 ];
M_.exo_names_orig_ord = [1:17];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(121, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(17, 1);
M_.params = NaN(30, 1);
M_.endo_trends = struct('deflator', cell(121, 1), 'log_deflator', cell(121, 1), 'growth_factor', cell(121, 1), 'log_growth_factor', cell(121, 1));
M_.NNZDerivatives = [428; -1; -1; ];
M_.static_tmp_nbr = [61; 13; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 2.0;
sigma = M_.params(1);
M_.params(2) = 0.99;
beta = M_.params(2);
M_.params(3) = 0.0045;
g_bar = M_.params(3);
M_.params(4) = 0.72;
nu = M_.params(4);
M_.params(5) = 0.5;
gam = M_.params(5);
M_.params(15) = 0.1;
ha = M_.params(15);
M_.params(8) = 1.15;
mu_ss = M_.params(8);
M_.params(6) = 0.85;
xi = M_.params(6);
M_.params(7) = 0.65;
omega_sc = M_.params(7);
sigma_ac = 0.32; 
sigma_ai = 0.32;
M_.params(9) = 1.5;
Psi_C = M_.params(9);
M_.params(10) = 1.5;
Psi_I = M_.params(10);
M_.params(11) = 0.20;
I_Y = M_.params(11);
M_.params(12) = 11;
K_Y = M_.params(12);
M_.params(13) = 0.67;
labor_share = M_.params(13);
M_.params(14) = 0.2;
nu_R = M_.params(14);
M_.params(17) = 0.20;
eta = M_.params(17);
M_.params(16) = 0.32;
phi = M_.params(16);
M_.params(18) = 0.81;
Psi = M_.params(18);
M_.params(19) = 0.5;
theta = M_.params(19);
M_.params(29) = 1.0;
p_I_ss = M_.params(29);
M_.params(30) = 0.30;
N_ss = M_.params(30);
M_.params(20) = 0.1;
rho_g = M_.params(20);
M_.params(21) = 0.9;
rho_Z = M_.params(21);
M_.params(22) = 0.9;
rho_ZI = M_.params(22);
M_.params(23) = 0.9;
rho_N = M_.params(23);
M_.params(24) = 0.9;
rho_D = M_.params(24);
M_.params(25) = 0.9;
rho_DI = M_.params(25);
M_.params(26) = 0.9;
rho_b = M_.params(26);
M_.params(27) = 0.9;
rho_muC = M_.params(27);
M_.params(28) = 0.9;
rho_muI = M_.params(28);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 5.184e-05;
M_.Sigma_e(3, 3) = 5.184e-05;
M_.Sigma_e(5, 5) = 5.184e-05;
M_.Sigma_e(7, 7) = 5.184e-05;
M_.Sigma_e(8, 8) = 5.184e-05;
M_.Sigma_e(10, 10) = 5.184e-05;
M_.Sigma_e(12, 12) = 5.184e-05;
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 1, 1.5, 1.0, 4.0, 1, 1.5, 0.25, 1.0, 4.0, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.5, 0.0, 0.95, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, 0.72, 0.05, 2.0, 2, 0.72, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, 0.5, 0.0, 1.0, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.32, 0.00, 0.999, 1, 0.32, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.20, 0.00, 10.0, 2, 0.2, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, 0.85, 0.5, 2.0, 2, 0.85, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 0.20, 0.01, 0.5, 1, 0.2, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, 1.5, 0.0, 50, 2, 4, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, 1.5, 0.0, 50, 2, 4, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, 0.5, .00, 10, 2, 1, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.1, 0.0001, 0.9, 1, 0.1, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.95, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 0.95, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.6, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, 0.9, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, 0.9, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, 0.95, 0.01, 0.99999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, 0.95, 0.01, 0.99999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 28, 0.95, 0.01, 0.99999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.01, 0.00001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.01, 0.00001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.01, 0.00001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.01, 0.00001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 8, 0.01, 0.0001, 0.4, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 9, 0.01, 0.0001, 0.4, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 10, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 11, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 12, 0.01, 0.0001, 0.4, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 13, 0.01, 0.0001, 0.4, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 14, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 15, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 16, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 17, 0.01, 0.0001, 0.2, 2, 0.01, 0.01, NaN, NaN, NaN ];
options_.TeX=1;
options_.TeX = true;
options_.lik_init = 2;
options_.mh_drop = 0.3;
options_.mh_init_scale = 0.0001;
options_.mh_jscale = 0.006;
options_.mh_nblck = 2;
options_.mh_replic = 150000;
options_.mode_check.status = true;
options_.mode_compute = 4;
options_.presample = 0;
options_.prior_trunc = 0;
options_.MCMC_jumping_covariance = 'prior_variance';
options_.datafile = 'observables_sectoral';
options_.optim_opt = '''MaxIter'',200';
options_.order = 1;
var_list_ = {'Y_obs';'Y_N_obs';'I_obs';'p_I_obs';'C_obs';'NC_obs';'NI_obs';'util_ND_obs';'util_D_obs';'w_obs'};
oo_recursive_=dynare_estimation(var_list_);
write_latex_parameter_table;
write_latex_definitions;
write_latex_prior_table;
generate_trace_plots(1);
collect_latex_files;
options_.irf = 0;
options_.nofunctions = true;
options_.order = 1;
options_.periods = 0;
var_list_ = {'Y_obs';'Y_N_obs';'SR_obs';'I_obs';'p_I_obs';'C_obs';'NC_obs';'NI_obs';'util_ND_obs';'util_D_obs';'w_obs'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'BRS_sectoral_wo_vcu_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_wo_vcu_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_wo_vcu_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_wo_vcu_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_wo_vcu_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_wo_vcu_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_sectoral_wo_vcu_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
