%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'directed_search_testing_only_C';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(4,1);
M_.exo_names_tex = cell(4,1);
M_.exo_names_long = cell(4,1);
M_.exo_names(1) = {'e_ZI'};
M_.exo_names_tex(1) = {'e\_ZI'};
M_.exo_names_long(1) = {'e_ZI'};
M_.exo_names(2) = {'e_Z'};
M_.exo_names_tex(2) = {'e\_Z'};
M_.exo_names_long(2) = {'e_Z'};
M_.exo_names(3) = {'e_shop'};
M_.exo_names_tex(3) = {'e\_shop'};
M_.exo_names_long(3) = {'e_shop'};
M_.exo_names(4) = {'e_chi'};
M_.exo_names_tex(4) = {'e\_chi'};
M_.exo_names_long(4) = {'e_chi'};
M_.endo_names = cell(41,1);
M_.endo_names_tex = cell(41,1);
M_.endo_names_long = cell(41,1);
M_.endo_names(1) = {'p_C'};
M_.endo_names_tex(1) = {'p\_C'};
M_.endo_names_long(1) = {'p_C'};
M_.endo_names(2) = {'P_C'};
M_.endo_names_tex(2) = {'P\_C'};
M_.endo_names_long(2) = {'P_C'};
M_.endo_names(3) = {'q_C'};
M_.endo_names_tex(3) = {'q\_C'};
M_.endo_names_long(3) = {'q_C'};
M_.endo_names(4) = {'Q_C'};
M_.endo_names_tex(4) = {'Q\_C'};
M_.endo_names_long(4) = {'Q_C'};
M_.endo_names(5) = {'Q_I'};
M_.endo_names_tex(5) = {'Q\_I'};
M_.endo_names_long(5) = {'Q_I'};
M_.endo_names(6) = {'C'};
M_.endo_names_tex(6) = {'C'};
M_.endo_names_long(6) = {'C'};
M_.endo_names(7) = {'Gamma_C'};
M_.endo_names_tex(7) = {'Gamma\_C'};
M_.endo_names_long(7) = {'Gamma_C'};
M_.endo_names(8) = {'c_A'};
M_.endo_names_tex(8) = {'c\_A'};
M_.endo_names_long(8) = {'c_A'};
M_.endo_names(9) = {'C_util'};
M_.endo_names_tex(9) = {'C\_util'};
M_.endo_names_long(9) = {'C_util'};
M_.endo_names(10) = {'I_util'};
M_.endo_names_tex(10) = {'I\_util'};
M_.endo_names_long(10) = {'I_util'};
M_.endo_names(11) = {'I'};
M_.endo_names_tex(11) = {'I'};
M_.endo_names_long(11) = {'I'};
M_.endo_names(12) = {'I_C'};
M_.endo_names_tex(12) = {'I\_C'};
M_.endo_names_long(12) = {'I_C'};
M_.endo_names(13) = {'I_I'};
M_.endo_names_tex(13) = {'I\_I'};
M_.endo_names_long(13) = {'I_I'};
M_.endo_names(14) = {'w'};
M_.endo_names_tex(14) = {'w'};
M_.endo_names_long(14) = {'w'};
M_.endo_names(15) = {'L_C'};
M_.endo_names_tex(15) = {'L\_C'};
M_.endo_names_long(15) = {'L_C'};
M_.endo_names(16) = {'L_I'};
M_.endo_names_tex(16) = {'L\_I'};
M_.endo_names_long(16) = {'L_I'};
M_.endo_names(17) = {'L'};
M_.endo_names_tex(17) = {'L'};
M_.endo_names_long(17) = {'L'};
M_.endo_names(18) = {'K_C'};
M_.endo_names_tex(18) = {'K\_C'};
M_.endo_names_long(18) = {'K_C'};
M_.endo_names(19) = {'K_I'};
M_.endo_names_tex(19) = {'K\_I'};
M_.endo_names_long(19) = {'K_I'};
M_.endo_names(20) = {'K'};
M_.endo_names_tex(20) = {'K'};
M_.endo_names_long(20) = {'K'};
M_.endo_names(21) = {'lam'};
M_.endo_names_tex(21) = {'lam'};
M_.endo_names_long(21) = {'lam'};
M_.endo_names(22) = {'D'};
M_.endo_names_tex(22) = {'D'};
M_.endo_names_long(22) = {'D'};
M_.endo_names(23) = {'u_C'};
M_.endo_names_tex(23) = {'u\_C'};
M_.endo_names_long(23) = {'u_C'};
M_.endo_names(24) = {'u_I'};
M_.endo_names_tex(24) = {'u\_I'};
M_.endo_names_long(24) = {'u_I'};
M_.endo_names(25) = {'cu'};
M_.endo_names_tex(25) = {'cu'};
M_.endo_names_long(25) = {'cu'};
M_.endo_names(26) = {'Z'};
M_.endo_names_tex(26) = {'Z'};
M_.endo_names_long(26) = {'Z'};
M_.endo_names(27) = {'Z_I'};
M_.endo_names_tex(27) = {'Z\_I'};
M_.endo_names_long(27) = {'Z_I'};
M_.endo_names(28) = {'u_ZI'};
M_.endo_names_tex(28) = {'u\_ZI'};
M_.endo_names_long(28) = {'u_ZI'};
M_.endo_names(29) = {'zeta'};
M_.endo_names_tex(29) = {'zeta'};
M_.endo_names_long(29) = {'zeta'};
M_.endo_names(30) = {'kappa'};
M_.endo_names_tex(30) = {'kappa'};
M_.endo_names_long(30) = {'kappa'};
M_.endo_names(31) = {'u_shop'};
M_.endo_names_tex(31) = {'u\_shop'};
M_.endo_names_long(31) = {'u_shop'};
M_.endo_names(32) = {'chi'};
M_.endo_names_tex(32) = {'chi'};
M_.endo_names_long(32) = {'chi'};
M_.endo_names(33) = {'Y_obs'};
M_.endo_names_tex(33) = {'Y\_obs'};
M_.endo_names_long(33) = {'Y_obs'};
M_.endo_names(34) = {'C_obs'};
M_.endo_names_tex(34) = {'C\_obs'};
M_.endo_names_long(34) = {'C_obs'};
M_.endo_names(35) = {'TI_obs'};
M_.endo_names_tex(35) = {'TI\_obs'};
M_.endo_names_long(35) = {'TI_obs'};
M_.endo_names(36) = {'p_I_obs'};
M_.endo_names_tex(36) = {'p\_I\_obs'};
M_.endo_names_long(36) = {'p_I_obs'};
M_.endo_names(37) = {'lab_prod_obs'};
M_.endo_names_tex(37) = {'lab\_prod\_obs'};
M_.endo_names_long(37) = {'lab_prod_obs'};
M_.endo_names(38) = {'SR_obs'};
M_.endo_names_tex(38) = {'SR\_obs'};
M_.endo_names_long(38) = {'SR_obs'};
M_.endo_names(39) = {'SR_util_obs'};
M_.endo_names_tex(39) = {'SR\_util\_obs'};
M_.endo_names_long(39) = {'SR_util_obs'};
M_.endo_names(40) = {'Y_util_obs'};
M_.endo_names_tex(40) = {'Y\_util\_obs'};
M_.endo_names_long(40) = {'Y_util_obs'};
M_.endo_names(41) = {'AUX_ENDO_LAG_31_1'};
M_.endo_names_tex(41) = {'AUX\_ENDO\_LAG\_31\_1'};
M_.endo_names_long(41) = {'AUX_ENDO_LAG_31_1'};
M_.endo_partitions = struct();
M_.param_names = cell(18,1);
M_.param_names_tex = cell(18,1);
M_.param_names_long = cell(18,1);
M_.param_names(1) = {'A'};
M_.param_names_tex(1) = {'A'};
M_.param_names_long(1) = {'A'};
M_.param_names(2) = {'beta'};
M_.param_names_tex(2) = {'beta'};
M_.param_names_long(2) = {'beta'};
M_.param_names(3) = {'sigma_a'};
M_.param_names_tex(3) = {'sigma\_a'};
M_.param_names_long(3) = {'sigma_a'};
M_.param_names(4) = {'psi_inv'};
M_.param_names_tex(4) = {'psi\_inv'};
M_.param_names_long(4) = {'psi_inv'};
M_.param_names(5) = {'sigma'};
M_.param_names_tex(5) = {'sigma'};
M_.param_names_long(5) = {'sigma'};
M_.param_names(6) = {'var_share'};
M_.param_names_tex(6) = {'var\_share'};
M_.param_names_long(6) = {'var_share'};
M_.param_names(7) = {'Gamma_bar'};
M_.param_names_tex(7) = {'Gamma\_bar'};
M_.param_names_long(7) = {'Gamma_bar'};
M_.param_names(8) = {'wL_Y'};
M_.param_names_tex(8) = {'wL\_Y'};
M_.param_names_long(8) = {'wL_Y'};
M_.param_names(9) = {'phi_I'};
M_.param_names_tex(9) = {'phi\_I'};
M_.param_names_long(9) = {'phi_I'};
M_.param_names(10) = {'Psi'};
M_.param_names_tex(10) = {'Psi'};
M_.param_names_long(10) = {'Psi'};
M_.param_names(11) = {'Psi_K'};
M_.param_names_tex(11) = {'Psi\_K'};
M_.param_names_long(11) = {'Psi_K'};
M_.param_names(12) = {'gam'};
M_.param_names_tex(12) = {'gam'};
M_.param_names_long(12) = {'gam'};
M_.param_names(13) = {'rho_Z'};
M_.param_names_tex(13) = {'rho\_Z'};
M_.param_names_long(13) = {'rho_Z'};
M_.param_names(14) = {'rho_ZI'};
M_.param_names_tex(14) = {'rho\_ZI'};
M_.param_names_long(14) = {'rho_ZI'};
M_.param_names(15) = {'rho_shop'};
M_.param_names_tex(15) = {'rho\_shop'};
M_.param_names_long(15) = {'rho_shop'};
M_.param_names(16) = {'rho_zeta'};
M_.param_names_tex(16) = {'rho\_zeta'};
M_.param_names_long(16) = {'rho_zeta'};
M_.param_names(17) = {'lambda_1'};
M_.param_names_tex(17) = {'lambda\_1'};
M_.param_names_long(17) = {'lambda_1'};
M_.param_names(18) = {'lambda_2'};
M_.param_names_tex(18) = {'lambda\_2'};
M_.param_names_long(18) = {'lambda_2'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 41;
M_.param_nbr = 18;
M_.orig_endo_nbr = 40;
M_.aux_vars(1).endo_index = 41;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 32;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(1).orig_expr = 'chi(-1)';
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 40;
M_.eq_nbr = 41;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 2;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 2;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 2;
M_.lead_lag_incidence = [
 0 12 0;
 0 13 0;
 0 14 0;
 0 15 53;
 0 16 54;
 0 17 55;
 0 18 56;
 0 19 0;
 0 20 0;
 0 21 0;
 0 22 57;
 1 23 0;
 2 24 0;
 0 25 0;
 0 26 0;
 0 27 0;
 0 28 0;
 3 29 58;
 4 30 59;
 0 31 0;
 0 32 60;
 0 33 0;
 5 34 61;
 6 35 62;
 0 36 0;
 7 37 0;
 8 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 9 42 0;
 10 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 11 52 0;]';
M_.nstatic = 24;
M_.nfwrd   = 6;
M_.npred   = 7;
M_.nboth   = 4;
M_.nsfwrd   = 10;
M_.nspred   = 11;
M_.ndynamic   = 17;
M_.dynamic_tmp_nbr = [5; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Variety effect: household' ;
  2 , 'name' , 'Consumption aggregation' ;
  3 , 'name' , 'Markup (consumption)' ;
  4 , 'name' , 'Labor in retail' ;
  5 , 'name' , 'Labor in investment' ;
  6 , 'name' , 'Labor intratemporal' ;
  7 , 'name' , 'Capital accumulation (consumption)' ;
  8 , 'name' , 'Capital accumulation (investment)' ;
  9 , 'name' , 'HH shopping' ;
  10 , 'name' , 'Consumption multiplier' ;
  11 , 'name' , 'Euler equation of capital (C))' ;
  12 , 'name' , 'Euler equation of capital (I)' ;
  13 , 'name' , 'Capital utilization (C)' ;
  14 , 'name' , 'Capital utilization (I)' ;
  15 , 'name' , 'Relative price of capital good: consumption' ;
  16 , 'name' , 'Relative price of capital good: investment' ;
  17 , 'name' , 'Relative price of investment' ;
  18 , 'name' , 'Retail production' ;
  19 , 'name' , 'Investment production' ;
  20 , 'name' , 'C_util' ;
  21 , 'name' , 'Investment (utilization-adjusted)' ;
  22 , 'name' , 'Labor composition' ;
  23 , 'name' , 'Capital composition' ;
  24 , 'name' , 'Investment composition' ;
  25 , 'name' , 'Capacity utilization' ;
  26 , 'name' , 'Aggregate accounting (income = expenditures)' ;
  27 , 'name' , 'Z' ;
  28 , 'name' , 'u_ZI' ;
  29 , 'name' , 'Z_I' ;
  30 , 'name' , 'u_shop' ;
  31 , 'name' , 'kappa' ;
  32 , 'name' , 'zeta' ;
  33 , 'name' , 'chi' ;
  34 , 'name' , 'C_obs' ;
  35 , 'name' , 'TI_obs' ;
  36 , 'name' , 'Y_obs' ;
  37 , 'name' , 'Y_util_obs' ;
  38 , 'name' , 'SR_obs' ;
  39 , 'name' , 'SR_util_obs' ;
  40 , 'name' , 'lab_prod_obs' ;
};
M_.mapping.p_C.eqidx = [1 17 18 20 34 36 37 ];
M_.mapping.P_C.eqidx = [1 2 6 10 ];
M_.mapping.q_C.eqidx = [1 3 9 18 25 ];
M_.mapping.Q_C.eqidx = [11 13 15 ];
M_.mapping.Q_I.eqidx = [12 14 16 ];
M_.mapping.C.eqidx = [2 4 11 13 18 26 34 36 ];
M_.mapping.Gamma_C.eqidx = [3 4 11 13 ];
M_.mapping.c_A.eqidx = [2 6 9 10 ];
M_.mapping.C_util.eqidx = [20 37 ];
M_.mapping.I_util.eqidx = [21 37 ];
M_.mapping.I.eqidx = [5 12 14 19 24 35 36 ];
M_.mapping.I_C.eqidx = [7 15 24 ];
M_.mapping.I_I.eqidx = [8 16 24 ];
M_.mapping.w.eqidx = [4 5 6 ];
M_.mapping.L_C.eqidx = [4 18 20 22 ];
M_.mapping.L_I.eqidx = [5 19 21 22 ];
M_.mapping.L.eqidx = [6 22 38 39 40 ];
M_.mapping.K_C.eqidx = [7 11 13 15 18 20 23 ];
M_.mapping.K_I.eqidx = [8 12 14 16 19 21 23 ];
M_.mapping.K.eqidx = [23 38 39 ];
M_.mapping.lam.eqidx = [10 11 12 ];
M_.mapping.D.eqidx = [26 ];
M_.mapping.u_C.eqidx = [7 11 13 18 25 ];
M_.mapping.u_I.eqidx = [8 12 14 19 25 ];
M_.mapping.cu.eqidx = [25 ];
M_.mapping.Z.eqidx = [18 20 27 29 ];
M_.mapping.Z_I.eqidx = [19 21 28 29 ];
M_.mapping.u_ZI.eqidx = [28 29 ];
M_.mapping.zeta.eqidx = [32 ];
M_.mapping.kappa.eqidx = [9 31 ];
M_.mapping.u_shop.eqidx = [30 31 32 ];
M_.mapping.chi.eqidx = [6 33 ];
M_.mapping.Y_obs.eqidx = [36 38 40 ];
M_.mapping.C_obs.eqidx = [34 ];
M_.mapping.TI_obs.eqidx = [35 ];
M_.mapping.p_I_obs.eqidx = [17 ];
M_.mapping.lab_prod_obs.eqidx = [40 ];
M_.mapping.SR_obs.eqidx = [38 ];
M_.mapping.SR_util_obs.eqidx = [39 ];
M_.mapping.Y_util_obs.eqidx = [37 39 ];
M_.mapping.e_ZI.eqidx = [28 ];
M_.mapping.e_Z.eqidx = [27 ];
M_.mapping.e_shop.eqidx = [30 ];
M_.mapping.e_chi.eqidx = [33 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [12 13 18 19 23 24 26 27 31 32 41 ];
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(41, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(18, 1);
M_.endo_trends = struct('deflator', cell(41, 1), 'log_deflator', cell(41, 1), 'growth_factor', cell(41, 1), 'log_growth_factor', cell(41, 1));
M_.NNZDerivatives = [148; 0; -1; ];
M_.static_tmp_nbr = [5; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(2) = 0.993;
beta = M_.params(2);
M_.params(4) = 0.72;
psi_inv = M_.params(4);
phi = 0.5;
M_.params(5) = 1.0;
sigma = M_.params(5);
M_.params(11) = 4.0;
Psi_K = M_.params(11);
M_.params(14) = 0.979;
rho_ZI = M_.params(14);
M_.params(13) = 0.979;
rho_Z = M_.params(13);
M_.params(15) = 0.979;
rho_shop = M_.params(15);
M_.params(16) = 0.979;
rho_zeta = M_.params(16);
M_.params(17) = 0.979;
lambda_1 = M_.params(17);
M_.params(18) = 0.0;
lambda_2 = M_.params(18);
M_.params(8) = 0.667;
wL_Y = M_.params(8);
M_.params(9) = 0.22;
phi_I = M_.params(9);
M_.params(6) = 0.5;
var_share = M_.params(6);
M_.params(1) = 0.78;
A = M_.params(1);
M_.params(10) = 0.5;
Psi = M_.params(10);
M_.params(12) = 0.42;
gam = M_.params(12);
M_.params(7) = 1.2;
Gamma_bar = M_.params(7);
M_.params(3) = 0.32;
sigma_a = M_.params(3);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0.0072;
M_.Sigma_e(2, 2) = 0.0072;
M_.Sigma_e(3, 3) = 0.0072;
options_.irf = 100;
options_.nofunctions = true;
options_.order = 1;
options_.periods = 0;
options_.conditional_variance_decomposition = [1;4;8;40;];
var_list_ = {'C_obs';'Y_obs';'D';'lab_prod_obs';'SR_obs';'cu';'TI_obs';'L_C';'L_I';'L';'p_I_obs';'Gamma_C'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'directed_search_testing_only_C_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_testing_only_C_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_testing_only_C_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_testing_only_C_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_testing_only_C_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_testing_only_C_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'directed_search_testing_only_C_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
