%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'BRS_pred_labor';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(7,1);
M_.exo_names_tex = cell(7,1);
M_.exo_names_long = cell(7,1);
M_.exo_names(1) = {'e_g'};
M_.exo_names_tex(1) = {'{e_g}'};
M_.exo_names_long(1) = {'Stochastic trend shock'};
M_.exo_names(2) = {'e_Z'};
M_.exo_names_tex(2) = {'{e_Z}'};
M_.exo_names_long(2) = {'TFP shock'};
M_.exo_names(3) = {'e_ZI'};
M_.exo_names_tex(3) = {'{e_{ZI}}'};
M_.exo_names_long(3) = {'Investment-specific tech shock'};
M_.exo_names(4) = {'e_N'};
M_.exo_names_tex(4) = {'{e_N}'};
M_.exo_names_long(4) = {'Labor supply shock'};
M_.exo_names(5) = {'e_D'};
M_.exo_names_tex(5) = {'{e_D}'};
M_.exo_names_long(5) = {'Shopping disutility shock'};
M_.exo_names(6) = {'e_DI'};
M_.exo_names_tex(6) = {'{e_DI}'};
M_.exo_names_long(6) = {'Relative investment shopping disutility shock'};
M_.exo_names(7) = {'e_C'};
M_.exo_names_tex(7) = {'{e_C}'};
M_.exo_names_long(7) = {'Consumption preference shock'};
M_.endo_names = cell(61,1);
M_.endo_names_tex = cell(61,1);
M_.endo_names_long = cell(61,1);
M_.endo_names(1) = {'Y'};
M_.endo_names_tex(1) = {'{Y}'};
M_.endo_names_long(1) = {'output'};
M_.endo_names(2) = {'C'};
M_.endo_names_tex(2) = {'{C}'};
M_.endo_names_long(2) = {'consumption'};
M_.endo_names(3) = {'I'};
M_.endo_names_tex(3) = {'{I}'};
M_.endo_names_long(3) = {'investment'};
M_.endo_names(4) = {'K'};
M_.endo_names_tex(4) = {'{K}'};
M_.endo_names_long(4) = {'Capital'};
M_.endo_names(5) = {'K_C'};
M_.endo_names_tex(5) = {'{K_C}'};
M_.endo_names_long(5) = {'Capital:C'};
M_.endo_names(6) = {'K_I'};
M_.endo_names_tex(6) = {'{K_I}'};
M_.endo_names_long(6) = {'Capital:I'};
M_.endo_names(7) = {'N'};
M_.endo_names_tex(7) = {'{N}'};
M_.endo_names_long(7) = {'Hours'};
M_.endo_names(8) = {'N_C'};
M_.endo_names_tex(8) = {'{N_C}'};
M_.endo_names_long(8) = {'Hours:C'};
M_.endo_names(9) = {'N_I'};
M_.endo_names_tex(9) = {'{N_I}'};
M_.endo_names_long(9) = {'Hours:I'};
M_.endo_names(10) = {'Z_C'};
M_.endo_names_tex(10) = {'{Z_C}'};
M_.endo_names_long(10) = {'Tech:C'};
M_.endo_names(11) = {'u_ZI'};
M_.endo_names_tex(11) = {'u\_ZI'};
M_.endo_names_long(11) = {'u_ZI'};
M_.endo_names(12) = {'Z_I'};
M_.endo_names_tex(12) = {'{Z_I}'};
M_.endo_names_long(12) = {'Tech:I'};
M_.endo_names(13) = {'theta_N'};
M_.endo_names_tex(13) = {'{\theta_N}'};
M_.endo_names_long(13) = {'Labor disutility'};
M_.endo_names(14) = {'theta_D'};
M_.endo_names_tex(14) = {'{\theta_D}'};
M_.endo_names_long(14) = {'Shopping disutility'};
M_.endo_names(15) = {'theta_I'};
M_.endo_names_tex(15) = {'{\theta_I}'};
M_.endo_names_long(15) = {'Relative shopping disutility'};
M_.endo_names(16) = {'theta_C'};
M_.endo_names_tex(16) = {'{\theta_C}'};
M_.endo_names_long(16) = {'Consumption preference shock'};
M_.endo_names(17) = {'R_C'};
M_.endo_names_tex(17) = {'{R_C}'};
M_.endo_names_long(17) = {'Capital rental rate:C'};
M_.endo_names(18) = {'R_I'};
M_.endo_names_tex(18) = {'{R_I}'};
M_.endo_names_long(18) = {'Capital rental rate:I'};
M_.endo_names(19) = {'W_C'};
M_.endo_names_tex(19) = {'{W}'};
M_.endo_names_long(19) = {'Real wage:C'};
M_.endo_names(20) = {'W_I'};
M_.endo_names_tex(20) = {'{W}'};
M_.endo_names_long(20) = {'Real wage:I'};
M_.endo_names(21) = {'h_C'};
M_.endo_names_tex(21) = {'{h_C}'};
M_.endo_names_long(21) = {'Capital utilization rate:C'};
M_.endo_names(22) = {'h_I'};
M_.endo_names_tex(22) = {'{h_I}'};
M_.endo_names_long(22) = {'Capital utilization rate:I'};
M_.endo_names(23) = {'delta_C'};
M_.endo_names_tex(23) = {'{\delta_C}'};
M_.endo_names_long(23) = {'Capital depreciation rate:C'};
M_.endo_names(24) = {'delta_I'};
M_.endo_names_tex(24) = {'{\delta_I}'};
M_.endo_names_long(24) = {'Capital depreciation rate:I'};
M_.endo_names(25) = {'delta_C_pr'};
M_.endo_names_tex(25) = {'{\delta_C}'};
M_.endo_names_long(25) = {'Capital depreciation rate derivative:C'};
M_.endo_names(26) = {'delta_I_pr'};
M_.endo_names_tex(26) = {'{\delta_I}'};
M_.endo_names_long(26) = {'Capital depreciation rate derivative:I'};
M_.endo_names(27) = {'S'};
M_.endo_names_tex(27) = {'S'};
M_.endo_names_long(27) = {'Investment adjustment cost'};
M_.endo_names(28) = {'S_pr'};
M_.endo_names_tex(28) = {'S_pr'};
M_.endo_names_long(28) = {'Derivative investment adjustment cost'};
M_.endo_names(29) = {'D'};
M_.endo_names_tex(29) = {'{D}'};
M_.endo_names_long(29) = {'Shopping effort'};
M_.endo_names(30) = {'D_C'};
M_.endo_names_tex(30) = {'{D}'};
M_.endo_names_long(30) = {'Shopping effort:C'};
M_.endo_names(31) = {'D_I'};
M_.endo_names_tex(31) = {'{D}'};
M_.endo_names_long(31) = {'Shopping effort:I'};
M_.endo_names(32) = {'Gam'};
M_.endo_names_tex(32) = {'{\Gamma}'};
M_.endo_names_long(32) = {'Composite utility term'};
M_.endo_names(33) = {'p_I'};
M_.endo_names_tex(33) = {'{p_I}'};
M_.endo_names_long(33) = {'Relative investment price'};
M_.endo_names(34) = {'Q'};
M_.endo_names_tex(34) = {'{Q}'};
M_.endo_names_long(34) = {'Relative price of capital'};
M_.endo_names(35) = {'x'};
M_.endo_names_tex(35) = {'{x}'};
M_.endo_names_long(35) = {'Growth rate of investment'};
M_.endo_names(36) = {'log_SR'};
M_.endo_names_tex(36) = {'log\_SR'};
M_.endo_names_long(36) = {'Solow residual'};
M_.endo_names(37) = {'util'};
M_.endo_names_tex(37) = {'{util}'};
M_.endo_names_long(37) = {'Capacity utilization:'};
M_.endo_names(38) = {'g'};
M_.endo_names_tex(38) = {'{g}'};
M_.endo_names_long(38) = {'Growth rate of stochastic trend'};
M_.endo_names(39) = {'log_Y'};
M_.endo_names_tex(39) = {'log\_Y'};
M_.endo_names_long(39) = {'log_Y'};
M_.endo_names(40) = {'log_C'};
M_.endo_names_tex(40) = {'log\_C'};
M_.endo_names_long(40) = {'log_C'};
M_.endo_names(41) = {'log_I'};
M_.endo_names_tex(41) = {'log\_I'};
M_.endo_names_long(41) = {'log_I'};
M_.endo_names(42) = {'log_N'};
M_.endo_names_tex(42) = {'log\_N'};
M_.endo_names_long(42) = {'log_N'};
M_.endo_names(43) = {'log_NC'};
M_.endo_names_tex(43) = {'log\_NC'};
M_.endo_names_long(43) = {'log_NC'};
M_.endo_names(44) = {'log_NI'};
M_.endo_names_tex(44) = {'log\_NI'};
M_.endo_names_long(44) = {'log_NI'};
M_.endo_names(45) = {'log_K'};
M_.endo_names_tex(45) = {'log\_K'};
M_.endo_names_long(45) = {'log_K'};
M_.endo_names(46) = {'log_Y_N'};
M_.endo_names_tex(46) = {'log\_Y\_N'};
M_.endo_names_long(46) = {'log_Y_N'};
M_.endo_names(47) = {'log_D'};
M_.endo_names_tex(47) = {'log\_D'};
M_.endo_names_long(47) = {'log_D'};
M_.endo_names(48) = {'log_p_I'};
M_.endo_names_tex(48) = {'log\_p\_I'};
M_.endo_names_long(48) = {'log_p_I'};
M_.endo_names(49) = {'log_util'};
M_.endo_names_tex(49) = {'log\_util'};
M_.endo_names_long(49) = {'log_util'};
M_.endo_names(50) = {'C_obs'};
M_.endo_names_tex(50) = {'C\_obs'};
M_.endo_names_long(50) = {'C_obs'};
M_.endo_names(51) = {'I_obs'};
M_.endo_names_tex(51) = {'I\_obs'};
M_.endo_names_long(51) = {'I_obs'};
M_.endo_names(52) = {'Y_obs'};
M_.endo_names_tex(52) = {'Y\_obs'};
M_.endo_names_long(52) = {'Y_obs'};
M_.endo_names(53) = {'Y_N_obs'};
M_.endo_names_tex(53) = {'Y\_N\_obs'};
M_.endo_names_long(53) = {'Y_N_obs'};
M_.endo_names(54) = {'p_I_obs'};
M_.endo_names_tex(54) = {'p\_I\_obs'};
M_.endo_names_long(54) = {'p_I_obs'};
M_.endo_names(55) = {'N_obs'};
M_.endo_names_tex(55) = {'N\_obs'};
M_.endo_names_long(55) = {'N_obs'};
M_.endo_names(56) = {'NC_obs'};
M_.endo_names_tex(56) = {'NC\_obs'};
M_.endo_names_long(56) = {'NC_obs'};
M_.endo_names(57) = {'NI_obs'};
M_.endo_names_tex(57) = {'NI\_obs'};
M_.endo_names_long(57) = {'NI_obs'};
M_.endo_names(58) = {'util_obs'};
M_.endo_names_tex(58) = {'util\_obs'};
M_.endo_names_long(58) = {'util_obs'};
M_.endo_names(59) = {'D_obs'};
M_.endo_names_tex(59) = {'D\_obs'};
M_.endo_names_long(59) = {'D_obs'};
M_.endo_names(60) = {'K_obs'};
M_.endo_names_tex(60) = {'K\_obs'};
M_.endo_names_long(60) = {'K_obs'};
M_.endo_names(61) = {'SR_obs'};
M_.endo_names_tex(61) = {'SR\_obs'};
M_.endo_names_long(61) = {'SR_obs'};
M_.endo_partitions = struct();
M_.param_names = cell(23,1);
M_.param_names_tex = cell(23,1);
M_.param_names_long = cell(23,1);
M_.param_names(1) = {'gam'};
M_.param_names_tex(1) = {'{\gamma}'};
M_.param_names_long(1) = {'Risk aversion'};
M_.param_names(2) = {'gam_max'};
M_.param_names_tex(2) = {'{\gamma_{max}}'};
M_.param_names_long(2) = {'Upper bound on risk aversion'};
M_.param_names(3) = {'r_ann'};
M_.param_names_tex(3) = {'{r_ann}'};
M_.param_names_long(3) = {'Annual interest rate'};
M_.param_names(4) = {'g_bar'};
M_.param_names_tex(4) = {'{\overline{g}}'};
M_.param_names_long(4) = {'Quarterly trend growth rate'};
M_.param_names(5) = {'nu'};
M_.param_names_tex(5) = {'\nu'};
M_.param_names_long(5) = {'Frisch elasticity'};
M_.param_names(6) = {'sigma_a'};
M_.param_names_tex(6) = {'{\sigma_a}'};
M_.param_names_long(6) = {'Inverse elasticity of marginal utilization cost wrt rental rate'};
M_.param_names(7) = {'Psi_K'};
M_.param_names_tex(7) = {'{\Psi_K}'};
M_.param_names_long(7) = {'Investment adjustment cost parameter'};
M_.param_names(8) = {'I_Y'};
M_.param_names_tex(8) = {'{I_Y}'};
M_.param_names_long(8) = {'Investment-output ratio'};
M_.param_names(9) = {'K_Y'};
M_.param_names_tex(9) = {'{K_Y}'};
M_.param_names_long(9) = {'Capital-output ratio (quarterly)'};
M_.param_names(10) = {'labor_share'};
M_.param_names_tex(10) = {'(labor share)'};
M_.param_names_long(10) = {'Labor share'};
M_.param_names(11) = {'nu_R'};
M_.param_names_tex(11) = {'{\nu_R}'};
M_.param_names_long(11) = {'Fixed cost share'};
M_.param_names(12) = {'m'};
M_.param_names_tex(12) = {'{m}'};
M_.param_names_long(12) = {'Ratio of price dispersion to consumption dispersion'};
M_.param_names(13) = {'eta'};
M_.param_names_tex(13) = {'{\eta}'};
M_.param_names_long(13) = {'Shopping disutility'};
M_.param_names(14) = {'Psi'};
M_.param_names_tex(14) = {'{\Psi}'};
M_.param_names_long(14) = {'Matching utilization'};
M_.param_names(15) = {'rho_g'};
M_.param_names_tex(15) = {'{\rho_g}'};
M_.param_names_long(15) = {'persistence TFP growth shock'};
M_.param_names(16) = {'rho_Z'};
M_.param_names_tex(16) = {'{\rho_Z}'};
M_.param_names_long(16) = {'persistence TFP shock'};
M_.param_names(17) = {'rho_ZI'};
M_.param_names_tex(17) = {'{\rho_{ZI}}'};
M_.param_names_long(17) = {'persistence I-specific shock'};
M_.param_names(18) = {'rho_N'};
M_.param_names_tex(18) = {'{\rho_N}'};
M_.param_names_long(18) = {'persistence labor supply shock'};
M_.param_names(19) = {'rho_D'};
M_.param_names_tex(19) = {'{\rho_D}'};
M_.param_names_long(19) = {'persistence shopping effort shock'};
M_.param_names(20) = {'rho_DI'};
M_.param_names_tex(20) = {'{\rho_{DI}}'};
M_.param_names_long(20) = {'persistence relative shopping effort shock'};
M_.param_names(21) = {'rho_C'};
M_.param_names_tex(21) = {'{\rho_C}'};
M_.param_names_long(21) = {'persistence consumption preference shock'};
M_.param_names(22) = {'p_I_ss'};
M_.param_names_tex(22) = {'p\_I\_ss'};
M_.param_names_long(22) = {'p_I_ss'};
M_.param_names(23) = {'N_ss'};
M_.param_names_tex(23) = {'N\_ss'};
M_.param_names_long(23) = {'N_ss'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 61;
M_.param_nbr = 23;
M_.orig_endo_nbr = 61;
M_.aux_vars = [];
options_.varobs = cell(5, 1);
options_.varobs(1)  = {'I_obs'};
options_.varobs(2)  = {'Y_obs'};
options_.varobs(3)  = {'Y_N_obs'};
options_.varobs(4)  = {'p_I_obs'};
options_.varobs(5)  = {'util_obs'};
options_.varobs_id = [ 51 52 53 54 58  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 61;
M_.eq_nbr = 61;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 25 0;
 0 26 0;
 1 27 0;
 0 28 0;
 2 29 0;
 3 30 0;
 0 31 0;
 4 32 0;
 5 33 0;
 6 34 0;
 0 35 0;
 7 36 0;
 8 37 86;
 9 38 0;
 10 39 0;
 11 40 87;
 0 41 88;
 0 42 89;
 0 43 90;
 0 44 91;
 0 45 92;
 0 46 93;
 0 47 94;
 0 48 95;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 96;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 97;
 0 57 0;
 0 58 98;
 0 59 99;
 0 60 0;
 0 61 0;
 12 62 100;
 13 63 0;
 14 64 0;
 15 65 0;
 16 66 0;
 17 67 0;
 18 68 0;
 19 69 0;
 20 70 0;
 21 71 0;
 22 72 0;
 23 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 24 84 0;
 0 85 0;]';
M_.nstatic = 25;
M_.nfwrd   = 12;
M_.npred   = 21;
M_.nboth   = 3;
M_.nsfwrd   = 15;
M_.nspred   = 24;
M_.ndynamic   = 36;
M_.dynamic_tmp_nbr = [47; 18; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Labor leisure' ;
  2 , 'name' , '2' ;
  3 , 'name' , 'Shopping:C' ;
  4 , 'name' , 'Shopping:I' ;
  5 , 'name' , 'Composite utility term' ;
  6 , 'name' , 'Investment adjustment cost function' ;
  7 , 'name' , 'Investment adjustment cost function: derivative' ;
  8 , 'name' , 'Investment growth' ;
  9 , 'name' , 'Tobins Q' ;
  10 , 'name' , 'Euler equation: C' ;
  11 , 'name' , 'Euler equation: I' ;
  12 , 'name' , 'Utilization: C' ;
  13 , 'name' , 'Utilization: I' ;
  14 , 'name' , 'Depreciation rate: C' ;
  15 , 'name' , 'Depreciation rate: I' ;
  16 , 'name' , 'Depreciation rate derivative: C' ;
  17 , 'name' , 'Depreciation rate derivative: I' ;
  18 , 'name' , 'Consumption production' ;
  19 , 'name' , 'Investment production' ;
  20 , 'name' , 'Capital law of motion' ;
  21 , 'name' , 'Labor demand:C' ;
  22 , 'name' , 'Labor demand:I' ;
  23 , 'name' , 'Capital demand:C' ;
  24 , 'name' , 'Capital demand:I' ;
  25 , 'name' , 'Labor composition' ;
  26 , 'name' , 'Capital composition' ;
  27 , 'name' , 'Shopping composition' ;
  28 , 'name' , 'Output (base-year prices)' ;
  29 , 'name' , 'Capacity utilization' ;
  30 , 'name' , 'stochastic trend process' ;
  31 , 'name' , 'Stationary TFP process' ;
  32 , 'name' , 'Independent component of I-specific tech' ;
  33 , 'name' , 'Investment-specific TFP process' ;
  34 , 'name' , 'Labor supply process' ;
  35 , 'name' , 'Shopping effort process' ;
  36 , 'name' , 'Relative shopping effort process' ;
  37 , 'name' , 'Consumption preference process' ;
  38 , 'name' , 'Definition log output' ;
  39 , 'name' , 'Definition log consumption' ;
  40 , 'name' , 'Definition log investment' ;
  41 , 'name' , 'Definition log hours' ;
  42 , 'name' , 'log_NC' ;
  43 , 'name' , 'log_NI' ;
  44 , 'name' , 'log capital' ;
  45 , 'name' , 'Definition log labor productivity' ;
  46 , 'name' , 'Definition log shopping effort' ;
  47 , 'name' , 'Definition of log relative investment  price' ;
  48 , 'name' , 'Definition of log capacity utilization' ;
  49 , 'name' , 'Definition of log Solow residual' ;
  50 , 'name' , 'C_obs' ;
  51 , 'name' , 'I_obs' ;
  52 , 'name' , 'Y_obs' ;
  53 , 'name' , 'Y_N_obs' ;
  54 , 'name' , 'K_obs' ;
  55 , 'name' , 'SR_obs' ;
  56 , 'name' , 'p_I_obs' ;
  57 , 'name' , 'N_obs' ;
  58 , 'name' , 'NC_obs' ;
  59 , 'name' , 'NI_obs' ;
  60 , 'name' , 'util_obs' ;
  61 , 'name' , 'D_obs' ;
};
M_.mapping.Y.eqidx = [28 29 38 ];
M_.mapping.C.eqidx = [3 5 18 21 23 28 29 39 ];
M_.mapping.I.eqidx = [4 8 19 20 22 24 28 29 40 ];
M_.mapping.K.eqidx = [26 44 ];
M_.mapping.K_C.eqidx = [18 20 23 26 29 ];
M_.mapping.K_I.eqidx = [19 20 24 26 29 ];
M_.mapping.N.eqidx = [1 2 5 25 41 ];
M_.mapping.N_C.eqidx = [18 21 25 29 42 ];
M_.mapping.N_I.eqidx = [19 22 25 29 43 ];
M_.mapping.Z_C.eqidx = [18 31 33 ];
M_.mapping.u_ZI.eqidx = [32 33 ];
M_.mapping.Z_I.eqidx = [19 32 33 ];
M_.mapping.theta_N.eqidx = [1 2 5 34 ];
M_.mapping.theta_D.eqidx = [3 4 5 35 ];
M_.mapping.theta_I.eqidx = [4 36 ];
M_.mapping.theta_C.eqidx = [1 2 3 4 5 9 10 11 37 ];
M_.mapping.R_C.eqidx = [10 12 23 ];
M_.mapping.R_I.eqidx = [11 13 24 ];
M_.mapping.W_C.eqidx = [1 21 ];
M_.mapping.W_I.eqidx = [2 22 ];
M_.mapping.h_C.eqidx = [10 14 16 18 23 29 ];
M_.mapping.h_I.eqidx = [11 15 17 19 24 29 ];
M_.mapping.delta_C.eqidx = [10 14 20 ];
M_.mapping.delta_I.eqidx = [11 15 20 ];
M_.mapping.delta_C_pr.eqidx = [12 16 ];
M_.mapping.delta_I_pr.eqidx = [13 17 ];
M_.mapping.S.eqidx = [6 9 20 ];
M_.mapping.S_pr.eqidx = [7 9 ];
M_.mapping.D.eqidx = [3 4 5 27 46 ];
M_.mapping.D_C.eqidx = [3 18 21 23 27 29 ];
M_.mapping.D_I.eqidx = [4 19 22 24 27 29 ];
M_.mapping.Gam.eqidx = [5 9 10 11 ];
M_.mapping.p_I.eqidx = [4 9 22 24 47 ];
M_.mapping.Q.eqidx = [9 10 11 12 13 ];
M_.mapping.x.eqidx = [6 7 8 9 ];
M_.mapping.log_SR.eqidx = [49 ];
M_.mapping.util.eqidx = [29 48 ];
M_.mapping.g.eqidx = [8 9 10 11 18 19 20 23 24 30 50 51 52 53 54 ];
M_.mapping.log_Y.eqidx = [38 45 49 52 ];
M_.mapping.log_C.eqidx = [39 50 ];
M_.mapping.log_I.eqidx = [40 51 ];
M_.mapping.log_N.eqidx = [41 45 49 57 ];
M_.mapping.log_NC.eqidx = [42 58 ];
M_.mapping.log_NI.eqidx = [43 59 ];
M_.mapping.log_K.eqidx = [44 49 54 ];
M_.mapping.log_Y_N.eqidx = [45 53 ];
M_.mapping.log_D.eqidx = [46 61 ];
M_.mapping.log_p_I.eqidx = [47 56 ];
M_.mapping.log_util.eqidx = [48 60 ];
M_.mapping.C_obs.eqidx = [50 ];
M_.mapping.I_obs.eqidx = [51 ];
M_.mapping.Y_obs.eqidx = [52 55 ];
M_.mapping.Y_N_obs.eqidx = [53 ];
M_.mapping.p_I_obs.eqidx = [56 ];
M_.mapping.N_obs.eqidx = [55 57 ];
M_.mapping.NC_obs.eqidx = [58 ];
M_.mapping.NI_obs.eqidx = [59 ];
M_.mapping.util_obs.eqidx = [60 ];
M_.mapping.D_obs.eqidx = [61 ];
M_.mapping.K_obs.eqidx = [54 55 ];
M_.mapping.SR_obs.eqidx = [55 ];
M_.mapping.e_g.eqidx = [30 ];
M_.mapping.e_Z.eqidx = [31 ];
M_.mapping.e_ZI.eqidx = [32 ];
M_.mapping.e_N.eqidx = [34 ];
M_.mapping.e_D.eqidx = [35 ];
M_.mapping.e_DI.eqidx = [36 ];
M_.mapping.e_C.eqidx = [37 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [3 5 6 8 9 10 12 13 14 15 16 38 39 40 41 42 43 44 45 46 47 48 49 60 ];
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(61, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(23, 1);
M_.endo_trends = struct('deflator', cell(61, 1), 'log_deflator', cell(61, 1), 'growth_factor', cell(61, 1), 'log_growth_factor', cell(61, 1));
M_.NNZDerivatives = [244; -1; -1; ];
M_.static_tmp_nbr = [45; 14; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 2.0;
gam = M_.params(1);
M_.params(3) = 0.04;
r_ann = M_.params(3);
M_.params(4) = 0.00451;
g_bar = M_.params(4);
M_.params(2) = 0.25*log(1+M_.params(3))/M_.params(4);
gam_max = M_.params(2);
M_.params(5) = 0.72;
nu = M_.params(5);
M_.params(6) = 0.32;
sigma_a = M_.params(6);
M_.params(7) = 1.5;
Psi_K = M_.params(7);
M_.params(8) = 0.20;
I_Y = M_.params(8);
M_.params(9) = 11;
K_Y = M_.params(9);
M_.params(10) = 0.67;
labor_share = M_.params(10);
M_.params(11) = 0.2;
nu_R = M_.params(11);
M_.params(12) = 0.286;
m = M_.params(12);
M_.params(13) = 0.20;
eta = M_.params(13);
M_.params(14) = 0.81;
Psi = M_.params(14);
theta = 1/0.1735;
M_.params(22) = 1.0;
p_I_ss = M_.params(22);
M_.params(23) = 0.30;
N_ss = M_.params(23);
M_.params(15) = 0.1;
rho_g = M_.params(15);
M_.params(16) = 0.9;
rho_Z = M_.params(16);
M_.params(17) = 0.9;
rho_ZI = M_.params(17);
M_.params(18) = 0.9;
rho_N = M_.params(18);
M_.params(19) = 0.9;
rho_D = M_.params(19);
M_.params(20) = 0.9;
rho_DI = M_.params(20);
M_.params(21) = 0.9;
rho_C = M_.params(21);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 5.184e-05;
M_.Sigma_e(2, 2) = 5.184e-05;
M_.Sigma_e(3, 3) = 5.184e-05;
M_.Sigma_e(4, 4) = 5.184e-05;
M_.Sigma_e(5, 5) = 5.184e-05;
M_.Sigma_e(7, 7) = 5.184e-05;
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 1, 1.5, 1.0, M_.params(2), 1, 1.5, 0.25, 1.0, M_.params(2), NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, 0.32, 0.0, 10, 2, 0.32, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, 1.5, 0.0, 50, 2, 1.5, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 0.20, 0.00, 10.0, 2, 0.2, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.1, 0.0001, 0.9, 1, 0.1, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.95, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.95, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.6, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, 0.9, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.9, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.95, 0.01, 0.99999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.01, 0.00001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.01, 0.00001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.01, 0.0001, 0.4, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.01, 0.0001, 0.4, 4, 0.01, 0.1, NaN, NaN, NaN ];
options_.TeX=1;
options_.TeX = true;
options_.lik_init = 2;
options_.load_mh_file = true;
options_.mh_drop = 0.3;
options_.mh_init_scale = 0.0004;
options_.mh_jscale = 0.0015;
options_.mh_nblck = 2;
options_.mh_replic = 0;
options_.mode_check.status = true;
options_.mode_compute = 0;
options_.presample = 0;
options_.prior_trunc = 0;
options_.MCMC_jumping_covariance = 'prior_variance';
options_.datafile = 'observables_fd';
options_.mode_file = 'BRS_pred_labor_mode';
options_.optim_opt = '''MaxIter'',200';
options_.order = 1;
var_list_ = {'Y_obs';'Y_N_obs';'I_obs';'p_I_obs';'C_obs';'NC_obs';'NI_obs';'util_obs'};
oo_recursive_=dynare_estimation(var_list_);
write_latex_parameter_table;
write_latex_definitions;
write_latex_prior_table;
collect_latex_files;
options_.irf = 100;
options_.nofunctions = true;
options_.order = 1;
options_.periods = 0;
options_.conditional_variance_decomposition = [1;4;8;40;];
var_list_ = {'Y_obs';'Y_N_obs';'SR_obs';'I_obs';'p_I_obs';'C_obs';'NC_obs';'NI_obs';'util_obs';'D_obs';'log_Y';'log_Y_N';'log_SR';'log_K';'log_I';'log_p_I';'log_C';'log_N';'log_NC';'log_NI';'log_util';'log_D'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'BRS_pred_labor_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_pred_labor_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_pred_labor_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_pred_labor_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_pred_labor_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_pred_labor_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_pred_labor_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
