%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'BRS_gen';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(7,1);
M_.exo_names_tex = cell(7,1);
M_.exo_names_long = cell(7,1);
M_.exo_names(1) = {'e_g'};
M_.exo_names_tex(1) = {'{e_g}'};
M_.exo_names_long(1) = {'Labor-augmenting-technology growth shock'};
M_.exo_names(2) = {'e_Z'};
M_.exo_names_tex(2) = {'{e_Z}'};
M_.exo_names_long(2) = {'TFP shock'};
M_.exo_names(3) = {'e_ZI'};
M_.exo_names_tex(3) = {'{e_{ZI}}'};
M_.exo_names_long(3) = {'Investment-specific tech shock'};
M_.exo_names(4) = {'e_N'};
M_.exo_names_tex(4) = {'{e_N}'};
M_.exo_names_long(4) = {'Labor supply shock'};
M_.exo_names(5) = {'e_D'};
M_.exo_names_tex(5) = {'{e_D}'};
M_.exo_names_long(5) = {'Shopping disutility shock'};
M_.exo_names(6) = {'e_DI'};
M_.exo_names_tex(6) = {'{e_DI}'};
M_.exo_names_long(6) = {'Relative investment shopping disutility shock'};
M_.exo_names(7) = {'e_C'};
M_.exo_names_tex(7) = {'{e_C}'};
M_.exo_names_long(7) = {'Consumption preference shock'};
M_.endo_names = cell(63,1);
M_.endo_names_tex = cell(63,1);
M_.endo_names_long = cell(63,1);
M_.endo_names(1) = {'Y'};
M_.endo_names_tex(1) = {'{Y}'};
M_.endo_names_long(1) = {'output'};
M_.endo_names(2) = {'C'};
M_.endo_names_tex(2) = {'{C}'};
M_.endo_names_long(2) = {'consumption'};
M_.endo_names(3) = {'I'};
M_.endo_names_tex(3) = {'{I}'};
M_.endo_names_long(3) = {'investment'};
M_.endo_names(4) = {'K'};
M_.endo_names_tex(4) = {'{K}'};
M_.endo_names_long(4) = {'Capital'};
M_.endo_names(5) = {'K_C'};
M_.endo_names_tex(5) = {'{K_C}'};
M_.endo_names_long(5) = {'Capital:C'};
M_.endo_names(6) = {'K_I'};
M_.endo_names_tex(6) = {'{K_I}'};
M_.endo_names_long(6) = {'Capital:I'};
M_.endo_names(7) = {'N'};
M_.endo_names_tex(7) = {'{N}'};
M_.endo_names_long(7) = {'Hours'};
M_.endo_names(8) = {'N_C'};
M_.endo_names_tex(8) = {'{N_C}'};
M_.endo_names_long(8) = {'Hours:C'};
M_.endo_names(9) = {'N_I'};
M_.endo_names_tex(9) = {'{N_I}'};
M_.endo_names_long(9) = {'Hours:I'};
M_.endo_names(10) = {'N_comp'};
M_.endo_names_tex(10) = {'{N}'};
M_.endo_names_long(10) = {'Labor CES aggregate'};
M_.endo_names(11) = {'Z_C'};
M_.endo_names_tex(11) = {'{Z_C}'};
M_.endo_names_long(11) = {'Tech:C'};
M_.endo_names(12) = {'u_ZI'};
M_.endo_names_tex(12) = {'u\_ZI'};
M_.endo_names_long(12) = {'u_ZI'};
M_.endo_names(13) = {'Z_I'};
M_.endo_names_tex(13) = {'{Z_I}'};
M_.endo_names_long(13) = {'Tech:I'};
M_.endo_names(14) = {'theta_N'};
M_.endo_names_tex(14) = {'{\theta_N}'};
M_.endo_names_long(14) = {'Labor disutility'};
M_.endo_names(15) = {'theta_D'};
M_.endo_names_tex(15) = {'{\theta_D}'};
M_.endo_names_long(15) = {'Shopping disutility'};
M_.endo_names(16) = {'theta_I'};
M_.endo_names_tex(16) = {'{\theta_I}'};
M_.endo_names_long(16) = {'Relative shopping disutility'};
M_.endo_names(17) = {'theta_C'};
M_.endo_names_tex(17) = {'{\theta_C}'};
M_.endo_names_long(17) = {'Consumption preference shock'};
M_.endo_names(18) = {'R_C'};
M_.endo_names_tex(18) = {'{R_C}'};
M_.endo_names_long(18) = {'Capital rental rate:C'};
M_.endo_names(19) = {'R_I'};
M_.endo_names_tex(19) = {'{R_I}'};
M_.endo_names_long(19) = {'Capital rental rate:I'};
M_.endo_names(20) = {'W_C'};
M_.endo_names_tex(20) = {'{W}'};
M_.endo_names_long(20) = {'Real wage:C'};
M_.endo_names(21) = {'W_I'};
M_.endo_names_tex(21) = {'{W}'};
M_.endo_names_long(21) = {'Real wage:C'};
M_.endo_names(22) = {'h_C'};
M_.endo_names_tex(22) = {'{h_C}'};
M_.endo_names_long(22) = {'Capital utilization rate:C'};
M_.endo_names(23) = {'h_I'};
M_.endo_names_tex(23) = {'{h_I}'};
M_.endo_names_long(23) = {'Capital utilization rate:I'};
M_.endo_names(24) = {'delta_C'};
M_.endo_names_tex(24) = {'{\delta_C}'};
M_.endo_names_long(24) = {'Capital depreciation rate:C'};
M_.endo_names(25) = {'delta_I'};
M_.endo_names_tex(25) = {'{\delta_I}'};
M_.endo_names_long(25) = {'Capital depreciation rate:I'};
M_.endo_names(26) = {'delta_C_pr'};
M_.endo_names_tex(26) = {'{\delta_C}'};
M_.endo_names_long(26) = {'Capital depreciation rate derivative:C'};
M_.endo_names(27) = {'delta_I_pr'};
M_.endo_names_tex(27) = {'{\delta_I}'};
M_.endo_names_long(27) = {'Capital depreciation rate derivative:I'};
M_.endo_names(28) = {'S'};
M_.endo_names_tex(28) = {'S'};
M_.endo_names_long(28) = {'Investment adjustment cost'};
M_.endo_names(29) = {'S_pr'};
M_.endo_names_tex(29) = {'S_pr'};
M_.endo_names_long(29) = {'Derivative investment adjustment cost'};
M_.endo_names(30) = {'D'};
M_.endo_names_tex(30) = {'{D}'};
M_.endo_names_long(30) = {'Shopping effort'};
M_.endo_names(31) = {'D_C'};
M_.endo_names_tex(31) = {'{D}'};
M_.endo_names_long(31) = {'Shopping effort:C'};
M_.endo_names(32) = {'D_I'};
M_.endo_names_tex(32) = {'{D}'};
M_.endo_names_long(32) = {'Shopping effort:I'};
M_.endo_names(33) = {'Gam'};
M_.endo_names_tex(33) = {'{\Gamma}'};
M_.endo_names_long(33) = {'Composite utility term'};
M_.endo_names(34) = {'zeta'};
M_.endo_names_tex(34) = {'{\zeta}'};
M_.endo_names_long(34) = {'Wealth effects parameter'};
M_.endo_names(35) = {'p_I'};
M_.endo_names_tex(35) = {'{p_I}'};
M_.endo_names_long(35) = {'Relative investment price'};
M_.endo_names(36) = {'Q'};
M_.endo_names_tex(36) = {'{Q}'};
M_.endo_names_long(36) = {'Relative price of capital'};
M_.endo_names(37) = {'x'};
M_.endo_names_tex(37) = {'{x}'};
M_.endo_names_long(37) = {'Growth rate of investment'};
M_.endo_names(38) = {'log_SR'};
M_.endo_names_tex(38) = {'log\_SR'};
M_.endo_names_long(38) = {'Solow residual'};
M_.endo_names(39) = {'util'};
M_.endo_names_tex(39) = {'{util}'};
M_.endo_names_long(39) = {'Capacity utilization:'};
M_.endo_names(40) = {'g'};
M_.endo_names_tex(40) = {'{g}'};
M_.endo_names_long(40) = {'Growth rate of stochastic trend'};
M_.endo_names(41) = {'log_Y'};
M_.endo_names_tex(41) = {'log\_Y'};
M_.endo_names_long(41) = {'log_Y'};
M_.endo_names(42) = {'log_C'};
M_.endo_names_tex(42) = {'log\_C'};
M_.endo_names_long(42) = {'log_C'};
M_.endo_names(43) = {'log_I'};
M_.endo_names_tex(43) = {'log\_I'};
M_.endo_names_long(43) = {'log_I'};
M_.endo_names(44) = {'log_N'};
M_.endo_names_tex(44) = {'log\_N'};
M_.endo_names_long(44) = {'log_N'};
M_.endo_names(45) = {'log_NC'};
M_.endo_names_tex(45) = {'log\_NC'};
M_.endo_names_long(45) = {'log_NC'};
M_.endo_names(46) = {'log_NI'};
M_.endo_names_tex(46) = {'log\_NI'};
M_.endo_names_long(46) = {'log_NI'};
M_.endo_names(47) = {'log_K'};
M_.endo_names_tex(47) = {'log\_K'};
M_.endo_names_long(47) = {'log_K'};
M_.endo_names(48) = {'log_Y_N'};
M_.endo_names_tex(48) = {'log\_Y\_N'};
M_.endo_names_long(48) = {'log_Y_N'};
M_.endo_names(49) = {'log_D'};
M_.endo_names_tex(49) = {'log\_D'};
M_.endo_names_long(49) = {'log_D'};
M_.endo_names(50) = {'log_p_I'};
M_.endo_names_tex(50) = {'log\_p\_I'};
M_.endo_names_long(50) = {'log_p_I'};
M_.endo_names(51) = {'log_util'};
M_.endo_names_tex(51) = {'log\_util'};
M_.endo_names_long(51) = {'log_util'};
M_.endo_names(52) = {'C_obs'};
M_.endo_names_tex(52) = {'C\_obs'};
M_.endo_names_long(52) = {'C_obs'};
M_.endo_names(53) = {'I_obs'};
M_.endo_names_tex(53) = {'I\_obs'};
M_.endo_names_long(53) = {'I_obs'};
M_.endo_names(54) = {'Y_obs'};
M_.endo_names_tex(54) = {'Y\_obs'};
M_.endo_names_long(54) = {'Y_obs'};
M_.endo_names(55) = {'Y_N_obs'};
M_.endo_names_tex(55) = {'Y\_N\_obs'};
M_.endo_names_long(55) = {'Y_N_obs'};
M_.endo_names(56) = {'p_I_obs'};
M_.endo_names_tex(56) = {'p\_I\_obs'};
M_.endo_names_long(56) = {'p_I_obs'};
M_.endo_names(57) = {'N_obs'};
M_.endo_names_tex(57) = {'N\_obs'};
M_.endo_names_long(57) = {'N_obs'};
M_.endo_names(58) = {'NC_obs'};
M_.endo_names_tex(58) = {'NC\_obs'};
M_.endo_names_long(58) = {'NC_obs'};
M_.endo_names(59) = {'NI_obs'};
M_.endo_names_tex(59) = {'NI\_obs'};
M_.endo_names_long(59) = {'NI_obs'};
M_.endo_names(60) = {'util_obs'};
M_.endo_names_tex(60) = {'util\_obs'};
M_.endo_names_long(60) = {'util_obs'};
M_.endo_names(61) = {'D_obs'};
M_.endo_names_tex(61) = {'D\_obs'};
M_.endo_names_long(61) = {'D_obs'};
M_.endo_names(62) = {'K_obs'};
M_.endo_names_tex(62) = {'K\_obs'};
M_.endo_names_long(62) = {'K_obs'};
M_.endo_names(63) = {'SR_obs'};
M_.endo_names_tex(63) = {'SR\_obs'};
M_.endo_names_long(63) = {'SR_obs'};
M_.endo_partitions = struct();
M_.param_names = cell(26,1);
M_.param_names_tex = cell(26,1);
M_.param_names_long = cell(26,1);
M_.param_names(1) = {'gam'};
M_.param_names_tex(1) = {'{\gamma}'};
M_.param_names_long(1) = {'Risk aversion'};
M_.param_names(2) = {'gam_max'};
M_.param_names_tex(2) = {'{\gamma_{max}}'};
M_.param_names_long(2) = {'Upper bound on risk aversion'};
M_.param_names(3) = {'r_ann'};
M_.param_names_tex(3) = {'{r_ann}'};
M_.param_names_long(3) = {'Annual interest rate'};
M_.param_names(4) = {'g_bar'};
M_.param_names_tex(4) = {'{\overline{g}}'};
M_.param_names_long(4) = {'Quarterly trend growth rate'};
M_.param_names(5) = {'nu'};
M_.param_names_tex(5) = {'\nu'};
M_.param_names_long(5) = {'Frisch elasticity'};
M_.param_names(6) = {'sigma_s'};
M_.param_names_tex(6) = {'\sigma_s'};
M_.param_names_long(6) = {'wealth effect on labor supply'};
M_.param_names(7) = {'sigma_a'};
M_.param_names_tex(7) = {'{\sigma_a}'};
M_.param_names_long(7) = {'Inverse elasticity of marginal utilization cost wrt rental rate'};
M_.param_names(8) = {'Psi_K'};
M_.param_names_tex(8) = {'{\Psi_K}'};
M_.param_names_long(8) = {'Investment adjustment cost parameter'};
M_.param_names(9) = {'I_Y'};
M_.param_names_tex(9) = {'{I_Y}'};
M_.param_names_long(9) = {'Investment-output ratio'};
M_.param_names(10) = {'K_Y'};
M_.param_names_tex(10) = {'{K_Y}'};
M_.param_names_long(10) = {'Capital-output ratio (quarterly)'};
M_.param_names(11) = {'labor_share'};
M_.param_names_tex(11) = {'(labor share)'};
M_.param_names_long(11) = {'Labor share'};
M_.param_names(12) = {'nu_R'};
M_.param_names_tex(12) = {'{\nu_R}'};
M_.param_names_long(12) = {'Fixed cost share'};
M_.param_names(13) = {'ha'};
M_.param_names_tex(13) = {'{ha}'};
M_.param_names_long(13) = {'Habit persistence'};
M_.param_names(14) = {'m'};
M_.param_names_tex(14) = {'{m}'};
M_.param_names_long(14) = {'Ratio of price dispersion to consumption dispersion'};
M_.param_names(15) = {'eta'};
M_.param_names_tex(15) = {'{\eta}'};
M_.param_names_long(15) = {'Shopping disutility'};
M_.param_names(16) = {'Psi'};
M_.param_names_tex(16) = {'{\Psi}'};
M_.param_names_long(16) = {'Matching utilization'};
M_.param_names(17) = {'theta'};
M_.param_names_tex(17) = {'{\theta}'};
M_.param_names_long(17) = {'Inverse intersectoral elasticity of labor supply'};
M_.param_names(18) = {'rho_g'};
M_.param_names_tex(18) = {'{\rho_g}'};
M_.param_names_long(18) = {'persistence TFP growth shock'};
M_.param_names(19) = {'rho_Z'};
M_.param_names_tex(19) = {'{\rho_Z}'};
M_.param_names_long(19) = {'persistence TFP shock'};
M_.param_names(20) = {'rho_ZI'};
M_.param_names_tex(20) = {'{\rho_{ZI}}'};
M_.param_names_long(20) = {'persistence I-specific shock'};
M_.param_names(21) = {'rho_N'};
M_.param_names_tex(21) = {'{\rho_N}'};
M_.param_names_long(21) = {'persistence labor supply shock'};
M_.param_names(22) = {'rho_D'};
M_.param_names_tex(22) = {'{\rho_D}'};
M_.param_names_long(22) = {'persistence shopping effort shock'};
M_.param_names(23) = {'rho_DI'};
M_.param_names_tex(23) = {'{\rho_{DI}}'};
M_.param_names_long(23) = {'persistence relative shopping effort shock'};
M_.param_names(24) = {'rho_C'};
M_.param_names_tex(24) = {'{\rho_C}'};
M_.param_names_long(24) = {'persistence consumption preference shock'};
M_.param_names(25) = {'p_I_ss'};
M_.param_names_tex(25) = {'p\_I\_ss'};
M_.param_names_long(25) = {'p_I_ss'};
M_.param_names(26) = {'N_ss'};
M_.param_names_tex(26) = {'N\_ss'};
M_.param_names_long(26) = {'N_ss'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 7;
M_.endo_nbr = 63;
M_.param_nbr = 26;
M_.orig_endo_nbr = 63;
M_.aux_vars = [];
options_.varobs = cell(4, 1);
options_.varobs(1)  = {'I_obs'};
options_.varobs(2)  = {'Y_obs'};
options_.varobs(3)  = {'Y_N_obs'};
options_.varobs(4)  = {'p_I_obs'};
options_.varobs_id = [ 53 54 55 56  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(7, 7);
M_.Correlation_matrix = eye(7, 7);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 63;
M_.eq_nbr = 63;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 25 0;
 1 26 0;
 2 27 0;
 0 28 0;
 3 29 0;
 4 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 5 35 0;
 0 36 0;
 6 37 0;
 7 38 0;
 8 39 0;
 9 40 0;
 10 41 88;
 0 42 89;
 0 43 90;
 0 44 0;
 0 45 0;
 0 46 91;
 0 47 92;
 0 48 93;
 0 49 94;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 95;
 0 54 0;
 0 55 0;
 0 56 0;
 0 57 96;
 11 58 0;
 0 59 0;
 0 60 97;
 0 61 98;
 0 62 0;
 0 63 0;
 12 64 99;
 13 65 0;
 14 66 0;
 15 67 0;
 16 68 0;
 17 69 0;
 18 70 0;
 19 71 0;
 20 72 0;
 21 73 0;
 22 74 0;
 23 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 24 86 0;
 0 87 0;]';
M_.nstatic = 29;
M_.nfwrd   = 10;
M_.npred   = 22;
M_.nboth   = 2;
M_.nsfwrd   = 12;
M_.nspred   = 24;
M_.ndynamic   = 34;
M_.dynamic_tmp_nbr = [54; 21; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Labor composite' ;
  2 , 'name' , 'Labor leisure:C' ;
  3 , 'name' , 'Labor leisure:I' ;
  4 , 'name' , 'Shopping:C' ;
  5 , 'name' , 'Shopping:I' ;
  6 , 'name' , 'Composite utility term' ;
  7 , 'name' , 'Law of motion of wealth effects variable' ;
  8 , 'name' , 'Investment adjustment cost function' ;
  9 , 'name' , 'Investment adjustment cost function: derivative' ;
  10 , 'name' , 'Investment growth' ;
  11 , 'name' , 'Tobins Q' ;
  12 , 'name' , 'Euler equation: C' ;
  13 , 'name' , 'Euler equation: I' ;
  14 , 'name' , 'Utilization: C' ;
  15 , 'name' , 'Utilization: I' ;
  16 , 'name' , 'Depreciation rate: C' ;
  17 , 'name' , 'Depreciation rate: I' ;
  18 , 'name' , 'Depreciation rate derivative: C' ;
  19 , 'name' , 'Depreciation rate derivative: I' ;
  20 , 'name' , 'Consumption production' ;
  21 , 'name' , 'Investment production' ;
  22 , 'name' , 'Capital law of motion' ;
  23 , 'name' , 'Labor demand:C' ;
  24 , 'name' , 'Labor demand:I' ;
  25 , 'name' , 'Capital demand:C' ;
  26 , 'name' , 'Capital demand:I' ;
  27 , 'name' , 'Labor composition' ;
  28 , 'name' , 'Capital composition' ;
  29 , 'name' , 'Shopping composition' ;
  30 , 'name' , 'Output (base-year prices)' ;
  31 , 'name' , 'Capacity utilization' ;
  32 , 'name' , 'stochastic trend process' ;
  33 , 'name' , 'Stationary TFP process' ;
  34 , 'name' , 'Independent component of I-specific tech' ;
  35 , 'name' , 'Investment-specific TFP process' ;
  36 , 'name' , 'Labor supply process' ;
  37 , 'name' , 'Shopping effort process' ;
  38 , 'name' , 'Relative shopping effort process' ;
  39 , 'name' , 'Consumption preference process' ;
  40 , 'name' , 'Definition log output' ;
  41 , 'name' , 'Definition log consumption' ;
  42 , 'name' , 'Definition log investment' ;
  43 , 'name' , 'Definition log hours' ;
  44 , 'name' , 'log_NC' ;
  45 , 'name' , 'log_NI' ;
  46 , 'name' , 'log capital' ;
  47 , 'name' , 'Definition log labor productivity' ;
  48 , 'name' , 'Definition log shopping effort' ;
  49 , 'name' , 'Definition of log relative investment  price' ;
  50 , 'name' , 'Definition of log capacity utilization' ;
  51 , 'name' , 'Definition of log Solow residual' ;
  52 , 'name' , 'C_obs' ;
  53 , 'name' , 'I_obs' ;
  54 , 'name' , 'Y_obs' ;
  55 , 'name' , 'Y_N_obs' ;
  56 , 'name' , 'K_obs' ;
  57 , 'name' , 'SR_obs' ;
  58 , 'name' , 'p_I_obs' ;
  59 , 'name' , 'N_obs' ;
  60 , 'name' , 'NC_obs' ;
  61 , 'name' , 'NI_obs' ;
  62 , 'name' , 'util_obs' ;
  63 , 'name' , 'D_obs' ;
};
M_.mapping.Y.eqidx = [30 31 40 ];
M_.mapping.C.eqidx = [4 6 7 20 23 25 30 31 41 ];
M_.mapping.I.eqidx = [5 10 21 22 24 26 30 31 42 ];
M_.mapping.K.eqidx = [28 46 ];
M_.mapping.K_C.eqidx = [20 22 25 28 31 ];
M_.mapping.K_I.eqidx = [21 22 26 28 31 ];
M_.mapping.N.eqidx = [27 43 ];
M_.mapping.N_C.eqidx = [1 2 20 23 27 31 44 ];
M_.mapping.N_I.eqidx = [1 3 21 24 27 31 45 ];
M_.mapping.N_comp.eqidx = [1 2 3 6 ];
M_.mapping.Z_C.eqidx = [20 33 35 ];
M_.mapping.u_ZI.eqidx = [34 35 ];
M_.mapping.Z_I.eqidx = [21 34 35 ];
M_.mapping.theta_N.eqidx = [2 3 6 36 ];
M_.mapping.theta_D.eqidx = [4 5 6 7 37 ];
M_.mapping.theta_I.eqidx = [5 29 38 ];
M_.mapping.theta_C.eqidx = [2 3 4 5 6 7 11 12 13 39 ];
M_.mapping.R_C.eqidx = [12 14 25 ];
M_.mapping.R_I.eqidx = [13 15 26 ];
M_.mapping.W_C.eqidx = [2 23 ];
M_.mapping.W_I.eqidx = [3 24 ];
M_.mapping.h_C.eqidx = [12 16 18 20 25 31 ];
M_.mapping.h_I.eqidx = [13 17 19 21 26 31 ];
M_.mapping.delta_C.eqidx = [12 16 22 ];
M_.mapping.delta_I.eqidx = [13 17 22 ];
M_.mapping.delta_C_pr.eqidx = [14 18 ];
M_.mapping.delta_I_pr.eqidx = [15 19 ];
M_.mapping.S.eqidx = [8 11 22 ];
M_.mapping.S_pr.eqidx = [9 11 ];
M_.mapping.D.eqidx = [4 5 6 7 29 48 ];
M_.mapping.D_C.eqidx = [4 20 23 25 29 31 ];
M_.mapping.D_I.eqidx = [5 21 24 26 29 31 ];
M_.mapping.Gam.eqidx = [6 11 12 13 ];
M_.mapping.zeta.eqidx = [2 3 6 7 ];
M_.mapping.p_I.eqidx = [5 11 24 26 49 ];
M_.mapping.Q.eqidx = [11 12 13 14 15 ];
M_.mapping.x.eqidx = [8 9 10 11 ];
M_.mapping.log_SR.eqidx = [51 ];
M_.mapping.util.eqidx = [31 50 ];
M_.mapping.g.eqidx = [10 11 12 13 20 21 22 25 26 32 52 53 54 55 56 ];
M_.mapping.log_Y.eqidx = [40 47 51 54 ];
M_.mapping.log_C.eqidx = [41 52 ];
M_.mapping.log_I.eqidx = [42 53 ];
M_.mapping.log_N.eqidx = [43 47 51 59 ];
M_.mapping.log_NC.eqidx = [44 60 ];
M_.mapping.log_NI.eqidx = [45 61 ];
M_.mapping.log_K.eqidx = [46 51 56 ];
M_.mapping.log_Y_N.eqidx = [47 55 ];
M_.mapping.log_D.eqidx = [48 63 ];
M_.mapping.log_p_I.eqidx = [49 58 ];
M_.mapping.log_util.eqidx = [50 62 ];
M_.mapping.C_obs.eqidx = [52 ];
M_.mapping.I_obs.eqidx = [53 ];
M_.mapping.Y_obs.eqidx = [54 57 ];
M_.mapping.Y_N_obs.eqidx = [55 ];
M_.mapping.p_I_obs.eqidx = [58 ];
M_.mapping.N_obs.eqidx = [57 59 ];
M_.mapping.NC_obs.eqidx = [60 ];
M_.mapping.NI_obs.eqidx = [61 ];
M_.mapping.util_obs.eqidx = [62 ];
M_.mapping.D_obs.eqidx = [63 ];
M_.mapping.K_obs.eqidx = [56 57 ];
M_.mapping.SR_obs.eqidx = [57 ];
M_.mapping.e_g.eqidx = [32 ];
M_.mapping.e_Z.eqidx = [33 ];
M_.mapping.e_ZI.eqidx = [34 ];
M_.mapping.e_N.eqidx = [36 ];
M_.mapping.e_D.eqidx = [37 ];
M_.mapping.e_DI.eqidx = [38 ];
M_.mapping.e_C.eqidx = [39 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [2 3 5 6 11 13 14 15 16 17 34 40 41 42 43 44 45 46 47 48 49 50 51 62 ];
M_.exo_names_orig_ord = [1:7];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(63, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(7, 1);
M_.params = NaN(26, 1);
M_.endo_trends = struct('deflator', cell(63, 1), 'log_deflator', cell(63, 1), 'growth_factor', cell(63, 1), 'log_growth_factor', cell(63, 1));
M_.NNZDerivatives = [261; -1; -1; ];
M_.static_tmp_nbr = [52; 17; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 2.0;
gam = M_.params(1);
M_.params(3) = 0.04;
r_ann = M_.params(3);
M_.params(4) = 0.0045;
g_bar = M_.params(4);
M_.params(2) = 0.25*log(1+M_.params(3))/M_.params(4);
gam_max = M_.params(2);
M_.params(5) = 0.72;
nu = M_.params(5);
M_.params(6) = 0.5;
sigma_s = M_.params(6);
M_.params(7) = 0.32;
sigma_a = M_.params(7);
M_.params(8) = 1.5;
Psi_K = M_.params(8);
M_.params(13) = 0.1;
ha = M_.params(13);
M_.params(9) = 0.20;
I_Y = M_.params(9);
M_.params(10) = 11;
K_Y = M_.params(10);
M_.params(11) = 0.67;
labor_share = M_.params(11);
M_.params(12) = 0.2;
nu_R = M_.params(12);
M_.params(14) = 0.286;
m = M_.params(14);
M_.params(15) = 0.20;
eta = M_.params(15);
M_.params(16) = 0.81;
Psi = M_.params(16);
M_.params(17) = 0.5;
theta = M_.params(17);
M_.params(25) = 1.0;
p_I_ss = M_.params(25);
M_.params(26) = 0.30;
N_ss = M_.params(26);
M_.params(18) = 0.1;
rho_g = M_.params(18);
M_.params(19) = 0.9;
rho_Z = M_.params(19);
M_.params(20) = 0.9;
rho_ZI = M_.params(20);
M_.params(21) = 0.9;
rho_N = M_.params(21);
M_.params(22) = 0.9;
rho_D = M_.params(22);
M_.params(23) = 0.9;
rho_DI = M_.params(23);
M_.params(24) = 0.9;
rho_C = M_.params(24);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 5.184e-05;
M_.Sigma_e(2, 2) = 5.184e-05;
M_.Sigma_e(3, 3) = 5.184e-05;
M_.Sigma_e(4, 4) = 5.184e-05;
M_.Sigma_e(5, 5) = 5.184e-05;
M_.Sigma_e(6, 6) = 5.184e-05;
M_.Sigma_e(7, 7) = 5.184e-05;
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 1, 1.5, 1.0, M_.params(2), 1, 1.5, 0.25, 1.0, M_.params(2), NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 0.5, 0.0, 0.95, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, 0.72, 0.05, 2.0, 2, 0.72, 0.25, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, 0.5, 0.0, 1.0, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 0.286, 0.0, 0.95, 2, 0.286, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, 0.32, 0.0, 10, 4, 1, 1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, 1.5, 0.0, 50, 2, 4, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.20, 0.00, 10.0, 2, 0.2, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.5, .00, 10, 2, 1, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.1, 0.0001, 0.9, 1, 0.1, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 19, 0.95, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 20, 0.95, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 21, 0.6, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 22, 0.9, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 23, 0.9, 0.01, 0.9999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, 0.95, 0.01, 0.99999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.01, 0.00001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.01, 0.00001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.01, 0.0001, 0.4, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 6, 0.01, 0.0001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 7, 0.01, 0.0001, 0.4, 4, 0.01, 0.1, NaN, NaN, NaN ];
options_.TeX=1;
options_.TeX = true;
options_.lik_init = 2;
options_.mh_drop = 0.3;
options_.mh_init_scale = 0.0001;
options_.mh_jscale = 0.1;
options_.mh_nblck = 2;
options_.mh_replic = 150000;
options_.mode_check.status = true;
options_.mode_compute = 4;
options_.presample = 0;
options_.prior_trunc = 0;
options_.datafile = 'observables_sectoral';
options_.mode_file = 'BRS_gen_mode';
options_.optim_opt = '''MaxIter'',200';
options_.order = 1;
var_list_ = {'Y_obs';'Y_N_obs';'I_obs';'p_I_obs';'C_obs';'NC_obs';'NI_obs';'util_obs'};
oo_recursive_=dynare_estimation(var_list_);
write_latex_parameter_table;
write_latex_definitions;
write_latex_prior_table;
generate_trace_plots(1);
collect_latex_files;
options_.irf = 100;
options_.nofunctions = true;
options_.order = 1;
options_.periods = 0;
options_.conditional_variance_decomposition = [1;4;8;40;];
var_list_ = {'Y_obs';'Y_N_obs';'SR_obs';'I_obs';'p_I_obs';'C_obs';'NC_obs';'NI_obs';'util_obs';'D_obs';'log_Y';'log_Y_N';'log_SR';'log_I';'log_p_I';'log_C';'log_N';'log_NC';'log_NI';'log_util';'log_D'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'BRS_gen_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_gen_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_gen_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_gen_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_gen_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_gen_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'BRS_gen_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
